### ISSUE TITLE
[INFO] limitation à zoom 16 pour les sources Institut Cartogràfic i Geològic de Catalunya

### ISSUE THREAD

**Issue by paulgirard** [geotribu/website#1027]
Merci beaucoup pour cette ressource très utile.
Notamment les sources de tuilrs vectorielles.

Je viens de découvrir que les tuiles de l'Institut Cartogràfic i Geològic de Catalunya sont limitées à un zoom de 16.
Ça pourrais être utile de prévenir les futur⋅e⋅s utilisateur⋅rices.

Pour info j'ai trouvé une autre source librement accessible mais que pour des tests gentiment maintenues par la communauté OpenStreetMap FR :
https://tile-vect.openstreetmap.fr/
https://github.com/osm-fr/infrastructure

**Comment by Guts** [comment]
Bonjour,

Merci pour votre message mais de quel contenu parlez-vous ?

Pour votre information, les issues Github sont soit là pour signaler un problème technique, soit une proposition d'aide, d'idée, fonctionnelle ou rédactionnelle (news, article...).

Mais pour commenter un contenu publié, il faut passer par le bloc de commentaires en bas de page sur le site.

**Comment by paulgirard** [comment]
Ah au temps pour moi.
C'était ici : https://geotribu.fr/articles/2021/2021-02-23_carte_ligne_libre/
J'ai ajouté un commentaire en bas de page.

**Comment by Guts** [comment]
Merci d'avoir fait l'effort pour remettre le commentaire au bon endroit :pray:. Ça nous a aussi permis de nous rendre compte que les notifications étaient cassées et on a pu corriger cela hier.

cc @bmericskay pour répondre aux commentaires sur ton article.
