### ISSUE TITLE
De la tolérance en SIG

### ISSUE THREAD

**Issue by lbartoletti** [geotribu/website#1150]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui
- [ ] Non

### Votre nom

Loïc Bartoletti

### Votre adresse email

lituus@free.fr

### Licence

Creative Commons International BY-NC-SA 4.0

### Titre

De la tolérance en SIG

### Description courte

Régulièrement, j’ai des questions sur certaines « irrégularités » rencontrées lors d’opérations courantes :      Pourquoi l’accrochage dans QGIS ne se positionne-t-il pas toujours exactement sur la géométrie ?     Pourquoi les calculs lors des opérations de superposition semblent manquer de précision ?     Et pourquoi un calcul et son inverse ne produisent-ils pas toujours des résultats cohérents ?  Ces questions reflètent des préoccupations courantes parmi les utilisateurs de SIG, qui s’attendent à une exactitude et à une précision rigoureuses. Mais, les 3 R : rigueur, rigueur, rigueur, cher à un de mes anciens chefs, ce n’est pas toujours… de rigueur sur nos ordinateurs.  Alors que je préparais un article sur la topologie que je dois à Julien depuis plusieurs mois, j’ai été frappé par ce que l’on appelle le phénomène Baader-Meinhof, ou l’illusion de fréquence : soudainement, ce sujet paraît surgir partout, des cours aux discussions en ligne. Entre les issues signalées et les conversations avec mes collègues, j’ai décidé de changer mon fusil d’épaule. Plutôt que de continuer sur le chemin prévu, j’ai opté pour réaliser plusieurs séries d’articles, explorant certains traitements, « problèmes », différences dans les SIG. Cet article, subdivisé en chapitres, fera partie d’une série qui vise donc à montrer le dessous des SIG.

### Mots-clés

analyse,géométrie,topologie,qgis,geos,postgis,sfcgal,arcgis,fme,grass,saga

### Date de publication envisagée

Cf planning de Julien pour la série :)

### Contenu de l'article

De la tolérance en SIG

### Message libre

J'ouvre cette première pour faire une première relecture globale. Il devra être séparé en plusieurs parties pour la publication.

**Comment by lbartoletti** [comment]
Je ne me souvenais plus que ça ne faisait pas la PR automatiquement.

Fermé au profit de https://github.com/geotribu/website/pull/1151

**Comment by Guts** [comment]
> Je ne me souvenais plus que ça ne faisait pas la PR automatiquement.

Un jour viendra... mais c'est délicat de tout gérer. L'idée de l'issue de proposition d'article c'est plutôt proposition d'un projet d'article pour valider / échanger en amont.
