### ISSUE TITLE
Publication du support « Comprendre les données géographiques »

### ISSUE THREAD

**Issue by nicolas-roelandt** [geotribu/website#1154]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui et je détaille dans quelle mesure dans la partie commentaire libre
- [ ] Non

### Votre nom

Nicolas ROELANDT

### Votre adresse email

nicolas.roelandt[at]univ-eiffel.fr

### Licence

- [X] J'accepte

### Compte Mastodon

@NRoelandt@social.sciences.re

### Section / catégorie

Sorties de la semaine

### Mots-clés

formation, données

### Titre de la news

Publication du support « Comprendre les données géographiques »

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

« Comprendre les données géospatiales » est un module
d'auto-apprentissage pour découvrir les spécificités des données
géospatiales. 

Destiné aux doctorants et professionnels amenés à
manipuler ce genre de données n'ayant pas suivi de cursus en géographie, 
il vise à fournir un premier aperçu sur ce qu'est une donnée
géospatiale, quels sont les types et formats les plus courants ainsi
qu'une brève recension de sources de données géospatiales ouvertes. 
Un focus est porté sur les systèmes de référence de coordonnées qui peuvent
être sources de confusion pour les personnes peu habituées à manipuler
des données géospatiales.

Il est publié sur la plateforme Callisto: https://callisto-formation.fr/course/view.php?id=376

### Message libre

Ce module a été créé par Nicolas Roelandt (Université Gustave Eiffel),
Marion Maisonobe (CNRS/Géographie-cités) avec l'appui d'Olivier Lu
(URFIST Lyon) et de Viêt Jeannaud (Fondation Callisto) dans le cadre de la
plateforme DoRANum.

**Comment by Guts** [comment]
@nicolas-roelandt merci. Si tu as une image, c'est top !

**Comment by nicolas-roelandt** [comment]
@Guts Je sais pas si je dois éditer le premier commentaire alors je la pose là:

![vignette-comprendre-donnees-geographiques](https://github.com/geotribu/website/assets/86657953/6285a135-c677-46bc-8c62-8a7041f81e3c)

**Comment by gounux** [comment]
merci @nicolas-roelandt !
ça te convient le rendu ? https://preview-pullrequest-1077--geotribu-preprod.netlify.app/rdp/2024/rdp_2024-07-12/#publication-du-support-comprendre-les-donnees-geographiques

**Comment by nicolas-roelandt** [comment]
@gounux Farpait ! Merci :)

**Comment by Guts** [comment]
je mettrais bien l'image après le second paragraphe pour bien aérer par rapport à l'icône
