### ISSUE TITLE
Des cartes et des couleurs : enquête sur les gradients

### ISSUE THREAD

**Issue by ljegou** [geotribu/website#1155]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui et je détaille dans quelle mesure dans la partie commentaire libre
- [ ] Non

### Votre nom

Laurent JÉGOU

### Votre adresse email

jegou@univ-tlse2.fr

### Licence

- [X] J'accepte

### Compte LinkedIn

https://www.linkedin.com/in/laurentjegou/

### Compte Mastodon

https://vis.social/@ljegou

### Compte Twitter

@ljegou

### Section / catégorie

Représentation Cartographique

### Mots-clés

couleur, cartographie, Observable, recherche

### Titre de la news

Des cartes et des couleurs : enquête sur les gradients

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

![visuel_ljegou2024](https://github.com/geotribu/website/assets/5158753/3709ad01-d496-4f0f-9930-f9d4767a5447)

Mes recherches s'intéressent depuis longtemps aux usages de la _couleur_ en cartographie thématique. 

Dernièrement, je propose d'évaluer la progression lumineuse des gradients standards et de l'adapter en luminosité pour suivre la progression des valeurs représentées, ce qui permet de mieux exprimer les valeurs de la variable. Une enquête en ligne tend à montrer que c'est bien le cas : les données sont plus lisibles lorsque le gradient de couleurs est adapté à leur progression.

J'ai présenté ces travaux dans un webinaire "Carte Blanche" de [l'AR9](https://github.com/magisAR9) (action de recherche) du [GDR Magis](http://gdr-magis.imag.fr/) (Groupe de laboratoires sur l'information géographique du CNRS).

- L'annonce et les liens utiles : [https://github.com/magisAR9/webinaires/blob/main/cartogeoviz16-ljegou.md](https://github.com/magisAR9/webinaires/blob/main/cartogeoviz16-ljegou.md)
- La vidéo de la présentation : [https://bbb-prod-rp.unistra.fr/playback/presentation/2.3/99470eae0814dfe5c9cca017ea6e2edc6966dada-1719308957319](https://bbb-prod-rp.unistra.fr/playback/presentation/2.3/99470eae0814dfe5c9cca017ea6e2edc6966dada-1719308957319)

### Message libre

Laurent Jégou est enseignant-chercheur en géomatique à l'université de Toulouse - Jean Jaurès et à l'UMR LISST du CNRS.

**Comment by gounux** [comment]
merci @ljegou !

C'est visualisable ici : https://preview-pullrequest-1077--geotribu-preprod.netlify.app/rdp/2024/rdp_2024-07-12/#des-cartes-et-des-couleurs-enquete-sur-les-gradients
