### ISSUE TITLE
Pgdays à Lille du 11 et 12 Juin

### ISSUE THREAD

**Issue by thomas-szczurek** [geotribu/website#1156]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui et je détaille dans quelle mesure dans la partie commentaire libre
- [X] Non

### Votre nom

Thomas Szczurek-Gayant

### Votre adresse email

thomas.szczurek@gmail.com

### Licence

- [X] J'accepte

### Compte Mastodon

@thomas_szczurek@mapstodon.space

### Section / catégorie

Geo-event

### Mots-clés

PostgreSQL, PostGIS

### Titre de la news

Les pgdays à Lille !

### Icône de la news

https://cdn.geotribu.fr/tinyfilemanager.php?p=logos-icones%2Flogiciels_librairies&view=postgresql.png

### Contenu de la news

Le 11 et 12 Juin c'était les pgdays à Lille ! Les rencontres utilisateurs de PostgreSQL. Les replays ne sont pas encore disponibles mais vous pourrez les retrouver [ici](https://www.youtube.com/@PostgresqlFr). Pour le moment vous pouvez consulter le [programme](https://pgday.fr/programme) des différents ateliers et conférences qui se sont déroulés. Spécifiquement sur le spatial, il y avait une présentation de l'H3 indexing, et l'IGN était présente à la table ronde inter-entreprises. Sinon je ne peux que vous conseiller les histoires qui font peur, où vous pourrez découvir ce qui se passe quand on ne configure pas work_mem en prod.

**Comment by gounux** [comment]
salut @thomas-szczurek et merci !

C'est visible ici : https://preview-pullrequest-1077--geotribu-preprod.netlify.app/rdp/2024/rdp_2024-07-12/#les-pgdays-a-lille
