### ISSUE TITLE
Le thème sombre rend les champs texte illisibles

### ISSUE THREAD

**Issue by sguimmara** [geotribu/website#1159]
J'ai un thème sombre par défaut sur mon PC, qui agit aussi sur les pages web, et en l'occurence les champs texte reste en version claire, et leur contenu est illisible

![image](https://github.com/geotribu/website/assets/5512096/f572efac-7ec5-43dd-9eac-bb8afcf84550)

**Comment by Guts** [comment]
C'est à voir du côté du CSS d'isso je pense qui vient de le variabiliser https://github.com/isso-comments/isso/pull/1001. 
Pour info, je ne suis pas bien capé en CSS pour améliorer cela donc si quelqu'un veut prendre l'action...

Pour info le déploiement avec les fichiers de configuration du système de commentaires est dans ce dépôt : https://github.com/geotribu/infra/tree/master/ansible/roles/comments.geotribu.fr
