### ISSUE TITLE
Podcast de carte 

### ISSUE THREAD

**Issue by Maxime-ArtisansCartos** [geotribu/website#1166]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui et je détaille dans quelle mesure dans la partie commentaire libre
- [ ] Non

### Votre nom

Maxime Salles

### Votre adresse email

maxime@les-artisans-cartographes.fr

### Licence

- [X] J'accepte

### Compte LinkedIn

https://www.linkedin.com/in/maximesalles

### Compte Twitter

@Artisans_Cartos

### Section / catégorie

Sorties de la semaine

### Mots-clés

podcast, cartapaname

### Titre de la news

Cartapaname - un podcast sur les cartes

### Icône de la news

logo du podcast

### Contenu de la news

Je suis ravi de vous annoncer la création d'une émission de radio dédiée à la cartographie, une émission sur l'art et la manière de faire des cartes.

Une fois par mois, explorons ensemble le travail d'un ou d'une cartographe. À travers ses productions, l'invité nous promène sur les territoires qu'il explore. Manipulation de données, techniques de création, choix graphique, ... autant de thèmes abordés pour mieux comprendre ce métier, et mieux appréhender les savoir-faire de celles et ceux qui nous donnent à voir le monde.

L'émission est enregistrée dans les locaux de la Radio RapTz avec le soutien de l'association Les Artisans Cartographes.

Pour le 1er épisode (sorti en juin), j'ai reçu Lucas Destrem. Fondateur de GéoGraphismes et cartographe passionné, Lucas se distingue par son approche originale, traitant toujours des données singulières. Grâce à cela, ses cartes sont toujours une découverte, offrant un regard inédit sur les territoires qu'il explore. 

Pendant l'emission, il nous a fait découvrir son univers à travers 3 créations :
- Son exposition sur la compagnie des ZooDépartements, où il révèle comment les formes animales peuvent être trouvées dans la géographie des départements français. 
- Son plan culturel et artistique du métro de Paris, où chaque station est renommée en fonction du lieu culturel le plus proche. 
- Son travail de recherche sur les panneaux routiers, explorant les histoires et les significations derrière ces symboles du quotidien. 

La page de l'émission sur le site de la radio : https://www.raptz.com/shows/cartapaname
Toutes les émissions sont et seront ré-écoutables en podcast : https://www.raptz.com/podcast/cartapaname-01-lucas-destrem

Rendez-vous en septembre pour le prochain numéro.

![podcast_cartapaname](https://github.com/geotribu/website/assets/175006188/d8f29127-eaf7-4001-bccd-5e25337b965e)

**Comment by Guts** [comment]
Bonsoir @Maxime-ArtisansCartos ,

Merci pour la contribution.
Je me suis permis de légèrement amendé la fin pour préférer une intégration du lecteur SoundCloud directement. Visible en preview ici : https://preview-pullrequest-1077--geotribu-preprod.netlify.app/rdp/2024/rdp_2024-07-12/#cartapaname-un-podcast-sur-les-cartes
