### ISSUE TITLE
RDP de Juillet : Les lignes de force du vote RN en 2024 : une cartographie lissée avec la grille H3

### ISSUE THREAD

**Issue by lbartoletti** [geotribu/website#1168]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui et je détaille dans quelle mesure dans la partie commentaire libre
- [X] Non

### Votre nom

Loïc Bartoletti

### Votre adresse email

lituus@free.fr

### Licence

- [X] J'accepte

### Compte LinkedIn

https://linkedin.com/in/lbartoletti

### Section / catégorie

Représentation Cartographique

### Mots-clés

Cartographie,H3,DuckDB,MapShaper,Élections,Choroplèthe

### Titre de la news

Les lignes de force du vote RN en 2024 : une cartographie lissée avec la grille H3

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

[Eric Mauvière](https://www.linkedin.com/in/ericmauviere/) a poussé sur [LinkedIn](https://www.linkedin.com/posts/ericmauviere_les-lignes-de-force-du-vote-rn-en-2024-activity-7217079994542346242-PZqo) une technique de cartographie lissée pour visualiser les résultats électoraux à l'échelle nationale. Cette méthode combine :

- la grille hexagonale H3 pour un maillage uniforme du territoire ;
- un lissage par disque mobile pour révéler les tendances de vote ;
- des outils comme DuckDB (SQL), H3 (maillage) et Mapshaper (cartographie web).

Appliquée aux résultats du RN aux européennes 2024, cette approche offre une alternative aux cartes choroplèthes ou à symboles classiques. Elle prend en compte la géographie et les différences de population pour une représentation plus nuancée des tendances.
Cette méthode de lissage spatial est adaptable à divers sujets, il ne reste qu'à vous les approprier.

[Lien vers l'article pour le tutoriel détaillé](https://www.icem7.fr/cartographie/les-lignes-de-force-du-vote-rn-en-2024/)

**Comment by gounux** [comment]
Merci Loïc !

**Comment by Guts** [comment]
Merci @ericemc3 surtout :wink:
