### ISSUE TITLE
Comment l’archéologie entre progressivement dans l’ère du logiciel libre

### ISSUE THREAD

**Issue by Bakaniko** [geotribu/website#1170]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui et je détaille dans quelle mesure dans la partie commentaire libre
- [X] Non

### Votre nom

Nicolas Roelandt

### Votre adresse email

roelandtn.pro@gmail.com

### Licence

- [X] J'accepte

### Compte Mastodon

@Roelandtn@social.sciences.re

### Section / catégorie

En bref

### Mots-clés

archéologie, géomatique, logiciels libres

### Titre de la news

Comment l’archéologie entre progressivement dans l’ère du logiciel libre

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

L’archéologie est un domaine qui, depuis ses débuts, s’attache au catalogage, à la structuration et l’archivage de données issues de fouilles. Sur le terrain, elle a longtemps reposé sur la création de fiches, la collecte manuelle d’information sur papier, et le dessin à la main, retranscrit lors des phases d’étude sur support numérique. Ce n’est que récemment que certains archéologues ont lancé le mouvement de la fouille « tout numérique ». Je vous propose de raconter ici l’histoire de la numérisation de l’archéologie, qui, comme vous allez le voir, repose en partie sur le logiciel libre. 

Un article de [lovasoa](https://ophir.dev/) sur [LinuxFr.org](https://linuxfr.org/news/comment-l-archeologie-entre-progressivement-dans-l-ere-du-logiciel-libre), avec des très gros morceaux de QGIS et PostGIS dedans.

### Message libre

Je ne suis pas l'auteur de cet article.

**Comment by Bakaniko** [comment]
J'ai édité le lien, je n'avais pas mis le bon...

**Comment by gounux** [comment]
merci @Bakaniko ! Je me suis permis de déplacer la news dans la partie "Divers"

C'est visible ici et ça devrait partir dans l'après-midi : https://preview-pullrequest-1077--geotribu-preprod.netlify.app/rdp/2024/rdp_2024-07-12/#comment-larcheologie-entre-progressivement-dans-lere-du-logiciel-libre

**Comment by Bakaniko** [comment]
@gounux tu as bien fait, c'est vous qui gérez le processus éditorial :)
Merci d'avoir pris le temps de l'intégrer dans les dernières heures.

**Comment by Guts** [comment]
Merci !

J'ai cru un moment que c'était Frédéric Couchet _himself_ qui avait soumis la news ! 

Je me suis permis d'ajouter une icône archéo et une capture d'écran.
