### ISSUE TITLE
Créer un venv sous Windows pour le développement de plugin QGIS sous VSCode

### ISSUE THREAD

**Issue by nicogodet** [geotribu/website#1201]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui
- [ ] Non

### Votre nom

Nicolas Godet

### Votre adresse email

nicolas.godet@outlook.fr

### Licence

Beerware (Révision 42)

### Titre

Créer un venv sous Windows pour le développement de plugin QGIS sous VSCode

### Description courte

De nombreux articles proposent des méthodes pour paramétrer VSCode afin d'avoir l'autocomplétion PyQGIS sous Windows. Beaucoup ne sont pas à jour, d'autres sont incomplets et même certains ne fonctionnent pas. Voici une méthode qui fontionne !

### Mots-clés

pyqgis,python,windows,vscode,plugin qgis

### Date de publication envisagée

Soon tm

### Contenu de l'article

Méthode brute nécessite un habillage pour en faire un article propre.
# Dev

## Créer l'environnement

```sh
C:\OSGeo4W\bin\python-qgis.bat -m venv --system-site-packages .venv
C:\OSGeo4W\bin\python-qgis.bat -c "import pathlib;import qgis;print(str((pathlib.Path(qgis.__file__)/'../..').resolve()))" > .venv\qgis.pth
```

Si ces commandes sont exécutées depuis PowerShell, changer l'encodage du fichier `.venv\qgis.pth` à `UTF-8`.

Pour une meilleure intégration, le fichier `.venv\qgis.pth` peut ressembler à :

```text
C:\OSGeo4W\apps\qgis\python
C:\OSGeo4W\apps\qgis\python\plugins
C:\OSGeo4W\apps\Python312\Lib\site-packages
```

Créer le fichier `sitecustomize.py` dans `.venv\Lib\site-packages` avec le contenu :

```python
import os

os.add_dll_directory("C:/OSGeo4W/bin")
os.add_dll_directory("C:/OSGeo4W/apps/qgis/bin")
os.add_dll_directory("C:/OSGeo4W/apps/Qt5/bin")
```

Mettre à jour `.venv\pyvenv.cfg` en remplaçant les occurences `C:\OSGeo4W\bin` par `C:\OSGeo4W\apps\Python312`.
Le fichier devrait ressembler à:

```yaml
home = C:\OSGeo4W\apps\Python312
include-system-site-packages = true
version = 3.12.6
executable = C:\OSGeo4W\apps\Python312\python.exe
command = C:\OSGeo4W\apps\Python312\python.exe -m venv --system-site-packages blablabla
```

----

TODO :

- [ ] Généraliser les chemins
- [ ] Sourcer
- [ ] Capture d'écran VSCode
- [ ] Exemples

**Comment by Guts** [comment]
Salut @nicogodet 

merci pour la proposition d'article. Mais franchement, étant donné ton niveau en GitHub, je pense que tu peux filer directement à l'étape fork --> PR https://contribuer.geotribu.fr/articles/workflow/#je-nai-pas-acces-en-ecriture

**Comment by Guts** [comment]
Dossier créé sur le CDN https://cdn.geotribu.fr/tinyfilemanager.php?p=articles-blog-rdp%2Farticles%2F2024%2Fpyqgis_environnement_dev_windows
