### ISSUE TITLE
[News GeoRDP] mviewer 3.4

### ISSUE THREAD

**Issue by bchartier** [geotribu/website#216]
# News

## Section cible

Un seul choix possible :

- [ ] Sorties de la semaine
- [ ] Client
- [ ] Serveur
- [ ] Logiciel
- [ ] Représentation Cartographique
- [ ] OpenStreetMap
- [ ] Google
- [ ] Open Data
- [ ] Geo-event
- [ ] Divers
- [x] En bref

----

## Titre
Sortie de mviewer 3.4

## Image de la vignette
Pas de logo

## Contenu
[mviewer](https://mviewer.netlify.app) (client cartographique né de GéoBretagne) est passé en [version 3.4](https://github.com/geobretagne/mviewer/releases/tag/v3.4).

## Medias d'illustration (images, vidéos, tweets, etc.)

----

## Texte final à copier/coller

```markdown
## {{ news.section }}

### {{ news.title }}

![{{ news.thumbnail.replace_txt }}]({{ news.thumbnail.url }} "{{ news.thumbnail.caption }}"){: .img-rdp-news-thumb loading=lazy }

{{ news.body }}
```

**Comment by Guts** [comment]
Merci @bchartier . Par contre, vu qu'il n'y a pas de description, je l'ai mis dans la section "En bref".
