### ISSUE TITLE
[News GeoRDP] InfluxDB et capacités géos

### ISSUE THREAD

**Issue by bchartier** [geotribu/website#217]
# News

## Section cible

Un seul choix possible :

- [ ] Sorties de la semaine
- [ ] Client
- [x] Serveur
- [ ] Logiciel
- [ ] Représentation Cartographique
- [ ] OpenStreetMap
- [ ] Google
- [ ] Open Data
- [ ] Geo-event
- [ ] Divers
- [ ] En bref

----

## Titre
Package Geo dans la feuille de route d'InfluxDB

## Image de la vignette

- Texte de remplacement : InfluxDb logo
- Légende de l'image : InfluxDb logo
- URL : https://fr.wikipedia.org/wiki/InfluxDB#/media/Fichier:Influxdb_logo.svg

## Contenu

[InfluxDb](https://www.influxdata.com/products/influxdb-overview/) est un serveur de données conçu spécifiquement pour traiter des séries temporelles. Ce type de données concerne aussi bien les métriques d'une infrastructure informatique, l'évolution dans le temps d'indicateurs financiers, météorologiques ou climatiques, que des mesures fournies par des objets connectés (IoT).
L'un des composants d'InfluxDB est le langage de requête Flux. Il intègre des fonctions géographiques plutôt basiques (mais néanmoins adaptées aux besoin des utilisateurs de tels outils) via le [package Geo](https://docs.influxdata.com/influxdb/v2.0/query-data/flux/geo/) qui est marqué à l'heure actuelle comme expérimental. Ces fonctions sont basées sur un zonage multi-échelles du globe et se limitent à des calculs en longitude et latitude (impossible d'utiliser des coordonnées projetées). L'enrichissement des capacités géospatiales d'InfluxDB est l'une des orientations marquantes présentées cet été dans la feuille de route de l'outil (cf. vidéo dans les liens ci-dessous).

Quelques liens pour approfondir :
- Vidéo de présentation de la feuille de route d'InfluxDB (directement sur la séquence consacrée à la géolocalisation) : https://youtu.be/snLIFHmV5GU?t=1714- Article d'introduction au package Geo de Flux : https://www.influxdata.com/blog/exploring-geo-temporal-flux/
- Article d'introduction à l'utilisation de Geo : https://www.influxdata.com/blog/exploring-geo-temporal-flux/
- Guide d'utilisation du package Geo de Flux : https://docs.influxdata.com/influxdb/v2.0/query-data/flux/geo/
- Documentation de référence des fonctions du package Geo de Flux : https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/experimental/geo/

## Medias d'illustration (images, vidéos, tweets, etc.)

Présentations de résultats de requêtes géographiques dans des tableaux de bord (images extraites de la présentation de feuille de route de cet été) :
![Tim_Hall__InfluxData____InfluxDB_Roadmap_-_YouTube](https://user-images.githubusercontent.com/2361255/97797765-fed70380-1c1f-11eb-8423-8a5635481501.jpg)

![Tim_Hall__InfluxData____InfluxDB_Roadmap_-_YouTube](https://user-images.githubusercontent.com/2361255/97797778-1adaa500-1c20-11eb-98b6-3eeb53e66e93.jpg)

----

## Texte final à copier/coller

```markdown
## {{ news.section }}

### {{ news.title }}

![{{ news.thumbnail.replace_txt }}]({{ news.thumbnail.url }} "{{ news.thumbnail.caption }}"){: .img-rdp-news-thumb loading=lazy }

{{ news.body }}
```

**Comment by Guts** [comment]
Merci pour cette très belle news !
