### ISSUE TITLE
gh-pages branch history

### ISSUE THREAD

**Issue by fgravin** [geotribu/website#302]
Le clone initial est très lourd car chaque publication dans la branche `gh-pages` est historisée.
Cette branche est utilisée pour publier un snapshot statique du site web, idéalement elle ne devrait pas persister l'historique.

Je ne sais trop comment `mkdocs gh-deploy` fonctionne (je n'ai pas trouvé d'option pour gérer l'historique) mais si `mkdocs` peut exporter le site avant de la publier, vous pourriez utiliser par exemple le paquet npm [gh-pages](https://www.npmjs.com/package/gh-pages) qui fonctionne très bien et peut être utilisé dans une `gh-actions`.

Voici un exemple d'actions utilisant cet outil:
```yaml
- name: deploy to gh pages
  run: |
    echo "Deploying to directory: ${{env.BRANCH_NAME}}"
    git config --global user.name "github-actions[bot]"
    git config --global user.email "github-actions[bot]@users.noreply.github.com"
    npx gh-pages --dist dist/ --dest ${{env.BRANCH_NAME}} --remove "${{env.BRANCH_NAME}}/**" --no-history --repo "https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git"
```

`--no-history `: https://www.npmjs.com/package/gh-pages#optionshistory.

**Comment by Guts** [comment]
Intéressant, merci !

Je n'avais pas vu que c'était la branche gh-pages qui pesait aussi lourd.

En fait, mkdocs utilise [ghp-import](https://pypi.org/project/ghp-import/) sous le capot. Faut que je regarde s'il y a un équivalent à ce --no-history si pratique..

**Comment by Guts** [comment]
@fgravin au fait, peux-tu me dire si ça va mieux depuis ce changement ?

**Comment by fgravin** [comment]
Oui c'est le jour et la nuit.. quelques secondes pour le clone.
https://github.com/geotribu/website/tree/gh-pages ne contient plus qu'un commit donc ça marche bien, merci pour le fix.

**Comment by Guts** [comment]
ok cool. Alors ça marche bien mais pas à tous les coups. J'attends le retour de l'auteur de ghp-import (voir [ce ticket](https://github.com/c-w/ghp-import/issues/97)) mais j'ai l'impression que je passe à côté de quelque chose...

Si tu as une idée...

**Comment by fgravin** [comment]
Je n'ai pas regardé le code de `gh-import` mais
```
ghp-import: error: Failed to rebase gh-pages branch.
```
je dirais que ça ne devrait pas faire de `rebase` juste un `push --force`
