### ISSUE TITLE
[News GeoRDP]

### ISSUE THREAD

**Issue by omrane0** [geotribu/website#326]
# News

## Section cible

Un seul choix possible :

- [ ] Sorties de la semaine
- [ ] Client
- [ ] Serveur
- [ ] Logiciel
- [ ] Représentation Cartographique
- [ ] OpenStreetMap
- [x] Google
- [ ] Open Data
- [ ] Geo-event
- [ ] Divers
- [ ] En bref

----

## Titre

Le titre accrocheur de la news.
Longeur maximale indicative : 100/120 caractères

## Image de la vignette

- Texte de remplacement :
- Légende de l'image :
- URL :

## Contenu

Prose.

## Medias d'illustration (images, vidéos, tweets, etc.)

----

## Texte final à copier/coller

```markdown
## {{ news.section }}

### {{ news.title }}

![{{ news.thumbnail.replace_txt }}]({{ news.thumbnail.url }} "{{ news.thumbnail.caption }}"){: .img-rdp-news-thumb loading=lazy }

{{ news.body }}
```

**Comment by Guts** [comment]
Bonjour @omrane0 ,

Pensez-vous compléter votre contribution ou était-ce seulement un clic hasard :) ?

**Comment by igeofr** [comment]
Bonjour @omrane0,
En l'absence d'une réponse de votre part, nous allons clôturer l'issue.
