### ISSUE TITLE
[News GeoRDP] Chronique « Pépites libres » sur les données géographiques libres

### ISSUE THREAD

**Issue by apitux** [geotribu/website#327]
# News
### Chronique « _Pépites libres_ » sur les données géographiques libres

![logo Libre à vous](https://cdn.geotribu.fr/img/logos-icones/divers/libravous.png "logo Libre à vous"){: .img-rdp-news-thumb }

[Pépites libres](https://www.april.org/chronique-pepites-libres-de-jean-christophe-becquet) est la chronique de Jean-Christophe Becquet dans [Libre à vous](https://www.april.org/libre-a-vous), l'émission de l'[April](https://www.april.org) sur la radio [Cause Commune](https://cause-commune.fm/). Celle du mardi 23 mars était consacrée **aux données géographiques libres**. Il revient sur l'ouverture récente des données de l'IGN, les dynamiques autour d'OpenStreetMap et la recommandation du rapport Bothorel : « _engager la puissance publique sur la voie d’une participation plus active aux communs numériques_ ».

[Le podcast](https://apr1.org/Zb) et [la transcription](https://apr1.org/Zc) ainsi que toutes les références sont à présent disponibles sous licence libre [sur le site de l'April](https://www.april.org/chronique-pepites-libres-de-jean-christophe-becquet#Mardi_23_mars_2021_:_donnees_geographiques_libres_pour_les_territoires).

:headphones: Ecouter le podcast :

<audio
    controls
    src="https://media.april.org/audio/radio-cause-commune/libre-a-vous/emissions/20210323/libre-a-vous-20210323-chronique-jean-christophe-becquet-donnees-geographiques-libres.ogg">
    Your browser does not support the <code>audio</code> element.
</audio>

:eyeglasses: Ou lire [la transcription](https://www.librealire.org/emission-libre-a-vous-diffusee-mardi-23-mars-2021-sur-radio-cause-commune#Chronique-lt-lt-Pepites-libres-de-Jean-Christophe-Becquet-nbsp).

**Comment by Guts** [comment]
Merci @apitux d'avoir fait les 3/4 du chemin. J'ai fait ce qu'il restait : c'est dans la boîte !
