### ISSUE TITLE
[News GeoRDP] QasketBall, QSoccer, il va y avoir du sport dans QGIS !

### ISSUE THREAD

**Issue by benoitblanc** [geotribu/website#383]
# News

## Section cible

Un seul choix possible :

- [ ] Sorties de la semaine
- [ ] Client
- [ ] Serveur
- [ ] Logiciel
- [ ] Représentation Cartographique
- [ ] OpenStreetMap
- [ ] Google
- [ ] Open Data
- [ ] Geo-event
- [x] Divers
- [ ] En bref

----

## Image de la vignette

- Texte de remplacement : Logo de QSoccer
- Légende de l'image : Logo de QSoccer
- URL : [https://gitlab.com/Oslandia/qgis/QSoccer/-/blob/master/qsoccer/resources/images/qsoccer_logo_512px.svg](https://gitlab.com/Oslandia/qgis/QSoccer/-/blob/master/qsoccer/resources/images/qsoccer_logo_512px.svg)

## Contenu

Après la présentation de [QasketBall](https://www.youtube.com/watch?v=HlLlJz9sghk) :basketball:  lors du [QGIS Open Day](https://github.com/qgis/QGIS/wiki/QOD-June-2021) de juin 2021, Oslandia a sorti une première version d'un plugin permettant de voir des données de matchs de football dans QGIS : QSoccer :soccer: ! Cette première version permet de récupérer des données en Open Data mises à disposition par [StatsBomb](https://github.com/statsbomb/open-data), et de les afficher dans un widget en utilisant notamment les bibliothèques Open Source [kloppy](https://kloppy.pysport.org/) et [mplsoccer](https://mplsoccer.readthedocs.io/en/latest/). Pour plus de détails, vous pouvez consulter l'article [ici](https://oslandia.com/2021/06/25/qsoccer-qgis-football-what-else/).

Ces deux projets prouvent que même le sport a toute sa place dans les SIG !

## Medias d'illustration (images, vidéos, tweets, etc.)

![image](https://user-images.githubusercontent.com/8960009/124077446-d66e0600-da47-11eb-9daf-64d4a6b8ae2a.png)

![demo_qsoccer_qgis](https://user-images.githubusercontent.com/8960009/124078097-04534a80-da48-11eb-9844-206dd9314537.gif)

----

## Texte final à copier/coller

```markdown
## {{ news.section }}

### {{ news.title }}

![{{ news.thumbnail.replace_txt }}]({{ news.thumbnail.url }} "{{ news.thumbnail.caption }}"){: .img-rdp-news-thumb loading=lazy }

{{ news.body }}
```

**Comment by Guts** [comment]
Publiée https://static.geotribu.fr/rdp/2021/rdp_2021-07-02/#qasketball-qsoccer-il-va-y-avoir-du-sport-dans-qgis
