### ISSUE TITLE
[News GeoRDP] Un nouveau service de cartographie en ligne

### ISSUE THREAD

**Issue by claustres** [geotribu/website#423]
# News

## Section cible

Un seul choix possible :

- [x] Sorties de la semaine
- [ ] Client
- [ ] Serveur
- [ ] Logiciel
- [ ] Représentation Cartographique
- [ ] OpenStreetMap
- [ ] Google
- [ ] Open Data
- [ ] Geo-event
- [ ] Divers
- [ ] En bref

----

## Titre

My planet maps: un nouveau service de cartographie en ligne made in France !

## Image de la vignette

- Texte de remplacement : My Planet Maps
- Légende de l'image : My Planet Maps: mapping made easy
- URL : https://doc.myplanetmaps.com/myplanetmaps_logo_slogan_100.png

## Contenu

[My planet maps](https://planetobserver.com/myplanetmaps-online-map-service/) offre un accès en streaming simple et rapide à des contenus cartographiques mondiaux de qualité, mis à jour régulièrement. Les cartes proposées englobent une mosaïque mondiale d’imagerie satellite de résolution 10 mètres, des orthophotographies de la France de résolution 50 cm et 20 cm et des cartes OpenStreetMap disponibles dans différents styles.

La mosaïque d’imagerie mondiale, produite par [PlanetObserver](https://planetobserver.com/), est au cœur de l’expérience My Planet Maps. Les données cartographiques sont accessibles via des web services aux standards OGC (WMS, WMTS, TMS) sur la plateforme opérée par [Kalisio](https://kalisio.com/).

## Medias d'illustration (images, vidéos, tweets, etc.)

https://doc.myplanetmaps.com/assets/img/imagery-1.2a2f551d.jpg
https://doc.myplanetmaps.com/assets/img/hybrid-3.0a30ffdd.jpg
https://doc.myplanetmaps.com/assets/img/plan-bright-3.2669f1ce.png

----

## Texte final à copier/coller

```markdown
## {{ news.section }}

### {{ news.title }}

![{{ news.thumbnail.replace_txt }}]({{ news.thumbnail.url }} "{{ news.thumbnail.caption }}"){: .img-rdp-news-thumb loading=lazy }

{{ news.body }}
```

**Comment by Guts** [comment]
Merci @claustres pour la contirbution. Pour être sûr : es-tu lié à Planet Maps ?

**Comment by claustres** [comment]
Bonjour, oui tout à fait je fait partie de la société qui opère la plateforme, désolé si la contribution doit venir d'une personne extérieure au projet je n'avais pas vu cette contrainte.

**Comment by Guts** [comment]
S'ils ont choisi Kalisio, c'est un bon choix :wink: !

Je vois en interne mais peut-être qu'on va ajouter un disclaimer.  
Sinon, ça peut se faire en proposant un article présentant la plateforme avec tuto de prise en main et aspects techniques, etc. Si ça vous intéresse, envoie-nous un mail : geotribu chez gmail

**Comment by Guts** [comment]
@claustres peux-tu fournir un logo carré stp ?

**Comment by claustres** [comment]
En voici un en suivant [ce lien](https://drive.google.com/file/d/1MwBSbgcgplbgFu8eanRUyjUZG9AcpiZ3/view?usp=sharing)

**Comment by Guts** [comment]
@claustres la plateforme ou les outils sous-jacents sont-ils open source ou du moins contribuent-ils à une dynamique d'ouverture des données ou autre ?

**Comment by claustres** [comment]
Oui tout à fait, le traitement des données et la plateforme sont entièrement basées sur des outils Open Source, quelques information à ce sujet [ici](https://kalisio.com/blog/11-divers/93-fonds-cartographiques-bases-sur-les-donnees-openstreetmap), nous détaillerons cela dans l'article que nous proposons d'écrire en complément pour GéoTribu.

**Comment by Guts** [comment]
@claustres ok cool. Peux-tu reformuler un peu pour que la news fasse moins communiqué de presse et entre plus dans le détail technique ?

**Comment by claustres** [comment]
Voici un nouveau contenu en espérant qu'il conviendra:

[My planet maps](https://planetobserver.com/myplanetmaps-online-map-service/) offre un accès en streaming simple et rapide à des contenus cartographiques mondiaux de qualité, mis à jour régulièrement. Les cartes proposées englobent une mosaïque mondiale d’imagerie satellite de résolution 10 mètres (produite par [PlanetObserver](https://planetobserver.com/)), des orthophotographies de résolution centimétrique (produites par l'IGN) et des données vectorielles OpenStreetMap disponibles dans différents styles (produites par [Kalisio](https://kalisio.com/)).

Les données cartographiques sont accessibles via des web services selon les standards OGC (WMS, WMTS, TMS) sur une plateforme propulsée par un écosystème Open Source:
* [OpenMapTiles](https://github.com/openmaptiles) pour l'import de la base de données OpenStreetMap et la génération des tuiles vectorielles,
* [Tippecanoe](https://github.com/mapbox/tippecanoe) pour l'aggrégation des tuiles vectorielles,
* [Krawler](https://kalisio.github.io/krawler/) pour l'orchestration des tâches de traitement des données,
* [Kaabah](https://kalisio.github.io/kaabah/) pour le déploiement automatisé d'infrastructures de traitement et de services,
* [Kargo](https://kalisio.github.io/kargo/) pour la mise à disposition des tuiles via les différents protocoles,
* [Kano](https://kalisio.github.io/kano/) comme client de visualisation des données.

**Comment by claustres** [comment]
Un simple complément: "Les données cartographiques **sont hébergées en France et** accessibles via des web services..."

Peut-on rajouter une illustration parmi les screenshots proposés ? Merci

**Comment by Guts** [comment]
Oui bon si c'est juste pour un élément de langage, je te laisse faire une PR, je n'aurai pas le temps aujourd'hui.

Quant à l'illustration, tu parles des fonds de plan ? Du coup, j'ai pas trouvé ça assez représentatif de la plate-forme donc j'ai pas pris. Peut-être une capture de l'interface côté utilisateur authentifié ? Ou autre ?

**Comment by robinbourianes-kalisio** [comment]
Bonjour, j'ai fait la modif dans une PR ici: https://github.com/geotribu/website/pull/427
J'y ai ajouté un lien vers une illustration qui irait peut être mieux, il s'agit de Kano, la webapp qu'on développe et qui nous sert de démonstrateur pour les fonds carto sur la plateforme.

Merci.
