### ISSUE TITLE
Homogénéisation et assainissement des contenus anciens

### ISSUE THREAD

**Issue by Guts** [geotribu/website#443]
## Contexte

Dans la foulée du nettoyage des en-têtes (voir https://github.com/geotribu/website/pull/425) dont le résultat le plus visible est le système des mots-clés, il est temps de se pencher sur le nettoyage et l'homogénéisation des contenus anciens, càd principalement avant l'opération géo-phénix du printemps 2020, dont le scraping ne pouvait résoudre tous les soucis.

:speech_balloon: sujet discuté sur le Slack de l'équipe : https://geotribu.slack.com/archives/CU9Q1B1FT/p1634317481021500

## Objectifs et gains attendus

- impression de qualité avec un rendu propre et homogène
- correction des erreurs dans la recherche du site
- possibilité d'effectuer des analyses sur l'ensemble des contenus : nuages de mots-clés, comparaison entre les mots-clés spécifiés et mots-clés mentionnés dans le corps du contenu, frises chronologiques, mécanismes pour proposer un "lire aussi.../sur le même sujet", etc.
- amélioration des performances dans la navigation (balises d'images, etc.)
- meilleure réversibilité de l'outil de génération du site (si on veut changer pour hugo ou autre)
- traitements par lots facilités
- meilleur référencement SEO

----

### Anciennes URLs d'images

Dans les anciens contenus, on trouve parfois des URLs structurées comme pour le gestionnaire de médias de Drupal qui du coup pointent vers des 404 sur le CDN actuel.

:dart: trouver l'équivalence de l'image dans le CDN actuel et rechercher/remplacer les images.

Exemples :

- [source](https://github.com/geotribu/website/blob/master/content/rdp/2011/rdp_2011-12-23.md?plain=1#L25) : `https://static.geotribu.fr/sites/default/files/Tuto/img/Blog/world_noel.png` par `https://cdn.geotribu.fr/img/internal/icons-rdp-news/noel.png`
- [source](https://github.com/geotribu/website/blob/master/content/rdp/2011/rdp_2011-12-23.md?plain=1#L39) : `http://geotribu.net/sites/default/files/Tuto/img/divers/logo-gvsig_150_14.gif` par `https://cdn.geotribu.fr/img/logos-icones/logiciels_librairies/gvsig.png`

### Balises d'accessibilité manquantes

A l'époque, tout le monde s'en foutait de [l'accessibilité du web](https://fr.wikipedia.org/wiki/Accessibilit%C3%A9_du_web) et l'outillage n'était pas au niveau.  Désormais, l'outillage est là et c'est un sujet important en phase avec les valeurs de la Geotribu (enfin je pense).

:dart: ajouter un texte de remplacement et une description à toutes les images (au moins les récurrentes)

Exemples :

```markdown
![OpenLayers.png](https://cdn.geotribu.fr/img/logos-icones/logiciels_librairies/openlayers.png) 
```
devient :

```markdown
![logo OpenLayers](https://cdn.geotribu.fr/img/logos-icones/logiciels_librairies/openlayers.png "logo OpenLayers") 
```

### Retraits superficiels en début de ligne

C'est ballot vu que la syntaxe Markdown tient compte de l'indentation.

Exemples :

```markdown
 Utilisateur de QGIS ou simple curieux de l'Open Source 
```
devient après suppression de l'espace en début de ligne :

```markdown
Utilisateur de QGIS ou simple curieux de l'Open Source 
```

### Paragraphes mal formatés

:dart: globalement, appliquer la structure actuelle. Plusieurs choses à faire par exemple pour une news de RDP :

- déplacer la ligne de l'icône sous le titre de niveau 3

Exemples :

```markdown
 **GeoIpsum**

![globe news](https://cdn.geotribu.fr/img/internal/icons-rdp-news/world.png){: .img-rdp-news-thumb } Il m'arrive tr
```
devient :

```markdown
### GeoIpsum

![icône news générique](https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png "News Geotribu"){: .img-rdp-news-thumb }

Il m'arrive tr
```

### Ajouter les balises CSS aux vignettes

Cf. https://static.geotribu.fr/contribuer/guides/image/#vignette

### Retirer les anciennes ancres `#news`

Dans les intros ds anciennes RDP notamment, on trouve beaucoup d'ancres comme celles-ci : `[librairie Google Vector Layer](#news11)` ([source](https://github.com/geotribu/website/blob/master/content/rdp/2011/rdp_2011-12-23.md?plain=1#L25))

Il s'agit de retirer ces liens puisque il y a une table des matières automatiquement à droite des contenus.

### Corriger les niveaux de titre

Parfois, les niveaux de titres ont été mal encodés lors de la récupération des contenus, notamment parce-que les premières RDP ne respectaient pas correctement le HTML ou que les titres étaient de simples balises gras.
Du coup, on retrouve parfois des noms de sections en titre 3 ou 4 au lieu du niveau 2.

```markdown
#### Open Data
```

Doit devenir :

```markdown
## Open Data
```

### Homogénéiser les images (en particulier les vignettes)

Selon les moments, un même logo peut être nommé de différentes façons. Au passage du nettoyage, il est intéressant d'en profiter pour homogénéiser. Exemple avec le logo OSM :

```markdown
![logo OpenStreetMap](https://cdn.geotribu.fr/img/logos-icones/OpenStreetMap/Openstreetmap.png "logo OSM"){: .img-rdp-news-thumb }

![logo OpenStreetMap](https://cdn.geotribu.fr/img/logos-icones/OpenStreetMap/Openstreetmap.png "logo OSM"){: .img-rdp-news-thumb }
```

On choisit celui qui est le plus cohérent avec les tags et le reste de la rédaction.

---

## Méthodologie

- Manuellement ou automatiquement (sed, scripts, etc.) même si ça me semble vraiment compliqué de tout résoudre vu l'hétérogénéité. Pour un script, se créer une branche dédiée pour travailler tranquillement sans impacter le travail collectif et proposer une PR.
- se répartir par années et type de contenu (article ou RDP), mais il est possible de faire des changements transversaux, par exemple pour faire des chercher/remplacer sur les URLs des images.
- une branche et sa PR pour centraliser les corrections
- éviter si possible de commiter contenu par contenu via l'interface pour ne pas déclencher la CI ouate 1000 fois

----

## Répartition du travail

:information_source: éditer la description pour ajouter le pseudo du responsable de chaque année

### RDP

| Année | URLs d'images | Balises d'accessibilité | Retraits superficiels | Paragraphes  | Relecture |
| :--------------- |:---------------:|:---------------:|:---------------:|:---------------:|:---------------:|  
| 2010 | @igeofr | @igeofr | @igeofr | @igeofr | |
| 2011 | | | | | |
| 2012 |   | |   |   | |
| 2013 |  @Guts |  @Guts |  @Guts | @Guts | |
| 2014 | @igeofr | @igeofr | @igeofr | @igeofr | @aurelienchaumet |
| 2015 | @igeofr | @igeofr | @igeofr | @igeofr | |
| 2016 | @igeofr | @igeofr | @igeofr | @igeofr | |
| 2017 | @igeofr | @igeofr | @igeofr | @igeofr | |

### Articles

| Année | URLs d'images | Balises d'accessibilité | Retraits superficiels | Paragraphes  |
| :--------------- |:---------------:|:---------------:|:---------------:|:---------------:| 
| 2008 | @igeofr | @igeofr | @igeofr | @igeofr |
| 2009 | @igeofr | @igeofr | @igeofr | @igeofr |
| 2010 |  |  |  |  |
| 2011 |  |  |  |  |
| 2012 |  |  |  |  |
| 2013 |  |  |  |  |
| 2014 |  |  |  |  |
| 2015 |  |  |  |  |
| 2016 |  |  |  |  |
| 2017 |  |  |  |  |

---
## Penser à faire par la suite

- Ajouter des '14h20' dans l'en-tête lorsque `date` ne contient que du yyyy-mm-dd

---

### On supprime les images extérieures qui n'existent plus ?

Non car tu peux pas savoir si l'image est temporairement ou définitivement inaccessible. Ajouter des textes de remplacement puisque ils sont justement fait pour ça :wink:.

**Comment by datagistips** [comment]
Je viens de voir cette PR

Les cas de paragraphes mal formatés sont plus nombreux. En voici 5 différents constatés sur 2011 :

```
### L'Open Data en image** lorem ipsum
## L'Open Data en image** lorem ipsum
L'Open Data en image** lorem ipsum
 **OpenLayers Mobile**  lorem ipsum
![logo-gvsig_150_14.gif](http://geotribu.net/sites/default/files/Tuto/img/divers/logo-gvsig_150_14.gif)**gvSIG** lorem ipsum
```

Me dire si ok pour 2011, voir https://github.com/geotribu/website/tree/fenfyx2/content/rdp/2011

https://github.com/geotribu/website/blob/fenfyx2/content/rdp/2011/rdp_2011-01-21.md devient https://github.com/geotribu/website/blob/fenfyx2/content/rdp/2011/rdp_2011-01-21-new.md

Log : https://github.com/geotribu/website/blob/fenfyx2/content/rdp/rdp_2011-01-21-log.md

A faire : vérifier si rdp de 2011 ok
Prochaines tâches de mon côté : liens morts, niveaux de titres,...

**Comment by datagistips** [comment]
Petit état des lieux :
- [x] Paragraphes mal formatés
- [x] Retraits superficiels

Pour les retraits, voir [cette version sur fenfyx2](https://raw.githubusercontent.com/geotribu/website/fenfy2/content/rdp/2011/rdp_2011-12-30.md) par rapport à [celle sur master](https://raw.githubusercontent.com/geotribu/website/master/content/rdp/2011/rdp_2011-12-30.md)
