### ISSUE TITLE
Télédétection et environnement : Ruth DeFries rejoint Wikipédia

### ISSUE THREAD

**Issue by KazeNoOni** [geotribu/website#488]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui
- [ ] Non

### Votre nom

D.MONTAGNE

### Votre adresse email

delphine.montagne@univ-pau.fr

### Licence

- [X] J'accepte

### Section / catégorie

Divers

### Mots-clés

wikipédia, télédétection, environnement, communs, genre

### Titre de la news

Télédétection et environnement : Ruth DeFries rejoint Wikipédia

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/journalisme.png

### Contenu de la news

```markdown
La télédétection offre de riches possibilités, dont celle d'étudier tout ce qui rend la planète habitable : les processus biophysiques, la biodiversité et les services écosystémiques, la transformation du paysage et ses conséquences sur le climat... Et c'est justement l'objet des travaux de Ruth DeFries qui a rejoint Wikipédia en français. L'occasion de (re)découvrir la méthode qu'elle a développé pour estimer la déforestation : https://fr.wikipedia.org/wiki/Ruth_DeFries
```

### Message libre

```markdown
Auto-promo puisque je suis à l'origine de la traduction de la biographie sur Wikipédia.
```

**Comment by Guts** [comment]
Bonjour @KazeNoOni ,

Merci. Nous l'avons intégrée dans la RDP de vendredi dont voici la prévisualisation https://preview-pullrequest-487--geotribu-preprod.netlify.app/rdp/2021/rdp_2021-12-24/#teledetection-et-environnement-ruth-defries-rejoint-wikipedia
