### ISSUE TITLE
Début d'année cartographique et nordique : Gerd Enequist sur Wikipédia

### ISSUE THREAD

**Issue by KazeNoOni** [geotribu/website#496]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui
- [ ] Non

### Votre nom

D.MONTAGNE

### Votre adresse email

delphine.montagne@univ-pau.fr

### Licence

- [X] J'accepte

### Section / catégorie

Divers

### Mots-clés

wikipédia, cartographie, diagramme, communs, genre

### Titre de la news

Début d'année cartographique et nordique : Gerd Enequist sur Wikipédia

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/journalisme.png

### Contenu de la news

En ce début d'année 2021, retour du grand nord avec un passage par la Suède pour découvrir la géographe et cartographe Gerd Enequist. On lui doit de nombreuses cartes du premier Atlas de la Suède, le premier diagramme triangulaire appliqué à la cartographie et de nombreses études sur l'urbanisme ou les statistiques suédoises. Elle vient de rejoindre Wikipédia en français et l'ensemble de ses travaux, ainsi que son parcours pionnier sont à découvrir sur sa page : https://fr.wikipedia.org/wiki/Gerd_Enequist.

### Message libre

Auto-promo puisque je suis à l'origine de la traduction de la biographie sur Wikipédia. Merci beaucoup pour votre très gentil message de la dernière fois !

**Comment by Guts** [comment]
Merci @KazeNoOni pour cette nouvelle contribution. Je viens de l'ajouter à la prochaine RDP prévisualisable ici : https://preview-pullrequest-499--geotribu-preprod.netlify.app/rdp/2022/rdp_2022-01-07/#debut-dannee-cartographique-et-nordique-gerd-enequist-sur-wikipedia

Je me suis permis de corriger 2 petites coquilles, notamment l'année :wink: ! 
A noter que les pages Geotribu concernant Wikipédia sont regroupées sur la page des mots-clés : https://static.geotribu.fr/tags/#wikipedia.

Bonnes fêtes de fin d'année :champagne: !
