### ISSUE TITLE
Découvrir OpenStreetMap autrement : premier stream sur Tropicamap

### ISSUE THREAD

**Issue by KazeNoOni** [geotribu/website#497]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui
- [X] Non

### Votre nom

D.Montagne

### Votre adresse email

delphine.montagne@univ-pau.fr

### Licence

- [X] J'accepte

### Section / catégorie

OpenStreetMap

### Mots-clés

OpenStreetMap, communs

### Titre de la news

Découvrir OpenStreetMap autrement : premier stream sur Tropicamap

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

OpenStreetMap vous semble un monde à part, rempli de mots compliqués et d'applications obscures ? Il vous semble passionnant mais trop touffu ? Et pourtant vous avez envie de le (re)découvrir ? Adrien, Donat et Florian d'OpenStreetMap France proposent un nouveau rendez-vous régulier sur leur chaîne YouTube Tropicamap. Au menu tous les mois, de la contribution sur OSM, de la veille cartographique et surtout, de la découverte pas à pas de cet incroyable commun : https://www.youtube.com/watch?v=djET4aTtcJ4

### Message libre

Par transparence on fait partie de la même association mais je n'ai pas participé à la création de l'émission (je n'étais pas au courant).

**Comment by Guts** [comment]
Merci @KazeNoOni pour cette nouvelle contribution. Je viens de l'ajouter à la prochaine RDP prévisualisable ici : https://preview-pullrequest-499--geotribu-preprod.netlify.app/rdp/2022/rdp_2022-01-07/#decouvrir-openstreetmap-autrement-premier-stream-sur-tropicamap

Je me suis permis de l'augmenter un petit peu avec notamment des liens supplémentaires et une citation des auteurs de la chaîne. En espérant ne pas avoir dénaturé votre propos.
