### ISSUE TITLE
Cartographie extra-terrestre : Kira Shingareva sur Wikipédia

### ISSUE THREAD

**Issue by KazeNoOni** [geotribu/website#508]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui
- [ ] Non

### Votre nom

D.Montagne

### Votre adresse email

delphine.montagne@univ-pau.fr

### Licence

- [X] J'accepte

### Section / catégorie

Divers

### Mots-clés

wikipédia, commun, Lune, espace

### Titre de la news

Cartographie extra-terrestre : Kira Shingareva sur Wikipédia

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

Cette semaine c'était la première pleine Lune de l'année : si vous avez admiré le ciel, ou au contraire mal dormi et que vous êtes une personne passionnée de cartographie, savez-vous qui a été à l'origine de la première cartographie complète (quasi-complète) de la face cachée de la Lune ? Il s'agit de Kira Shingareva, géographe extra-terrestre russe, a qui l'on doit aussi des cartographies de Phobos, Deimos ou des planètes Mars, Mercure ou Vénus. Elle participe également au groupe de toponymie extraterrestre et à la rédaction d'un ouvrage dont le nom laisse rêveur : _Atlas des planètes terrestres et de leurs lunes_ (en russe : _Атлас планет Земной группы и их спутников_).
Kira Shingareva fait son entrée sur Wikipédia et avec elle l'occasion de voyager grâce aux cartes dans tout le système solaire : https://fr.wikipedia.org/wiki/Kira_Shingareva
![MoonTopoGeoidUSGS-fr](https://user-images.githubusercontent.com/17273438/148610364-bcfa5753-21dd-40b9-801b-29e55a97ef93.jpg)

### Message libre

J'ai créé cette page WP, donc autopromotion.

**Comment by KazeNoOni** [comment]
Bonjour, Je crois que le lien URL n'est pas passé dans la visualisation... Et désolée, je vais devoir vous faire un petit changer le template : il ne s'agit pas d'une traduction cette fois-ci, mais d'un travail inédit, une création (un scandale, je vous l'accorde). KS n'existe dans aucune autre langue que le français.

**Comment by Guts** [comment]
Corrigé à l'instant.
