### ISSUE TITLE
Retour historique sur la cartographie de l'Amazone

### ISSUE THREAD

**Issue by KazeNoOni** [geotribu/website#517]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui
- [X] Non

### Votre nom

D.Montagne

### Votre adresse email

delphine.montagne@univ-pau.fr

### Licence

- [X] J'accepte

### Section / catégorie

Représentation Cartographique

### Mots-clés

Gallica, BNF, carte

### Titre de la news

Retour historique sur la cartographie de l'Amazone

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

Comment a évolué [la cartographie et notre vision de l'Amazone](https://gallica.bnf.fr/blog/12012022/entre-faits-et-legendes-la-cartographie-du-fleuve-amazone-du-xvie-au-xviiie-siecle) ? Gallica propose un passionnant retour, en cartes, sur ces représentations et les explorations occidentales qui s'y sont déroulées.
![image](https://user-images.githubusercontent.com/17273438/150218863-adb64b23-b1d5-44d5-840f-8c60da8202e4.png)

A noter si le sujet des cartes anciennes vous intéressent, [ces capsules vidéos de la BNF](https://www.youtube.com/playlist?list=PL-GL80g2OlE3HeD0u3CB80NKwP-CGrcjL), denses mais riches, sur quelques unes des plus connues de leurs collections.

**Comment by igeofr** [comment]
https://github.com/geotribu/website/pull/506/commits/29cdda266219cce47ac082391262dbd91d5053ef
