### ISSUE TITLE
OpenStreetMap sur Tropicamap

### ISSUE THREAD

**Issue by KazeNoOni** [geotribu/website#530]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui
- [X] Non

### Votre nom

Montagne

### Votre adresse email

delphine.montagne@univ-pau.fr

### Licence

- [X] J'accepte

### Section / catégorie

Divers

### Mots-clés

commun, OpenStreetMap, pic4review

### Titre de la news

Comment contribuer sur OpenStreetMap avec Pic4Review ?

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

Chaque mois, la chaîne YouTube Tropicamap propose de la contribution collective sur OpenSteetMap. Pour le mois de février, le live propose de découvrir [Pic4Review, un outil de contribution libre](https://www.youtube.com/watch?v=LDxPXAZWFFg) qui s'appuie sur des photos sous licence libre. Avec en bonus la présence de l'équipe de création !

### Message libre

Par transparence, adhérente d'OSM France.

**Comment by Guts** [comment]
Bonjour Delphine,

Merci pour la proposition.

> Avec en bonus la présence de l'équipe de création !

Je suis un peu surpris de la formulation puis pic4review = Adrien Pavie = un des 3 membres de Tropicamap. Donc on est plus sur de l'autopromo ou de la promo croisée entre projets de mêmes auteurs qu'une vraie découverte. Ou alors c'est juste la formulation manque un peu de transparence.

Ceci dit, le projet est sympa et propre (comme souvent avec Adien Pavie) donc on peut toujours le relayer en brève.

**Comment by Guts** [comment]
Bon j'ai publié quand même, avec une petite reformulation : https://preview-pullrequest-518--geotribu-preprod.netlify.app/rdp/2022/rdp_2022-02-04/#pic4review-au-menu-de-tropicamap
