### ISSUE TITLE
Webinaire geOrchestra le jeudi 10/03/2022

### ISSUE THREAD

**Issue by MaelREBOUX** [geotribu/website#534]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui
- [ ] Non

### Votre nom

Maël REBOUX

### Votre adresse email

mael.reboux@georchestra.org

### Licence

- [X] J'accepte

### Section / catégorie

Geo-event

### Mots-clés

geOrchestra,mapstore

### Titre de la news

Webinaire mapstore2 le jeudi 10/03/2022

### Icône de la news

https://cdn.geotribu.fr/img/logos-icones/logiciels_librairies/georchestra.png

### Contenu de la news

Le prochain webinaire de la communauté [geOrchestra](url) sera consacré à Mapstore et aura lieu le jeudi 10/03/2022 de 15h00 à 17h00, sur notre [chaîne Youtube](https://www.youtube.com/channel/UC5GMhd360QgNhfN5D0wyWAg).

Nous aborderons plus ou moins en détail les corrections, nouveautés et apports des différentes versions publiées depuis septembre 2021.
Un temps sera consacré à la méthodologie pour migrer depuis mapfishapp vers mapstore, en appui d'un ou deux cas d'usage.

**Comment by Guts** [comment]
Merci @MaelREBOUX.
Par contre, le lien vers le webinaire est vide.

**Comment by Guts** [comment]
Du coup, j'ai pris la liberté de mettre ce lien https://www.georchestra.org/fr/communaute.html. Si tu veux changer, c'est évidemment possible.
