### ISSUE TITLE
Données géographiques et logiciels libres outre-Rhin

### ISSUE THREAD

**Issue by PatGendre** [geotribu/website#561]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui
- [ ] Non

### Votre nom

Patrick Gendre

### Votre adresse email

patgendre94@gmail.com

### Licence

- [X] J'accepte

### Section / catégorie

Divers

### Mots-clés

Europe, OSM, open source

### Titre de la news

Données géographiques, OSM et logiciels libres outre-Rhin

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

La dernière conférence [FOSS-GIS](https://fossgis-konferenz.de/2022/programm/) sur les SIG open source à Marburg en Allemagne montre le dynamisme et les compétences de la communauté géomatique outre-Rhin, y compris autour d'OpenStreetMap. Le site de la conférence est en allemand mais avec les outils de traduction automatique on peut trouver des idées ou des outils intéressants à regarder de plus près. Assez peu de présentations sont encore en ligne, il y a quelques vidéos (auf Deutsch bien sûr), mais quand on s'intéresse à un outil en particulier on peut assez facilement le retrouver en ligne, bien souvent documenté en anglais s'il est open source.

### Message libre

J'ai rédigé une petite page avec quelques résumés de présentations qui m'ont intéressé :
https://infomobi.bee.wf/blog/donnees-geographiques-et-logiciels-libres-outre-rhin
Vous pouvez citer la page ou reprendre tout ou partie de son contenu peu importe, je vous fais confiance :-)
Merci !

**Comment by Guts** [comment]
Publiée ici https://static.geotribu.fr/rdp/2022/rdp_2022-03-18/#donnees-geographiques-osm-et-logiciels-libres-outre-rhin

**Comment by PatGendre** [comment]
Merci 👍👍
