### ISSUE TITLE
Vidéo de vulgarisation en géodésie

### ISSUE THREAD

**Issue by KazeNoOni** [geotribu/website#570]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui
- [X] Non

### Votre nom

Montagne

### Votre adresse email

delphine.montagne@univ-pau.fr

### Licence

- [X] J'accepte

### Section / catégorie

Divers

### Mots-clés

géodésie, vulgarisation,YouTube

### Titre de la news

Géodésie décalée sur YouTube

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

Valentine tient une chaîne de vulgarisation sur la géologie, Science de Comptoir (SdC pour les intimes). Or les cailloux, ce n'est pas le sujet le plus évident à traiter. Mais Valentine est incapable de faire une vidéo sans une blague par minute. Avec parfois des rafales d'une par seconde... Si l'on arrive à suivre son humour décalé. Vous n'avez jamais rien compris à la géodésie ? Au géoïde ? Aux controverses sur la forme de la Terre ? A la gravimétrie ? C'est le moment d'aller l'écouter :
https://www.youtube.com/watch?v=Y75kkQrGUAw

**Comment by Guts** [comment]
Bonsoir @KazeNoOni ,

Merci pour ta proposition de news. Elle est intégrée. Voici la preview : https://preview-pullrequest-565--geotribu-preprod.netlify.app/rdp/2022/rdp_2022-04-01/#geodesie-decalee-sur-youtube

**Comment by Guts** [comment]
Publiée : https://static.geotribu.fr/rdp/2022/rdp_2022-04-01/#geodesie-decalee-sur-youtube
