### ISSUE TITLE
geOcom 2022 : le programme

### ISSUE THREAD

**Issue by MaelREBOUX** [geotribu/website#572]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui
- [ ] Non

### Votre nom

Maël REBOUX

### Votre adresse email

mael.reboux@georchestra.org

### Licence

- [X] J'accepte

### Section / catégorie

Geo-event

### Mots-clés

geOrchestra

### Titre de la news

geOcom 2022 : le programme

### Icône de la news

https://cdn.geotribu.fr/img/logos-icones/logiciels_librairies/georchestra.png

### Contenu de la news

Le programme du prochain geOcom 2022 (les rencontres de la communauté geOrchestra) est sorti ! Il est consultable et téléchargeable [en cliquant ici](https://www.georchestra.org/blog/2022/03/10/geocom-2022-fr/).

Un fort beau programme qui permettra grâce à la variété des intervenants et des participants de croiser les regards sur l'actualité du cœur logiciel mais pas seulement car les usages sont omniprésents dans les échanges. 
Au menu :
- Les tendances numériques à surveiller
- Comment mieux faire entrer les données ?
- Comment démultiplier l’usage des données ?
- Les évolutions structurantes de geOrchestra
- Quelles opportunités technologiques ? 
- Les axes de développement

Inscriptions sur la page du programme.

**Comment by Guts** [comment]
Bonsoir @MaelREBOUX ,

Merci pour ta proposition de contribution. La voici dans la preview : https://preview-pullrequest-565--geotribu-preprod.netlify.app/rdp/2022/rdp_2022-04-01/#geocom-2022-le-programme

**Comment by Guts** [comment]
Publiée : https://static.geotribu.fr/rdp/2022/rdp_2022-04-01/#geocom-2022-le-programme
