### ISSUE TITLE
La géomatique dans Ma thèse en 180 secondes

### ISSUE THREAD

**Issue by KazeNoOni** [geotribu/website#587]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui
- [X] Non

### Votre nom

Delphine MONTAGNE

### Votre adresse email

delphine.montagne@univ-pau.fr

### Licence

- [X] J'accepte

### Section / catégorie

Divers

### Mots-clés

vulgarisation, lidar, SIG

### Titre de la news

La géomatique à l'honneur du concours Ma thèse en 180 secondes

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

Le concours "Ma thèse en 180 secondes" (MT180 pour les intimes) vise à présenter et apprendre à vulgariser son sujet de thèse auprès du grand public en 3mn. Et pas une seconde de plus, c'est dans le titre ! Oser s'exprimer devant un large public, poser sa voix, apprendre à occuper une estrade, parvenir à expliquer sans dénaturer son sujet scientifique, le défi n'est pas facile !

Cette année, Julien Berthe, doctorant à l'Université de Reims Champagne-Ardenne, a été sélectionné pour la finale nationale. Son sujet ? La morphologie et les paysages de la Montagne de Reim. Le grand public (re)découvrira les apports du Lidar et de la géomatique dans ce type de thématique de recherche (en 180 secondes, donc).

Bonne chance à Julien Berthe et n'hésitez pas à aller l'encourager le 31 mai à la Bourse du travail de Lyon si vous êtes dans le secteur !
https://www.youtube.com/watch?v=kAj70hbwwcI

### Message libre

Peut-être à publier le 27 mai ?

**Comment by Guts** [comment]
Merci @KazeNoOni pour la news.

> Peut-être à publier le 27 mai ?

A vous de nous dire :)

## Préparation automatique de la contribution

### En-tête

```yaml
tags:
    - vulgarisation
    - LiDAR
    - SIG
```

### News

```markdown
### La géomatique à l'honneur du concours Ma thèse en 180 secondes

Le concours "Ma thèse en 180 secondes" (MT180 pour les intimes) vise à présenter et apprendre à vulgariser son sujet de thèse auprès du grand public en 3mn. Et pas une seconde de plus, c'est dans le titre ! Oser s'exprimer devant un large public, poser sa voix, apprendre à occuper une estrade, parvenir à expliquer sans dénaturer son sujet scientifique, le défi n'est pas facile !

Cette année, Julien Berthe, doctorant à l'Université de Reims Champagne-Ardenne, a été sélectionné pour la finale nationale. Son sujet ? La morphologie et les paysages de la Montagne de Reim. Le grand public (re)découvrira les apports du Lidar et de la géomatique dans ce type de thématique de recherche (en 180 secondes, donc).

Bonne chance à Julien Berthe et n'hésitez pas à aller l'encourager le 31 mai à la Bourse du travail de Lyon si vous êtes dans le secteur !

<iframe width="100%" height="400" src="https://www.youtube-nocookie.com/embed/kAj70hbwwcI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

!!! info "Contribution externe"
    Cette news est proposée par Delphine MONTAGNE via le [formulaire GitHub](https://github.com/geotribu/website/issues/new?assignees=Guts&labels=contribution+externe%2Crdp%2Ctriage&template=RDP_NEWS.yml) - [voir le ticket](https://github.com/geotribu/website/issues/587). Merci !
```

Commande git à utiliser :

```bash
git commit --author="Delphine MONTAGNE <delphine.montagne@univ-pau.fr>"
```

**Comment by Guts** [comment]
News ajoutée.Voici la prévisualisation : https://preview-pullrequest-586--geotribu-preprod.netlify.app/rdp/2022/rdp_2022-04-29/#la-geomatique-a-lhonneur-du-concours-ma-these-en-180-secondes
