### ISSUE TITLE
Journée Pro OPenIG : Géomatique, I.A et Changement Climatique, c'est le 24 mai à Carcassonne :european_castle:

### ISSUE THREAD

**Issue by ghost** [geotribu/website#594]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui
- [ ] Non

### Votre nom

Gabriel Poujol

### Votre adresse email

gpoujol@openig.org

### Licence

- [X] J'accepte

### Section / catégorie

Geo-event

### Mots-clés

OPenIG, Intelligence_Artificielle, Changement_Climatique, IA, CC 

### Titre de la news

Journée Pro OPenIG : Géomatique, I.A et Changement Climatique, c'est le 24 mai à Carcassonne :european_castle:

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

Le 24 mai 2022, aux abords de la cité médiévale de Carcassonne, [OPenIG](https://www.openig.org/) organise sa Journée Professionnelle (*) annuelle sur le thème des liens entre géomatique et IA, en présentiel. 

*Comment la géomatique de demain se propose de conjuguer intelligence artificielle et changement climatique ? Comprendre, lutter et s'adapter au changement climatique : en quoi l’intelligence artificielle offre de nouveaux outils aux géomaticiens ?*

On y abordera entre autres : IA et information géographique, enjeux éthiques, applications pour évaluer les ressources en eau ou estimer le « **Z**éro **A**rtificialisation **N**ette », jumeau numérique... dans une ambiance conviviale, avec quizz, jeux et temps d’échanges ! 

* [Programme détaillé](https://tools.openig.org/jpopenig/document/programme.pdf)
* [Inscription](https://tools.openig.org/jpopenig/index.php)
* En bonus, la rétrospective 2021, en mode *OPenIG Matin* sur les Données Majic : 

<iframe title="Rétrospective JP OPenIG 2021 : Données Foncières, un atout pour votre SIG !" src="https://peertube.iriseden.eu/videos/embed/27b29943-51ec-465b-b6b4-7d19ce3d90b2" allowfullscreen="" sandbox="allow-same-origin allow-scripts allow-popups" width="560" height="315" frameborder="0"></iframe>

Inscrivez-vous vite et faites passer l’info autour de vous ! Une participation à distance sera également possible, avec une transmission des conférences en direct, mais :shushing_face: **chut**, c'est un secret parce qu'on essaie désespérément de refaire du présentiel.

(*) La Journée Professionnelle d’OPenIG porte sur des thèmes en lien avec l’actualité de la géomatique et les besoins de veille exprimés par les membres d'OPenIG, plateforme régionale associative pour l'information géographique en Occitanie, le Crige Occitanie quoi?

![Image si besoin de mise en avant](https://tools.openig.org/jpopenig/document/affiche.png)

![Miniature_JPro_OPenIG](https://user-images.githubusercontent.com/72464583/165144065-d6e9439a-4292-4da0-9198-04d224251c0b.png)
.

**Comment by igeofr** [comment]
Voici la preview : https://preview-pullrequest-586--geotribu-preprod.netlify.app/rdp/2022/rdp_2022-04-29/#journee-pro-openig-geomatique-ia-et-changement-climatique-le-24-mai-2022

Si t'es ok, je vais rajouter une phrase pour rappeler que l'évènement est accessible à tous et pas uniquement aux membres d'OpenIG.

**Comment by Gab-OPenIG** [comment]
Tu peux ajouter ça, c'est tout bon pour moi @igeofr !
