### ISSUE TITLE
Formations Trame Noire OFB et CPIE

### ISSUE THREAD

**Issue by Gab-OPenIG** [geotribu/website#595]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui
- [X] Non

### Votre nom

Gabriel Poujol

### Votre adresse email

gpoujol@openig.org

### Licence

- [X] J'accepte

### Section / catégorie

Divers

### Mots-clés

Trame_noire, TVB, TVBN, Biodiversité, Pollution_Lumineuse

### Titre de la news

Pour y voir clair dans la trame noire :milky_way:

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/night.png

### Contenu de la news

# Formez vous à la Trame Noire avec le MNHN

Après plus de 10 ans de TVB, on passe depuis [2018](https://www.legifrance.gouv.fr/loda/id/JORFTEXT000037864346/) à la TVBN. Le N, pour Trame Noire, inclut la réduction des pollutions ~~nocturnes~~ lumineuses pour le maintien de la biodiversité. Les formations incluent cours théoriques :woman_teacher_tone1:, retours d’expériences :recycle:, mise en pratique :man_juggling_tone3: et  sorties :camping:, avec des intervenants variés (écologues, éclairagistes, collectivités, parcs, etc.).  [Romain Sordello](http://www.biodiversite.romain-sordello.fr/?p=quisuisje), expert national en la matière, pourra vous en dire plus.

- **Formation Trame Noire de l'[OFB](https://www.ofb.gouv.fr/) du 27/06 au 01/07 à Foix (09)** : 2 modules au choix, [base](https://formation.ofb.fr/session/fiche?id=4047) et [approfondissement](https://formation.ofb.fr/session/fiche?id=3907).
- **Formation Trame noire du [CPIE Brenne Berry](https://www.cpiebrenne.fr/)  du 14/11 au 17/11 à Mézières (36)** : p.29 du [catalogue](https://www.cpiebrenne.fr/wp-content/uploads/2022/03/Catalogue-Formation-Stages-en-Brenne-2022.pdf) & bulletin d’inscription à la fin.

**Public cible** : chargés de missions/techniciens de parcs, collectivités, services de l’état, établissements publics, bureaux d’études, associations, ... écologues, urbanistes, éclairagistes,

**Comment by Guts** [comment]
Merci Gabriel pour cette nouvelle suggestion de news ! Top ! 

> Bon c'est peut être un peu dense, je peux tailler dans le gras si besoin.

C'est en effet un peu trop long pour une news de GeoRDP. Donc soit tu tailles dans le gras (c'est la vie), soit on le publie comme article.

Qu'en penses-tu ?

**Comment by Gab-OPenIG** [comment]
Bon c'est peut être un peu dense, je peux tailler dans le gras si besoin. Et j'ai pas trouvé de catégorie _formations_, alors entre _représentation carto_, _géo event_, _divers_, je vous laisse choisir ...

**Comment by Gab-OPenIG** [comment]
Je vais tailler

**Comment by Gab-OPenIG** [comment]
J'ai taillé le gras

**Comment by Guts** [comment]
## Préparation automatique de la contribution

### En-tête

```yaml
tags:
    - écologie
    - pollution
    - trame noire
    - trame verte
```

### News

```markdown
### Pour y voir clair dans la trame noire :milky_way:

![icône globe night](https://cdn.geotribu.fr/img/internal/icons-rdp-news/night.png "icône globe night"){: .img-rdp-news-thumb }

Après plus de 10 ans de TVB, on passe depuis [2018](https://www.legifrance.gouv.fr/loda/id/JORFTEXT000037864346/) à la TVBN. Le N, pour Trame Noire, inclut la réduction des pollutions ~~nocturnes~~ lumineuses pour le maintien de la biodiversité. Les formations incluent cours théoriques :woman_teacher_tone1:, retours d’expériences :recycle:, mise en pratique :man_juggling_tone3: et  sorties :camping:, avec des intervenants variés (écologues, éclairagistes, collectivités, parcs, etc.).  [Romain Sordello](http://www.biodiversite.romain-sordello.fr/?p=quisuisje), expert national en la matière, pourra vous en dire plus.

- Formation Trame Noire de l'[OFB](https://www.ofb.gouv.fr/) du 27/06 au 01/07 à Foix (09) : 2 modules au choix, [base](https://formation.ofb.fr/session/fiche?id=4047) et [approfondissement](https://formation.ofb.fr/session/fiche?id=3907).
- Formation Trame noire du [CPIE Brenne Berry](https://www.cpiebrenne.fr/)  du 14/11 au 17/11 à Mézières (36) : p.29 du [catalogue](https://www.cpiebrenne.fr/wp-content/uploads/2022/03/Catalogue-Formation-Stages-en-Brenne-2022.pdf) & bulletin d’inscription à la fin.

Public cible : chargés de missions/techniciens de parcs, collectivités, services de l’état, établissements publics, bureaux d’études, associations, ... écologues, urbanistes, éclairagistes, 

!!! info "Contribution externe"
    Cette news est proposée par Gabriel POUJOL via le [formulaire GitHub](https://github.com/geotribu/website/issues/new?assignees=Guts&labels=contribution+externe%2Crdp%2Ctriage&template=RDP_NEWS.yml) - [voir le ticket](https://github.com/geotribu/website/issues/595). Merci !
```

Commande git à utiliser :

```bash
git commit --author="Gabriel POUJOL <gpoujol@openig.org>" -m "Close #595. Ajout news trame noire"
```
