### ISSUE TITLE
Appel à la traduction !

### ISSUE THREAD

**Issue by lbartoletti** [geotribu/website#614]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui
- [X] Non

### Votre nom

Loïc Bartoletti

### Votre adresse email

lbartoletti@tuxfamily.org

### Licence

- [X] J'accepte

### Section / catégorie

Divers

### Mots-clés

PostGIS, GRASS GIS, OSGeo

### Titre de la news

Appel à la traduction !

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

Contribuer à un projet OpenSource, ce n'est pas que pondre des ~~bugs~~ fonctionnalités super excitantes. Un logiciel est comme un produit, il n'y a pas que les codeurs dessus, il faut de nombreuses autres forces vives pour le sortir et faire fonctionner la communauté autour.

En particulier, remercions les traducteurs, qui font un travail formidable pour que nous ayons nos logiciels dans la langue de Molière et non dans un shakespeare globishien.

Pour cela, nous utilisons des outils et services qui permettent de traduire chaque chaîne de texte et le livrer dans chaque langues envisageables. Classiquement, les projets utilisaient [Transiflex](https://www.transifex.com/) ; qui est encore utilisé par QGIS.

C'est passé presque inaperçue, mais cela fait déjà quelque temps que des projets de l'OSGeo utilisent un nouvel outil pour traduire ses logiciels : [weblate](https://weblate.org/fr/)

L'avantage est qu'il est [directement hébergé](https://weblate.osgeo.org/) sur le dépôt de l'OSGeo et vous pouvez vous connecter avec votre compte existant !

Vous souhaitez contribuer à PostGIS, GRASS, GTT, PgRouting, etc ? Venez nous aider à compléter et améliorer la traduction de vos outils préférés.

### Message libre

Désolé pour la news à la rache... hésitez donc pas à corriger/améliorer ou même reporter...

**Comment by Guts** [comment]
Merci de ta contribution.

News intégrée avec de légères reformulations que tu es évidemment libre de refuser : https://preview-pullrequest-605--geotribu-preprod.netlify.app/rdp/2022/rdp_2022-05-27/#traduction-des-logiciels-libres

**Comment by lbartoletti** [comment]
@Guts y'a (au moins) une typo : `C'est souvent un bon point de départ pour contribue rà un projet `

contribue rà
