### ISSUE TITLE
Mettre à jour le logo geOrchestra sur le CDN

### ISSUE THREAD

**Issue by MaelREBOUX** [geotribu/website#627]
Bonjour,

Il faudrait mettre à jour le logo de geOrchestra sur le CDN.
Merci d'avance.

![georchestra_logo](https://user-images.githubusercontent.com/6370443/173776508-6ae3f3c6-7fcb-4fcd-b72a-44526be4fb17.png)

**Comment by pierrejego** [comment]
![georchestra_logo_white](https://user-images.githubusercontent.com/11499415/174063785-b606dfee-f989-4405-baab-9eb03fde7827.png)

Il existe celui là
