### ISSUE TITLE
OpenStreetMap et entreprenariat numérique : Nathalie Sidibé rejoint Wikipédia

### ISSUE THREAD

**Issue by KazeNoOni** [geotribu/website#629]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui
- [ ] Non

### Votre nom

Delphine Montagne

### Votre adresse email

delphine.montagne@univ-pau.fr

### Licence

- [X] J'accepte

### Section / catégorie

OpenStreetMap

### Mots-clés

Wikipédia, OpenStreetMap, Afrique

### Titre de la news

OpenStreetMap et opendata : Nathalie Sidibé rejoint Wikipédia

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

Pour Nathalie Sidibé, OpenStreetMap a "changé sa vie". Co-fondatrice d'OSM Mali, elle est militante des données opendata qu'elle voit comme une manière d'utiliser les financements de manière efficiente. Entre la cartographie des réseaux de minibus (sotrama), des équipements publics et la formation au numérique, sa biographie, publiée à présent sur Wikipédia, est à [découvrir ici](https://fr.wikipedia.org/wiki/Nathalie_Sidib%C3%A9).
![Photo de minibus malien](https://fr.wikipedia.org/wiki/Nathalie_Sidib%C3%A9#/media/Fichier:Taxi_vans_in_Bamako.jpg "Les Sotrama, minibus maliens").

### Message libre

Je suis à l'origine de la création de la page, faite à l'occasion du SOTM.

**Comment by Guts** [comment]
Bonsoir @KazeNoOni,

Merci pour la news. Il semble qu'il y a un problème avec l'image. Peux-tu la renvoyer stp ?

**Comment by KazeNoOni** [comment]
Bonjour, elle est ici : https://fr.wikipedia.org/wiki/Nathalie_Sidib%C3%A9#/media/Fichier:Taxi_vans_in_Bamako.jpg
Merci !
