### ISSUE TITLE
Colette Cauvin sur Wikipédia

### ISSUE THREAD

**Issue by KazeNoOni** [geotribu/website#634]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui
- [ ] Non

### Votre nom

Delphine Montagne

### Votre adresse email

delphine.montagne@univ-pau.fr

### Licence

- [X] J'accepte

### Section / catégorie

Divers

### Mots-clés

Wikipédia, cartographie, anamorphose

### Titre de la news

Cartographie et anamorphose : Colette Cauvin rejoint Wikipédia

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

Ouvrez n'importe quel ouvrage de cartographie : en France, difficile de parler d'anamorphoses cartographiques sans voir apparaître le nom de [Colette Cauvin](https://fr.wikipedia.org/wiki/Colette_Cauvin). Elle leur a consacré une partie de sa carrière scientifique à Strasbourg, ce qui a même valu à son équipe le surnom de "tortionnaires de cartes" ! Pour découvrir les cartes piézoplèthes, la régression bidimensionnelle et son travail sur les cartes cognitives, avec des exemples de cartes en creative commons (créées au passage), un seul endroit : [Wikipédia ](https://fr.wikipedia.org/wiki/Colette_Cauvin)!

![image](https://user-images.githubusercontent.com/17273438/174457179-12f5f1be-233e-4b78-8451-1250061e8df3.png)

### Message libre

J'ai créé la page ainsi que les différentes cartes

**Comment by Guts** [comment]
Bonjour @KazeNoOni,

Merci pour cette nouvelle contribution (et pour la page surtout !).
