### ISSUE TITLE
Un nouveau service de géocodage

### ISSUE THREAD

**Issue by IGNF-Xavier** [geotribu/website#654]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui
- [ ] Non

### Votre nom

Xavier

### Votre adresse email

xavier.thauvin@ign.fr

### Licence

- [X] J'accepte

### Section / catégorie

Open Data

### Mots-clés

géocodage, BAN

### Titre de la news

Un nouveau géocodage

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/journalisme.png

### Contenu de la news

Avec discrétion du fait de la période estivale, une préfiguration du futur service de la Géoplateforme a été déployée : **les services de géocodage Bêta 2.0.**; et maintenant officiellement [annoncée](https://geoservices.ign.fr/actualites/2022-09-07-geocodage-autocompletion).

Services au pluriel ? Oui car ces derniers s'adressent (jeu de mot) à plusieurs référentiels : adresse avec la **Base Adresse Nationale** (BAN), les Points d'intérêts (POI) et les parcelles au travers de plusieurs services : géocodage direct, géocodage inverse, autocomplétion. 

A noter que l'API mise en œuvre converge avec celle d'Etalab pour ce qui est des appels et des réponses. Surtout, elle n'est pas limité au référentiel adresse. 

A suivre, le déploiement de ces services sur la Géoplateforme et le géocodage en masse. Les prochains [temps d'information](https://ign.fr/geoplateforme/agenda) du programme Geoplateforme permettront d'en savoir plus!

Si le nouveau service vous intéresse, n'hésitez pas à consulter [les ressources à disposition](https://geoservices.ign.fr/documentation/services/api-et-services-ogc/service-de-geocodage-beta-20), notamment les fichiers YAML (Yet Another Markup Language) qui permettent de découvrir facilement les fonctionnalités.

**Comment by Guts** [comment]
Intégrée après quelque reformulation. En preview ici : https://preview-pullrequest-677--geotribu-preprod.netlify.app/rdp/2022/rdp_2022-09-09/#les-services-de-geocodage-de-la-geoplateforme-sortent-en-version-2-beta

**Comment by IGNF-Xavier** [comment]
Merci. 
On est désormais à la rentrée et le service annoncé ce 7/09. J'ai donc ajusté le texte
