### ISSUE TITLE
Retour SOTM monde

### ISSUE THREAD

**Issue by KazeNoOni** [geotribu/website#680]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui
- [X] Non

### Votre nom

Delphine Montagne

### Votre adresse email

montagnedelphine@gmail.com

### Licence

- [X] J'accepte

### Section / catégorie

OpenStreetMap

### Mots-clés

OpenStreetMap, SOTM

### Titre de la news

Quoi de neuf au State of the Map monde ?

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

Fin août s'est déroulé la réunion mondiale d'OpenStreetMap. Au menu, des présentations techniques, des nouveautés issues du monde de la recherche et des discussions sur la communauté. Le compte-rendu, en français, est à [lire ici.](https://www.openstreetmap.fr/retour-sur-le-state-of-the-map-2022-en-italie/)
![image](https://user-images.githubusercontent.com/17273438/187969517-08dabea1-329f-43c6-905c-b2c3f3820a35.png)
[Photo by Carlo Prevosti, Wikimedia Italia, CC BY-SA 4.0](https://commons.wikimedia.org/wiki/Category:State_of_the_Map_2022_-_group_photo)

### Message libre

Personnes à mentionner pour Twitter : @overflorian, @nlehuby et @fre2d

**Comment by Guts** [comment]
Merci !

News intégrée et en preview : https://preview-pullrequest-677--geotribu-preprod.netlify.app/rdp/2022/rdp_2022-09-09/#openstreetmap

> Personnes à mentionner pour Twitter : @overflorian, @nlehuby et @fre2d

On va essayer d'y penser. Si on se rate, pourras-tu te charger de compléter notre tweet stp :pray: ?

**Comment by KazeNoOni** [comment]
Il y a un soucis dans le preview ! Les remerciements sont ceux de WP et non ceux pour une news technique. C'est noté pour les mentions !
