### ISSUE TITLE
La géographe Elena Chiozza 

### ISSUE THREAD

**Issue by KazeNoOni** [geotribu/website#683]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui
- [ ] Non

### Votre nom

Delphine Montagne

### Votre adresse email

delphine.montagne@univ-pau.fr

### Licence

- [X] J'accepte

### Section / catégorie

Divers

### Mots-clés

Wikipédia, Argentine, SIG

### Titre de la news

Aux origines des SIG en Argentine : portait d'Elena Chiozza

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

Comment avez-vous découvert les SIG ? L'importance de l'information géographique ? Vous arrivez à savoir quelles techniques vont révolutionner votre discipline ?
Nous sommes dans les années 80, dans une Argentine encore marquée par les traces de la dictature de la révolution, et Elena Chiozza a réussi un tour de force. A savoir moderniser la géographie du pays, avec notamment l'introduction des SIG et de la télédétection (entre autre). Comme cela ne suffisait pas, elle a aussi rédigé plusieurs ouvrages à destination du grand public avec ces outils. Dire que le plus connu, _Mi país, tu país..._ [Mon pays, votre pays...] fut une réussite est un euphémisme : réédité de nombreuses fois, décliné sur tous les supports (avec un objet ultra-moderne : le CD-ROM) l'ouvrage plaît par ses cartes, son analyse des photos aériennes et ses croquis décortiquant les paysages.
Un sens de l'histoire qui a valu à Elena Chiozza de nombreux hommages et récompenses... Car cet épisode n'est qu'une toute petite partie de sa riche et incroyable carrière de géographe (de caractère). Cette figure argentine est à découvrir [sur sa page Wikipédia](https://fr.wikipedia.org/wiki/Elena_Chiozza), tout juste traduite en français !
![image](https://user-images.githubusercontent.com/17273438/188616733-4c4de405-1006-4395-87a0-3b78f195184c.png)

### Message libre

J'ai traduit et enrichit cette page.

**Comment by Guts** [comment]
Merci news intégrée et en preview : https://preview-pullrequest-677--geotribu-preprod.netlify.app/rdp/2022/rdp_2022-09-09/

J'ai choisi de ne pas ajouter sa photo car ça colle pas trop avec les illustrations que l'on met dans les RDP habituellement, mais si tu trouves que c'est dommage et que je devrais faire bouger nos habitudes, je te laisse me convaincre ;)
