### ISSUE TITLE
Ajout évènement journée LiDAR du CRAIG le 4 octobre

### ISSUE THREAD

**Issue by Gab-OPenIG** [geotribu/website#684]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui
- [X] Non

### Votre nom

Gabriel Poujol

### Votre adresse email

gabriel.poujol@gmail.com

### Licence

- [X] J'accepte

### Section / catégorie

Geo-event

### Mots-clés

LiDAR, IGN

### Titre de la news

Journée LiDAR au CRAIG à Clermont-Ferrand le 4 octobre

### Icône de la news

https://cdn.geotribu.fr/img/logos-icones/divers/lidar.jpg

### Contenu de la news

Le [CRAIG](https://www.craig.fr/) organise ce 4 octobre une **[journée technique sur le LiDAR](https://www.craig.fr/fr/actualite/3768-journee-technique-le-lidar-un-outil-au-service-de-la-connaissance-des-territoires)** : cas d'usages thématiques et détails du [programme LiDAR HD](https://www.ign.fr/appel-projets-ignfab-lidar/accueil). Ce sera en présentiel à Clermont-Ferrand --> places limitées !

**Comment by Gab-OPenIG** [comment]
Pas réussi à mettre une jolie icône

**Comment by igeofr** [comment]
C'est ajouté et visible [en preview](https://preview-pullrequest-677--geotribu-preprod.netlify.app/rdp/2022/rdp_2022-09-09/#journee-lidar-au-craig)
