### ISSUE TITLE
Style OpenTile Seigneur des anneaux

### ISSUE THREAD

**Issue by KazeNoOni** [geotribu/website#687]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui
- [X] Non

### Votre nom

Delphine Montagne

### Votre adresse email

delphine.montagne@univ-pau.fr

### Licence

- [X] J'accepte

### Section / catégorie

OpenStreetMap

### Mots-clés

Openstreetmap, cart

### Titre de la news

OpenStreetMap gagne le statut de Lord

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

A l'occasion de la sortie de _Le Seigneur des Anneaux : Les Anneaux de Pouvoir_, OpenMapTiles a proposé un style de carte dérivé de la série. [_Lord of the Maps_](https://labs.maptiler.com/showcase/lotrmap/#11.82/18.51069/-72.39485/0/40) s'appuie bien évidemment sur les données OpenStreetMap. Un rendu pour apprécier différemment les données que vous avez saisies !

**Comment by Guts** [comment]
News intégrée dans la prochaine RDP. Preview : https://preview-pullrequest-693--geotribu-preprod.netlify.app/rdp/2022/rdp_2022-09-23/#representation-cartographique

Je me suis permis de la compléter avec des informations que j'avais glanées il y a quelques temps et avec celles de Cartigraphie Numérique. Si ça te dérange, j'en fais une news à part évidemment.
