### ISSUE TITLE
Les deuxièmes rencontres mviewer

### ISSUE THREAD

**Issue by smevel** [geotribu/website#695]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui
- [ ] Non

### Votre nom

Stéphane Mével-Viannay

### Votre adresse email

mviewer@bretagne.bzh

### Licence

- [X] J'accepte

### Section / catégorie

Geo-event

### Mots-clés

mviewer, opensource, visualiseur

### Titre de la news

Deuxièmes rencontres mviewer le 25 novembre à Paris

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

Le 25 novembre, le Comité de pilotage (PSC mviewer) organise les deuxièmes rencontres mviewer, le visualiseur cartographique,
Après une première édition à Rennes, la communauté se réunit à Paris (15e) au Lieu de la transformation publique dans le cadre du Mois de l'innovation publique.

**Programme provisoire**
- 10h00 - Accueil et introduction par le Comité de pilotage (PSC)
- 10h10 - Connaître mviewer et ses utilisateurs : Présentation de mviewer - À la rencontre de la communauté - Cas d’usages : démos / présentations flash
- 12h30 - Pause déjeuner - (! Attention : le repas ne sera pas pris en charge par les organisateurs)
- 13h30 - La fabrique mviewer sous formes d’ateliers
- 16h30 - Clôture

L'inscription est ouverte sur [eventbrite](https://www.eventbrite.fr/e/billets-les-deuxiemes-rencontres-mviewer-372724227197). Un appel à communication sera prochainement lancé.

Plus d'information sur [mviewer](https://mviewer.netlify.app/fr/) et suivez nous [twitter](https://twitter.com/MviewerPsc) 

### Message libre
Illustration possible : https://mviewer.netlify.app/images/blog/affiche_2erencontres.png

**Comment by Guts** [comment]
Bonjour,

Merci de votre proposition, cependant la soumission de news est nominative pour des raisons de responsabilité. Merci d'éditer en indiquant une personne :pray:

**Comment by smevel** [comment]
> Bonjour,
> 
> Merci de votre proposition, cependant la soumission de news est nominative pour des raisons de responsabilité. Merci d'éditer en indiquant une personne 🙏

Merci du retour. Modification faîte !

**Comment by Guts** [comment]
Désolé pour la fermeture/réouverture, c'était pour éprouver notre tout nouvel automate de traitemnt des propositions de news :)

**Comment by Guts** [comment]
News intégrée à la prochaine RDP. PReview : https://preview-pullrequest-693--geotribu-preprod.netlify.app/rdp/2022/rdp_2022-09-23/#deuxiemes-rencontres-mviewer-le-25-novembre-a-paris
