### ISSUE TITLE
Traduire des vieux textes sur la carto et la géovisualisation de données

### ISSUE THREAD

**Issue by fbahoken** [geotribu/website#703]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui
- [ ] Non

### Votre nom

Françoise Bahoken (ou @fbahoken)

### Votre adresse email

frcse_bhk@yahoo.fr

### Licence

- [X] J'accepte

### Section / catégorie

Représentation Cartographique

### Mots-clés

cartographie, analyse spatiale, analyse de données, représentation

### Titre de la news

Des choroplèthes sans classes ?

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/matiere.png

### Contenu de la news

Dans le cadre du projet [Tribute to Tobler](https://github.com/tributetotobler) (TTT), une collection « traductions » de textes propose des rééditions bilingues et commentées d'articles scientifiques, publiés ou inédits, de Waldo R. Tobler. Pour savoir qui c'est, n'hésitez pas à lire la [bio. de Tobler](https://hypergeo.eu/waldo-tobler/) écrite par Colette Cauvin (anciennement Professeure à l'Université de Strasbourg) dans Hybergéo.

La dernière traduction en date est un papier symptomatique de l'auteur intitulé [Des cartes choroplèthes sans cartes?](https://hal.archives-ouvertes.fr/hal-03777114), traduit par Laurent Jégou (MCF à l'université de Toulouse) pour TTT. Ce papier ne devrait pas manquer d'attirer l'attention de tou.te.s les cartographes et géodatavisualisateurs.trices. 

Tobler s'interroge en effet sur la possibilité de construire des cartes choroplèthes, c'est-à-dire des cartes thématiques élaborées à partir de données quantitatives continues, sans discrétisation préalable de ces données. 
- What ? 
- Oui, des cartes thématiques de données quantitatives continues sans discrétisation.
- Mais ça ne va pas produire un #mapfail ? Voir sur Néocarto, le [mapfail](https://neocarto.hypotheses.org/4029)
- Euh... non puisque ces choroplèthes ne sont pas construites avec la variable visuelle taille, comme le serait des données quantitatives discrètes. Ces choroplèthes de données continues mobilisent quand même la variable visuelle valeur.
- Ouf ! l'honneur est sauf :-)  

C'est manière de procéder tient effectivement dans un pari de l'auteur qui peut apparaître assez osé, lorsque l'on sait l'écueil que cette pratique peut avoir sur la perception du phénomène représenté. Reste à savoir comment Tobler s'y prend, en lisant la traduction proposée.

D'ailleurs, pour bien se rendre compte de l'effet de cette proposition de choroplèthe sans classe, Laurent Jégou a porté la méthode de Tobler en .JS sur un Notebook Observable. Cela permet de la comparer avec deux méthodes de discrétisation bien connues : les quantiles et les intervalles égaux. [@ljegou - ttt-continuous-choropleth](https://observablehq.com/@ljegou/ttt-continuous-choropleth?oetm_referrer=https%3A%2F%2Fneocarto.hypotheses.org%2F&oetm_route=%2F%40ljegou%2Fttt-continuous-choropleth)

Pour finir, précisons que le but de ces traductions proposées par [TTT-traductions](https://github.com/tributetotobler/traductions) est de faciliter l'appropriation par la communauté francophone (les traductions sont toutes vers le français) d'une sélection de textes concernant des théories, des méthodes jadis développées par l'auteur et qui mériteraient d'être déterrées. Tous les textes en anglais de Tobler sont ainsi susceptibles d'être traduits, du moment qu'ils intéressent un.e traducteur/traductrice. Une WishList est d'ailleurs proposée et régulièrement enrichie en fonction de l'avancée de ce chantier de traduction. Les textes déjà en ligne étant également accessibles dans la section Traductions de la [collection HAL/TTT](https://hal.archives-ouvertes.fr/TTT).

Pour contribuer, rien de plus facile. Il convient soit de proposer une issue : [TTT-traductions is:issue](https://github.com/tributetotobler/traductions/issues), soit d'envoyer un email à @fbahoken et [Anne-Christine Bronner](mailto:anne-christine.bronner@misha.fr) pour intégrer le projet et accéder à la liste bibliographique des travaux de Tobler via la section [TTT-corpus](https://github.com/tributetotobler/corpus).

### Message libre

Je vous propose un petit article sur la traduction d'un texte qui devrait intéresser la communauté...
Le choix de mon pseudo, vous faites comme la dernière fois

**Comment by Guts** [comment]
Merci Françoise, super texte !

C'est ajouté pour la prochaine RDP. Preview : https://preview-pullrequest-693--geotribu-preprod.netlify.app/rdp/2022/rdp_2022-09-23/#representation-cartographique

**Comment by fbahoken** [comment]
Merci Julien !

Il y a deux petites erreurs :

1er § : c'est Hypergéo (et non Hybergéo)

et dans des [Des cartes choroplèthes sans classes ?](https://hal.archives-ouvertes.fr/hal-03777114), 

c'est sans "classes" et pas "sans cartes".

**Comment by Guts** [comment]
Pas certain d'avoir le temps de corriger d'ici la publication mais si @igeofr le fait pas, je m'en chargerai après coup.

Par contre, pas compris le truc du titre. C'est pas celui que tu avais mis ?

**Comment by Guts** [comment]
Sinon @fbahoken tu peux éditer directement via l'icône crayon de la preview normalement
