### ISSUE TITLE
UtagawaVTT propose une nouveau fond cartographique OSM pour le VTT

### ISSUE THREAD

**Issue by utagawal** [geotribu/website#711]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui
- [ ] Non

### Votre nom

Lilian Morinon

### Votre adresse email

contact@utagawavtt.com

### Licence

- [X] J'accepte

### Section / catégorie

Représentation Cartographique

### Mots-clés

Openstreetmap, Planetiler, Maputnik, VTT

### Titre de la news

Fond cartographique OSM pour le VTT

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/world.png

### Contenu de la news

Depuis 2002, UtagawaVTT.com contribue à l'échange de parcours GPS pour les pratiquants VTT et VTT-AE (VTT à Assistance électrique).

L'un des fondements de UtagawaVTT est la représentation des parcours GPX sur fond cartographique.

[![Capture-d-cran-2022-10-01-182309.jpg](https://i.postimg.cc/V6Q7FRq8/Capture-d-cran-2022-10-01-182309.jpg)](https://postimg.cc/KKfrGtpq)

Dès son lancement, le site s'est appuyé sur des serveurs de tuiles. Dans un premier temps Google Maps, puis l'IGN, et au gré des modifications des licences d'utilisation, UtagawaVTT a accueilli avec bienveillance le projet OpenStreetMap, qui sert désormais de carte par défaut sur les pages de recherche et de description des circuits VTT.

En veille permanente sur les déclinaisons de styles cartographiques, l'équipe était constamment en recherche d'un fond cartographique OpenSource, et donc basé sur OSM qui soit lisible, esthétique et adapté au VTT.

Sans véritable succès jusqu'à présent.

Or, les évolutions technologiques ont ouvert de fantastiques opportunités et permettent désormais à UtagawaVTT de proposer un fond de carte libre, dynamique et ciblé sur les besoins de la communauté VTT.

Tout est parti de l'arrêt du service de tuiles d'ombrages du relief. Le service utilisé jusqu'alors, a stoppé la diffusion des tuiles début 2022 et aucun autre service satisfaisant, ni en terme de performance, ni en budget, n'était disponible. Il n'y avait donc plus de possibilité d'afficher les ombrages sur les cartes du site.

L'équipe s'est alors penchée sur la possibilité de créer un serveur de tuiles dédié, dans l'optique de servir une couche d'ombrage (hillshading) pour les cartes en ligne.

Mais comme souvent, la sérendipité a frappé !

Après plusieurs tests, et grâce aux contributions convaincantes de [Openmaptiles](https://openmaptiles.org) évoquant la simplicité d'héberger un serveur de tuile, le choix était fait.
Un container Docker de [Tileserver-Gl](https://github.com/maptiler/tileserver-gl) plus tard, le serveur de tuiles UtagawaVTT était en ligne.

Restait à le remplir pour qu'il puisse proposer le contenu adéquat.

Avec un peu d'analyse de la littérature disponible sur le web, l'intérêt de travailler avec des tuiles vectorielles plutôt que raster, est devenu évident.

La découverte du projet [planetiler](https://github.com/onthegomap/planetiler), la mise à disposition de fichiers OSM sur la planète entière en format [MBtiles](https://osm.dbtc.link/mbtiles/) pour éviter de les calculer nous même, et le projet [Natural earth](https://www.naturalearthdata.com) ont permis d'avoir la base des données.

Puis, l'outil d'édition en ligne [Maputnik](https://maputnik.github.io/) a permis de donner un style "maison" 👨‍🎨 aux données cartographiques :
* Un rendu lisible et peu chargé tout en restant esthétique
* Des POIs intéressants pour les cyclistes (sommets, cols, refuges, points de vue, etc.)
* Des règles pour identifier visuellement et simplement les chemins non accessibles aux VTT ❌

Bien sûr, l'ajout des ombrages et des lignes niveaux a été fait grâce à des tuiles "Terrain" mondial mises à disposition par [Mapzen](https://www.mapzen.com/blog/terrain-tile-service), et des détails plus précis ont été calculés pour la France et l'Europe grâce au concours des scripts de [Makina Corpus](https://www.data.gouv.fr/fr/organizations/makina-corpus) et des données Copernicus.

Le résultat est disponible sur [maps.utagawavtt.com](https://maps.utagawavtt.com) et intégré aux cartes de [UtagawaVTT](https://www.utagawavtt.com).

Le style est [Opensource](https://github.com/utagawal/MTBmaptiles).

[![utagawavtt-3d-grenoble.jpg](https://i.postimg.cc/BQsgbbgm/utagawavtt-3d-grenoble.jpg)](https://postimg.cc/QV45nXv7)

La suite du projet est de construire une pyramide de tuiles d'ombrages et de contours bien plus précis grâce aux MNT plus détaillés existants (IGN, Copernicus...). C'est en cours et en partenariat avec [ElevationApi](https://elevationapi.com)

Chaleureux remerciements à [Olivier](https://omrs.fr/) et [Jérémy](https://blog.utagawavtt.com/fr/team) (le lead tech d'UtagawaVTT), sans qui ce projet n'aurait pas pu être possible, et [Batiste](https://reliefmaps.io) pour avoir guidé les choix au tout début du projet.

### Message libre

Première version

**Comment by utagawal** [comment]
Update images

**Comment by utagawal** [comment]
Mise à jour de l'article

**Comment by utagawal** [comment]
fix typo

**Comment by utagawal** [comment]
fix typo

**Comment by Guts** [comment]
Merci @utagawal, c'est intégré. Preview : https://preview-pullrequest-705--geotribu-preprod.netlify.app/rdp/2022/rdp_2022-10-07/#fond-cartographique-osm-pour-le-vtt

**Comment by utagawal** [comment]
Fix VTTAE

**Comment by Guts** [comment]
> Fix VTTAE

Je n'ai pas compris ce commentaire Lilian. Une fois le texte en preview, il faut le modifier dessus. Il est désormais publié mais il est toujours possible de le modifier : https://static.geotribu.fr/contribuer/edit/fix_content_from_website/
