### ISSUE TITLE
30DayMapChallenge

### ISSUE THREAD

**Issue by KazeNoOni** [geotribu/website#730]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui
- [X] Non

### Votre nom

Delphine MONTAGNE

### Votre adresse email

delphine.montagne@univ-pau.fr

### Licence

- [X] J'accepte

### Section / catégorie

Représentation Cartographique

### Mots-clés

carte

### Titre de la news

C'est bientôt le 30DayMapChallenge !

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

On a parlait [début octobre](https://static.geotribu.fr/rdp/2022/rdp_2022-10-07/#30daymapchallenge-2022), c'est dans moins de 15 jours... Durant tout le mois de novembre, c'est le [30DayMapChallenge](https://30daymapchallenge.com/) ! L'objectif ? Créer ensemble, chaque jour, une carte sur un sujet donné. Un défi personnel où l'objectif est moins de faire mieux que les autres que de s'entraîner, découvrir les autres idées et représentations cartographiques. Une couleur, un jeu de données, un pays... Il y en a pour tous les goûts et tous les niveaux. Une seule règle : publier la carte le bon jour sur un réseau social.
Aucune inscription nécessaire, vous êtes libres de vos outils... Et peu importe si vous n'arrivez pas jusqu'aux 30 cartes, le but est de s'amuser !
![image](https://user-images.githubusercontent.com/17273438/196942312-30fccceb-f2b2-4b4c-8121-c348ec85fa58.png)
Les réalisations de l'an dernier sont, elles, [à voir ici](https://static.geotribu.fr/rdp/2021/rdp_2021-12-03/#30daymapchallenge).

**Comment by Guts** [comment]
Merci Delphine.

C'est dans le tuyau !
