### ISSUE TITLE
Leida Lepik

### ISSUE THREAD

**Issue by KazeNoOni** [geotribu/website#732]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui
- [ ] Non

### Votre nom

Delphine MONTAGNE

### Votre adresse email

delphine.montagne@univ-pau.fr

### Licence

- [X] J'accepte

### Section / catégorie

Divers

### Mots-clés

Wikipédia, Estonie, Regio

### Titre de la news

Leida Lepik : voyage en cartographie estonienne

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

Après [Vanessa Lawrence de l'Ordnance Survey](https://static.geotribu.fr/rdp/2022/rdp_2022-10-21/#vanessa-lawrence-ancienne-directrice-de-lordnance-survey-sur-wikipedia) il y a 15 jours, direction l'Estonie ! Tout le monde sait placer le pays sur une carte ? (les pays baltes sont des pays pratiques, ils se sont placés du nord au sud par ordre alphabétique) Prenez votre polaire pour découvrir le parcours de [Leida Lepik](https://fr.wikipedia.org/wiki/Leida_Lepik) ! Au sortir de l'URSS, elle a fait partie des géographes qui ont permis à l'Estonie de sa doter d'une cartographie indépendante. Passionnée de voyages, elle a rapporté de nombreuses innovations pour son entreprise de cartographie, Regio, un peu l'équivalent de Michelin en France (toutes proportions gardées, bien entendu). A lire au chaud [sur Wikipédia ](https://fr.wikipedia.org/wiki/Leida_Lepik)!
![image](https://user-images.githubusercontent.com/17273438/197754013-08398487-7ca3-4c93-b5a4-6bc0ef028273.png)

### Message libre

J'ai traduit et enrichi cette page.

**Comment by Guts** [comment]
Merci Delphine pour cette news et surtout pour ton travail sur Wikipédia, c'est top !

C'est dans le tuyau et en preview : https://preview-pullrequest-731--geotribu-preprod.netlify.app/rdp/2022/rdp_2022-11-04/#leida-lepik-voyage-en-cartographie-estonienne
