### ISSUE TITLE
Sortie de Clipper2

### ISSUE THREAD

**Issue by lbartoletti** [geotribu/website#738]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui
- [X] Non

### Votre nom

Loïc Bartoletti

### Votre adresse email

lbartoletti@tuxfamily.org

### Licence

- [X] J'accepte

### Section / catégorie

En bref

### Mots-clés

GIS, développement, algorithmique

### Titre de la news

Sortie de la seconde édition de Clipper

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

Comme il n'y a pas que GEOS pour faire des calculs de géométrie. Angus Johnson vient de sortir la version 2 de sa célèbre bibliothèque de calcul de "clipping" (opérations booléennes) : [Clipper](http://www.angusj.com/clipper2/Docs/Overview.htm).

Ce n'est pas qu'une évolution de son ancienne bibliothèque, mais une réécriture partielle, notamment en C++. qui est "[much better](http://www.angusj.com/clipper2/Docs/Changes.htm)" comme il l'indique.

À noter que c'est cette bibliothèque qu'utilise SAGA pour réaliser ses calculs.

### Message libre

Une petite news un peu technique, mais il ne faut pas la louper !

N'hésitez-pas si vous souhaitez ajouter des explications.

**Comment by Guts** [comment]
Pour mémohttps://github.com/AngusJohnson/Clipper2/releases
