### ISSUE TITLE
Zooms circulaires dans une mise en page QGIS (traduction billet de blog North Road)

### ISSUE THREAD

**Issue by jeremieprudhomme** [geotribu/website#741]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui
- [X] Non

### Votre nom

Jérémie PRUD'HOMME

### Votre adresse email

p.jeremie@gmail.com

### Licence

- [X] J'accepte

### Section / catégorie

Logiciel

### Mots-clés

QGIS

### Titre de la news

Zooms circulaires dans une mise en page QGIS

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

_Cet article est une traduction du [billet de blog](https://north-road.com/2022/11/04/creating-circular-insets-and-other-fun-qgis-layout-tricks/) publié le 4 novembre par North Road à l'occasion du [30 Day Map Challenge](https://twitter.com/hashtag/30DayMapChallenge)._

### Création de zooms circulaires et autres astuces amusantes de mise en page dans QGIS
_Grâce à la récente popularité du «30 Day Map Challenge», le mois de novembre est devenu synonyme de belles cartes et cartographies.  Au cours de ce mois de novembre, nous allons partager un certain nombre de conseils et d'astuces qui utilisent certaines fonctionnalités avancées de QGIS pour aider à créer de belles cartes._

Une technique qui peut améliorer considérablement l'apparence des cartes consiste à remplacer les zooms rectangulaires par des formes plus organiques, telles que des cercles ou des ovales.

En 2020, nous avons eu l'occasion d'ajouter la possibilité dans les mise en page de QGIS de créer directement des zooms circulaires (grâce au parrainage de la ville de Canning, en Australie !). Bien que cette fonctionnalité facilite la création de zooms non rectangulaires, de nombreux utilisateurs de QGIS ne savent peut-être pas que c'est possible. Nous avons donc voulu mettre en avant cette fonctionnalité pour notre premier post du 30 Day Map Challenge.

Commençons par un exemple de carte. Nous vous présentons ci-dessous un extrait de la [candidature de Brisbane aux Jeux olympiques de 2032](https://stillmed.olympics.com/media/Documents/Olympic-Games/Brisbane-2032/General/IOC-Feasibility-Assessment-Brisbane.pdf?_ga=2.48780838.1295957495.1666960789-1227590087.1665520398) que certains membres de l'équipe de North Road ont contribué à créer (au nom de [SMEC](https://www.smec.com/au/) pour [EKS](https://www.eks.com/)). Cette carte est conçue pour mettre en évidence les sites potentiels dans le sud-est du Queensland et les possibilités de déplacement entre ces régions :
![Olympic-map-2-768x782](https://user-images.githubusercontent.com/9571164/200112536-e938f1aa-e4fc-4959-8952-e6e4e56f4ebf.png)
Plan d'ensemble des sites pour les Jeux olympiques de 2032, évaluation de faisabilité du CIO - Jeux olympiques, Brisbane février 2021

Les cercles figuraient en bonne place sur les cartes des précédentes candidatures olympiques (comme celle de Budapest), dont nous nous sommes inspirés. En utilisant le même langage que les destinaires de la carte – pensez aux anneaux olympiques ! – cela peut, ou non, jouer un rôle.
![2024-Bid-Masterplan-Budapest-2024-1-768x518](https://user-images.githubusercontent.com/9571164/200112912-29ad96b1-adc0-476b-91cd-c324b1c39293.jpg)
Plan d'ensemble des Jeux olympiques de Budapest 2024

#### Guide étape par étape de la création d'un zoom circulaire

Tout d'abord, préparez une mise en page avec une carte principale et un zoom. Veillez à ce que celui-ci soit suffisamment grand pour couvrir le cercle souhaité :
![base-map-768x548](https://user-images.githubusercontent.com/9571164/200113058-5c6d24a9-8297-4181-b771-9bdbe3314056.png)

Dans la barre d'outils de mise en page, cliquez sur le bouton Ajouter Forme, puis sélectionnez Ajouter Ellipse :
![Ajouter Ellipse](https://user-images.githubusercontent.com/9571164/200113152-5de641be-2847-4e7f-bce0-b141daa264e8.PNG)

Dessinez l'ellipse au milieu de votre zoom (astuce : si vous maintenez la touche Maj enfoncée pendant que vous dessinez l'ellipse, vous la forcerez à prendre une forme circulaire !) Si vous n'avez pas réussi à créer un cercle exact, vous pouvez préciser manuellement la largeur et la hauteur dans les propriétés de l'élément de forme. Pour cet exemple, nous avons choisi un cercle de 50 mm x 50 mm :
![Dimensions Ellipse](https://user-images.githubusercontent.com/9571164/200113336-52576afd-14b0-4303-827c-4e8927760546.png)

Ensuite, sélectionnez l'élément zoom et, dans ses propriétés, cliquez sur le bouton Paramètres de découpage :
![Parametres de découpage](https://user-images.githubusercontent.com/9571164/200113390-5949b4ae-abad-4832-9a3c-b50f712889ed.PNG)

Dans les paramètres de découpage, faites défiler jusqu'à la deuxième section et cochez la case _Découper aux limites de l'élément_, puis sélectionnez votre élément Ellipse dans la liste. (Si vous avez des étiquettes affichées dans votre zoom, vous pouvez également cocher l'option « Forcer les étiquettes à l'intérieur de la forme de découpage » pour forcer ces étiquettes à l'intérieur du cercle. Si vous ne cochez pas cette option, les étiquettes seront autorisées à déborder en dehors du cercle).
![Découpage Ellipse](https://user-images.githubusercontent.com/9571164/200113587-39953f47-239b-4fd4-ae8d-623bc8e1eecb.PNG)

Votre zoom est maintenant lié à l'ellipse !
![clipped-inset](https://user-images.githubusercontent.com/9571164/200113591-1f5723b6-da57-4b96-9950-90534a2c3c87.png)

Encore un peu plus de magie à ajouter à cette carte – dans les propriétés de la carte principale, cliquez sur Aperçus et créez-en un pour le zoom, il affichera alors la zone circulaire visible et non le rectangle !
![overview-map](https://user-images.githubusercontent.com/9571164/200113850-b9d8127f-f26c-4714-920b-9feec0ceced8.png)

#### Point bonus : un texte de titre circulaire !

Pour les utilisateurs avancés, nous avons une autre astuce amusante... et par amusante nous voulons dire « jouons avec les radians » ! Ici, nous allons créer un titre avec un arrière-plan calé sur le contour de notre zoom circulaire. Cela demande un peu de doigté, mais le résultat final peut être visuellement remarquable ! Nous allons utiliser l'élément HTML de la mise en page de QGIS pour créer un dessin avancé. Une certaine expérience du codage HTML et CSS est donc souhaitable. (Une autre approche serait d'utiliser une application d'illustration vectorielle comme Inkscape, et d'ajouter votre titre et votre fond circulaire en tant qu'élément SVG dans la mise en page d'impression).

Nous allons commencer par créer un texte circulaire incurvé :
![text](https://user-images.githubusercontent.com/9571164/200114170-ba31b305-b0cd-4890-a5c4-97be30cfce2e.png)

Tout d'abord, ajoutez un « cadre HTML » à votre mise en page d'impression :
![Ajouter HTML](https://user-images.githubusercontent.com/9571164/200114203-804421df-d396-4893-9f10-6ae79660f7ee.PNG)

Les cadres HTML permettent de placer du contenu dynamique dans vos mises en page, qui peuvent utiliser HTML, CSS et JavaScript pour créer des composants graphiques.

Dans le champ « source » de l'élément HTML, ajoutez le code suivant :
```
<svg height="300" width="350">
        <defs>
            <clipPath id="circleView">
                <circle id="curve" cx="183" cy="156" r="25" fill="transparent" />
            </clipPath>
        </defs>
        <path id="forText" d="M 28,150, C 25,50, 180,-32,290,130" stroke="" fill="none"/>
            <text x="0" y="35" width="100">
                <textpath xlink:href="#forText">
                    <tspan font-weight="bold" fill="black">Place text here</tspan>
                </textpath>
            </text>
             <style>
    <![CDATA[
      text{
        dominant-baseline: hanging;
        font: 20px Arial;
      }
    ]]>
  </style>
</svg>
```

Maintenant, ajoutons un arrière-plan pour mettre davantage l'accent sur le titre !
![text-with-background-1-300x277](https://user-images.githubusercontent.com/9571164/200114566-72898388-1ba2-4eea-b693-e8fcd6040e2f.png)

Pour ajouter l'arrière-plan, créez un autre cadre HTML. Nous allons à nouveau créer la forme de l'arc en utilisant un élément SVG, donc ajoutez le code suivant dans le champ « source » de l'élément :
```
<svg width="750" height="750" xmlns="http://www.w3.org/2000/svg">
  <path d="M 90 70
           A 56 56, 0, 0, 0, 133 140
           L 150 90 Z" fill="#414042" transform=" scale(2.1) rotate(68 150 150) " />/>
</svg>
```
(Vous pouvez en savoir plus sur [les courbes et les arcs SVG](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths) sur MDN)

_Et voilà ! Ces deux techniques peuvent vous aider à pousser plus loin vos créations de cartes QGIS et à faciliter la création de belles cartographies directement dans QGIS lui-même. Si vous avez trouvé ces conseils utiles, gardez un œil sur ce blog car nous publierons d'autres conseils et astuces au cours du mois de novembre. Et n'oubliez pas de suivre le [30 Day Map Challenge](https://30daymapchallenge.com/) pour découvrir tout un assortiment de cartes absolument époustouflantes._

### Message libre

Une traduction en grande partie grâce à https://www.deepl.com mais avec relecture et en essayant de modifier les phrases qui n'avaient pas de sens en français.
Ce n'est pas parfait mais compréhensible je pense.

J'ai également repris les captures avec les menus pour les mettre avec les menus en français de QGIS.

**Comment by Guts** [comment]
Salut @jeremieprudhomme ,

Merci d'avoir aussi vite répondu à mon appel à traduction ! 
Par contre ce sera plus un article qu'une news pour la RDP :wink:


As-tu essayé le tuto par toi-même sur QGIS ?
Sais-tu créer une Pull Request ou souhaites-tu qu'on la fasse pour toi ?

**Comment by Guts** [comment]
Si tu veux refaire la soumission avec le formulaire d'article --> https://github.com/geotribu/website/issues/new?assignees=aurelienchaumet%2Cguts%2Cigeofr&labels=contribution+externe%2Carticle%2Ctriage&template=ARTICLE.yml

**Comment by jeremieprudhomme** [comment]
Ah mince, je me suis trompé.
Je regarde pour refaire ça.
