### ISSUE TITLE
Nos régions cultivent leur géo-talent

### ISSUE THREAD

**Issue by KazeNoOni** [geotribu/website#758]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui
- [X] Non

### Votre nom

Delphine MONTAGNE

### Votre adresse email

delphine.montagne@univ-pau.fr

### Licence

- [X] J'accepte

### Section / catégorie

Divers

### Mots-clés

carte

### Titre de la news

Nos régions cultivent leur géo-talent

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

Avis aux fans de cucurbitacées ! Pierre Lucas, agriculteur retraité de son état, a fait une carte que vous devriez adorer :
![image](https://user-images.githubusercontent.com/17273438/201370842-c0240717-07d0-4aef-a3dd-41791cacc6bf.png)

Une réalisation hors du #30DayMapChallenge mais tout aussi impressionnante et fascinante par ses couleurs et la diversité des variétés présentées (voir créées !). Pour comprendre le processus agri-créatif, il faut aller lire l'article du journal _Sud Ouest_ qui en fait l'écho, [ici](https://www.sudouest.fr/landes/parleboscq/parleboscq-un-agriculteur-retraite-realise-une-carte-de-france-avec-une-centaine-de-courges-12866503.php).

### Message libre

Pour me mentionner sur Mastodon, c'est avec ce compte tout neuf ! @dmontagne@mapstodon.space

**Comment by Guts** [comment]
Bonsoir Delphine,

News intégrée. Visible ici : https://preview-pullrequest-748--geotribu-preprod.netlify.app/rdp/2022/rdp_2022-11-18/#nos-regions-cultivent-leur-geo-talent

Encore merci !
