### ISSUE TITLE
Virginia T. Norwood

### ISSUE THREAD

**Issue by KazeNoOni** [geotribu/website#763]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui
- [ ] Non

### Votre nom

D.Montagne

### Votre adresse email

delphine.montagne@univ-pau.fr

### Licence

- [X] J'accepte

### Section / catégorie

Divers

### Mots-clés

Wikipédia, Landsat, télédétection, NASA

### Titre de la news

"La mère de Landsat", Virginia T. Norwood, sur Wikipédia

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

On utilise souvent des outils sans connaître les visages qui se cachent derrière. Et pourtant, il fallait un certain sens de l'innovation, de la ténacité et une très grande maîtrise technique pour imposer en 1972 l'envoi dans l'espace du "MSS".

[Virginia T. Norwood](https://fr.wikipedia.org/wiki/Virginia_T._Norwood) a été à la tête du projet de scanner multispectral envoyé dans ce qui est aujourd'hui appelé Landsat 1. Avec son équipe elle a conçu l'un des premiers outils d'observation de la Terre. Enquête utilisateur auprès de très nombreuses spécialités, choix techniques innovants voire audacieux... Les images obtenues ont fait, littéralement, pleurer, les scientifiques devant les possibilités qui étaient à présent ouvertes.

La biographie de [Virginia Norwood](https://fr.wikipedia.org/wiki/Virginia_T._Norwood) est à présent disponible en français sur Wikipédia (relectures bienvenues).

Un parcours découvert grâce à "Briques de géomatique" de Paul Passy, formation mentionnée dans la[ revue de presse](https://static.geotribu.fr/rdp/2022/rdp_2022-02-04/#briques-de-la-geomatique) de février de Géotribu.

https://upload.wikimedia.org/wikipedia/commons/3/38/Landsat-1.jpg 

### Message libre

J'ai traduit et enrichit la page.

**Comment by Guts** [comment]
Merci Delphine d'être toujours aussi productive sur Wikipédia et de prendre en plus le temps de publiciser ce travail notamment sur Geotribu :pray:.

En preview : https://preview-pullrequest-748--geotribu-preprod.netlify.app/rdp/2022/rdp_2022-11-18/#divers

**Comment by KazeNoOni** [comment]
Merci pour ce retour, il fait très plaisir à lire !
