### ISSUE TITLE
Lesley Wyborn

### ISSUE THREAD

**Issue by KazeNoOni** [geotribu/website#784]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui
- [ ] Non

### Votre nom

Delphine MONTAGNE

### Votre adresse email

delphine.montagne@univ-pau.fr

### Licence

- [X] J'accepte

### Section / catégorie

Divers

### Mots-clés

Wikipédia, géologie, open data, big data, FAIR, OGC,GeoSciML

### Titre de la news

Lesley Wyborn, une pionnière de la géoinformatique sur Wikipédia

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

Quand [Lesley Wyborn](https://fr.wikipedia.org/wiki/Lesley_Wyborn) commence sa carrière de géologue en 1972, le temps est au papier, au crayon, aux images aériennes en noir et blanc et aux tableaux de données tapés à la machine à écrire. Or, elle fait partie de ces personnes qui voient tout de suite l'intérêt de l'ordinateur. Elle informatise les données géologiques, les utilise pour des modélisations et des analyses : une pionnière en géoinformatique ! 
Très impliquée dans l'open data, elle contribue à la norme GeoSciML qui encode, manipule et permet l'échange des données géographiques sur la géologie. Ce travail fait émerger de très nombreuses données interopérables entre elles, ouvrant la voie au big data et à l'intelligence artificielle en géologie.
Des réalisations parmi beaucoup d'autres, à découvrir dans [sa biographie sur Wikipédia](https://fr.wikipedia.org/wiki/Lesley_Wyborn) à présent disponible en français.

### Message libre

J'ai traduit et enrichi cette page

**Comment by Guts** [comment]
Bon le robot de réponse auto est pété mais ta news est intégrée !

Merci encore !

**Comment by Guts** [comment]
Oh et j'ai gardé les flocons pour cette RDP aussi vu que ça semblait te plaire ;)

**Comment by Guts** [comment]
Désolé pour le bruit mais je pouvais décemment pas aller me coucher sans avoir corrigé le répondeur automatique :D
