### ISSUE TITLE
Nana Bolašvili

### ISSUE THREAD

**Issue by KazeNoOni** [geotribu/website#805]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui
- [ ] Non

### Votre nom

Delphine MONTAGNE

### Votre adresse email

delphine.montagne@univ-pau.fr

### Licence

- [X] J'accepte

### Section / catégorie

Divers

### Mots-clés

Wikipédia, atlas, carte

### Titre de la news

Cartographie des risques et atlas de la Géorgie : Nana Bolašvili

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

ნანა ბოლაშვილი ([Nana Bolašvili](https://fr.wikipedia.org/wiki/Nana_Bola%C5%A1vili)) est une géographe de Géorgie, comme on peut s'en douter en lisant son nom dans sa langue natale. Le géorgien s'écrit avec l'alphabet "mkhedruli" si bien que tous les atlas publiés en Géorgie, et reconnus pour leur qualité, étaient incompréhensibles pour le public occidental. Or, durant son parcours, Nana Bolašvili a étudié de manière avancée l'anglais. Ce qui, avec ses études en hydrologie, fait d'elle la personne parfaite pour diriger la traduction, la mise à jour et l'enrichissement de _L'atlas de la Géorgie_ en anglais. En temps que spécialiste des structures karstiques - elle a dirigé l'inventaire SIG détaillé des grottes de Géorgie - et de l'hydrologie de Géorgie -la base de données est aussi un de ses projets-, elle a grandement contribué à ces parties de l'atlas. L'[ensemble de ses réalisations est à découvrir sur Wikipédia](https://fr.wikipedia.org/wiki/Nana_Bola%C5%A1vili), grâce à sa traduction en langue française (mais la version géorgienne est aussi disponible pour les curieux et les curieuses !).

### Message libre

J'ai traduit et enrichit cette biographie.

**Comment by Guts** [comment]
Bonne année @KazeNoOni :)

Merci pour cette news. Intégrée dans la preview : https://preview-pullrequest-788--geotribu-preprod.netlify.app/rdp/2023/rdp_2023-01-06/
