### ISSUE TITLE
Retrospective 30DayMapChallenge

### ISSUE THREAD

**Issue by gounux** [geotribu/website#810]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui
- [ ] Non

### Votre nom

Guilhem Allaman

### Votre adresse email

contact@guilhemallaman.net

### Licence

- [X] J'accepte

### Section / catégorie

Geo-event

### Mots-clés

30DayMapChallenge

### Titre de la news

Retour vers le futur du 30DayMapChallenge

### Icône de la news

https://img.youtube.com/vi/IQpPJ8_ks6Y/0.jpg

### Contenu de la news

En novembre dernier a eu lieu le **#30DayMapChallenge**. À cette occasion, les geotribuns n'avaient pas manqué d'aborder [en long](/rdp/2022/rdp_2022-10-21/#cest-bientot-le-30daymapchallenge) et [en large](/rdp/2022/rdp_2022-11-18/#30daymapchallenge) la tenue de cet évènement, apprécié et attendu de longue date par la communauté géo. Sous forme de défis ludiques et joviaux, pour sa 4e édition, le 30DayMapChallenge propose un principe plutôt simple: en Novembre, **30** jours pour réaliser **30** cartes en suivant **30** thèmes. Ce qui, au doigt mouillé, revient à 1 sujet quotidien que doivent suivre les cartes postées sur le mot dièse, sans bémol ni fausse note, et ce tout au long des 30 jours que compte Novembre. D'ailleurs, il serait futile de noter que si le 30DayMapChallenge se déroulait en [février](https://fr.wikipedia.org/wiki/Ann%C3%A9e_bissextile#R%C3%A8gle_actuelle) ou en [décembre](https://www.senscritique.com/bd/32_decembre_La_Tetralogie_du_monstre_tome_2/193399), il porterait probablement un autre nom, toutes choses égales par ailleurs. Mais avec des si on mettrait Paris en bouteille, ce qui aurait cependant l'avantage de mettre certain.e.s au sec ces temps-ci...

Les [sujets](https://raw.githubusercontent.com/tjukanovt/30DayMapChallenge/main/images/flyers/30dmc-2022.png) sont annoncés quelques semaines à l'avance, et l'idée est de s'amuser, de prendre du plaisir: le choix des outils utilisés est libre, même chose pour les données, et ceci sans se prendre la tête: c'est pas une compétition et peu ou pas d'[obligations contractuelles](https://30daymapchallenge.com/#code-of-conduct). Ni quelconque autre obligation prérogativement et forfaitairement majorée au travers d'un droit de regard et de rétractation ultérieurement rétroactivable, amenant de facto à établir une période d'annuités flemmatoires prévue et pré-établie au devant de pénalités unilatéralement puis rétro-antérieurement dépénalisantes eu égard, à fortiori, aux prérogatives duement susmentionnées en alinéa 7 du paragraphe 34 de la troisième annexe des conditions générales d'un engagement manifestement non-contractuel, au demeurant.

Le but et les aspirations du #30DayMapChallenge sont multiples (liste contractuellement non-exhaustive) : célébrer les cartes, promouvoir la cartographie auprès du plus grand nombre, explorer la diversité de la communauté, applaudir la maestria et l'entrain des participants quelque soit le niveau d'expertise, s'émerveiller devant l'esthétique de certaines cartes, pouffer devant l'irrévérence de certaines autres, apprendre à maîtriser des nouveaux outils, tartiner de la confiture géoréférencée pour les plus starfoullah d'entre nous, libérer la créativité géospatiale et développer la sensibilité du cartomaniac qui sommeille en chacun de nous... Mais aussi partager avec les autres pour apprendre, découvrir, en connaître un peu plus sur des territoires inconnus et lointains, ou au contraire porter un regard nouveau sur d'autres plus proches et mieux connus... Ou encore rêvasser, s'évader dans des vapes reprojettées tout au long d'un mois de novembre qui se distingue souvent par des feuilles qui se colorent avant de tomber, une météo brumeuse, un spleen saisonnier propice au voyage géographique intérieur... zzz... aAh ! La nostalgie de ce 30DayMapChallenge passé est en train d'atteindre le rédacteur de cette brève qui finit décidément en roue libre ! Peuchère.

Si vous êtes aussi sur le point de vous assoupir, si vous commencez à vous impatienter, les géocuistots s'activent en cuisine pour stimuler les papilles au travers d'un menu qui revient sur cet évènement, composé d'ingrédients toujours frais et de saison. En espérant qu'il vous rassasie et vous permette de tenir jusqu'à novembre prochain.

:earth_americas: en entrée, le site du 30dmc apporte [une belle assiette composée](https://30daymapchallenge.com/2022/), avec son émincé et ses hors-d'œuvres cartographiques aux petits oignons

:earth_asia: en plat principal, Makina Corpus enfourne [le gratin des billets de blog](https://makina-corpus.com/sig-webmapping/retour-30daymapchallenge-2022), qui alterne fines couches de retours d'expériences, crème de la crème des Mapathoniens les plus motivés, le tout saupoudré de nombreux visuels pour relever un plat qui ne manque pas d'épices

:earth_africa: en dessert, la tarte du chef: le 30dmc étant beaucoup suivi chez les amis du Sénégal, c'est pas du flan, un [onctueux retour d'expérience](https://www.youtube.com/watch?v=IQpPJ8_ks6Y) est apporté par Abdou Sene, géoyoutubeur basé à Dakar. Son, image et sucre glace, n'hésitez pas à en redemander: les bienfaits thérapeutiques de la cartographie ne sont plus à démontrer !

En novembre, pas besoin de forcer le trait sur les médicaments, pas besoin d'abuser de géomédecines alternatives: "~~an apple~~ a map a day keeps the doctor away".

Un [café](https://darwinanddavis.github.io/DataPortfolio/30daymapchallenge/) ? [L'addition](https://30daymapchallenge.com/statistics/) ? Un grand remerciement aux nombreux participants, et rendez-vous l'année prochaine ! Ah et aussi : mangez des pommes !

**Comment by Guts** [comment]
Merci @gounux pour ta proposition de news.

As-tu vu d'autres rétrospectives qui mériteraient d'être relayées dans le même élan ? Comme celle de Makina par exemple https://makina-corpus.com/sig-webmapping/retour-30daymapchallenge-2022

**Comment by Guts** [comment]
A noter que depuis la RDP d'octobre que tu mentionnes, il y a eu d'autres news sur le sujet que tu peux retrouver via https://static.geotribu.fr/tags/#30daymapchallenge

**Comment by gounux** [comment]
> Merci @gounux pour ta proposition de news.
> 
> As-tu vu d'autres rétrospectives qui mériteraient d'être relayées dans le même élan ? Comme celle de Makina par exemple https://makina-corpus.com/sig-webmapping/retour-30daymapchallenge-2022

Merci @Guts pour les suggestions du jour, le contenu de la news est modifié en conséquence pour incorporer davantage de retours sur le 30dmc

**Comment by Guts** [comment]
Top @gounux !

A tel point que je me demande si on devrait pas le publier en tant qu'article plutôt qu'en news ? c'est suffisamment touffu et sympa à lire !

**Comment by gounux** [comment]
Bonne idée @Guts, c'est vrai que ça fait un peu long pour une "brève"...

Dans ce cas-là, ça mériterait peut-être une remise en forme avec des paragraphes allégés et des visuels pour illustrer

**Comment by Guts** [comment]
Allez, c'est tipar pour un article !

Oui, tu pourras même intégrer la vidéo youtube https://contribuer.geotribu.fr/guides/video/#youtube

**Comment by Guts** [comment]
T'as besoin d'aide sur le workflow ou c'est OK pour toi ?

**Comment by gounux** [comment]
Article rédigé ici #815 

Cette issue peut être fermée je pense

**Comment by Guts** [comment]
Duplicate of #815
