### ISSUE TITLE
De la géo et de la politique

### ISSUE THREAD

**Issue by gounux** [geotribu/website#813]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui
- [X] Non

### Votre nom

Guilhem Allaman

### Votre adresse email

contact@guilhemallaman.net

### Licence

- [X] J'accepte

### Section / catégorie

Divers

### Mots-clés

geopolitique

### Titre de la news

De la géo et de la politique

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

Montrer la complexité du monde dans des cartes pour mieux l'appréhender, l'analyser, en saisir les rouages et les enjeux : c'est l'ambition de [Yann Paris](https://www.linkedin.com/in/yann-paris-3b9908139/) des *[Cartes du monde](https://twitter.com/CartesDuMonde)*. Ce qu'il s'évertue à réaliser avec brio au travers d'analyses et de réflexions axées géopolitique, sécurité, conflit, crises...

![assassinats journalistes Monde 1992-2022](https://pbs.twimg.com/media/FlORDE7XoAAz3B9?format=jpg&name=small)

Ces analyses pointues s'appuient sur des cartes souvent temporelles et construites avec QGIS, qui incitent les _followers_ à faire travailler leur matière grise. Et aussi colorée, à l'image du style sobre, épuré et percutant de ce matériel cartographique twitté et à retwitter. 

![surpopulation carcérale 2016](https://pbs.twimg.com/media/FmLnPCmX0AESumL?format=jpg&name=small)

**Comment by Guts** [comment]
Merci pour cette proposition de news.

Je connaissais pas. Il ne publie son travail que sur LinkedIn ?

Peux-tu ajouter un visuel peut-être (capture d'écran...) ?

**Comment by Guts** [comment]
@gounux News ajoutée et visible sur la preview ici : https://preview-pullrequest-809--geotribu-preprod.netlify.app/rdp/2023/rdp_2023-01-20/#de-la-geo-et-de-la-politique

**Comment by gounux** [comment]
Bonne question @Guts : je l'ai contacté sur LinkedIn pour lui proposer de contribuer à la rédaction de contenus. Dans l'idée il y est ouvert, sans pouvoir forcément y accorder beaucoup de temps cependant.
Il propose éventuellement de reprendre ou adapter à la marge les contenus qu'il poste régulièrement sur son LinkedIn.
Ce qui m'amène à poser la question suivante au géotamponneur de billets: ses contenus sont-ils geotribu-compatibles ?

**Comment by Guts** [comment]
@gounux  ^

**Comment by gounux** [comment]
@Guts c'est une discussion intéressante qui mériterait d'en parler de vive voix !

Concernant cette news, à mes yeux elle peut être pesée puis emballée

**Comment by Guts** [comment]
> @Guts c'est une discussion intéressante qui mériterait d'en parler de vive voix !

Certainement ! Tu organises ça ? 


> Concernant cette news, à mes yeux elle peut être pesée puis emballée

C'est fait, cf lien preview plus haut.
