### ISSUE TITLE
Retour vers le futur du 30DayMapChallenge

### ISSUE THREAD

**Issue by gounux** [geotribu/website#815]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui
- [X] Non

### Votre nom

Guilhem ALLAMAN

### Votre adresse email

contact@guilhemallaman.net

### Licence

[Beerware (Révision 42)](https://fr.wikipedia.org/wiki/Beerware)

### Titre

Retour vers le futur du 30DayMapChallenge

### Mots-clés

30DayMapChallenge

### Date de publication envisagée

Mardi 17 ou vendredi 20 janvier ?

### Contenu de l'article

:sparkles: En novembre dernier avait lieu le **#30DayMapChallenge** !

![30: remix](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/retrospective_30dmc_2022/30dmc_2022_retro_01_d30.jpg){: loading=lazy}
:world_map: _J30: Remix - source: https://twitter.com/XemartinLaborde/status/1598096950439858177?s=20_

À cette occasion, les :two_women_holding_hands: _[géotribuns](https://static.geotribu.fr/team/)_ :two_women_holding_hands: n'avaient d'ailleurs pas manqué d'aborder [en long](/rdp/2022/rdp_2022-10-21/#cest-bientot-le-30daymapchallenge) et [en large](/rdp/2022/rdp_2022-11-18/#30daymapchallenge) la tenue de cet évènement, particulièrement apprécié par la communauté :world_map:. Un évènement décousu et attendu de longue date, mais pas cousu de fil blanc, bien au contraire : découvrons ensemble les décoctions géoréférencées et autres remèdes cartographiques concoctés par les herboristes véhéments qui ont participé au challenge :herb:

![20: My favourite](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/retrospective_30dmc_2022/30dmc_2022_retro_02_d20.png){: loading=lazy}
:world_map: _J20: "My favourite..." - source: https://github.com/Pecners/30DayMapChallenge_

![4: green](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/retrospective_30dmc_2022/30dmc_2022_retro_03_d4.jpg){: loading=lazy}
:world_map: _J4: Colour Friday: Green - source: https://github.com/aliciaoberholzer/30DayMapChallenge_

:exclamation: Sous forme de défis ludiques, sur un ton jovial, fédérateur, social, sans souci mais malheureusement sans saucisses à l'ail ni halal inch'Allah, et ce pour la quatrième édition maintenant d'une initiative lancée par [Topi Tjukanov](https://github.com/tjukanovt/30DayMapChallenge) qui fournit les sujets, le 30DayMapChallenge propose un principe plutôt simple :

- :three: :zero: jours, pour réaliser
- :three: :zero: cartes, en suivant
- :three: :zero: thèmes, que voici

![thèmes 30dmc 2022](https://cdn.geotribu.fr/img/articles-blog-rdp/30dmc-2022.png){: loading=lazy}

:point_right: Ce qui, au doigt mouillé, revient à environ :one: sujet par jour, one topic for teh day ([one two tri viva la cartographie](https://www.youtube.com/watch?v=MQndYND2s9M)), que doivent suivre les cartes postées sur le achetague, et ce tout au long des 30 jours que compte le mois de [novembre](https://fr.wikipedia.org/wiki/Tom_Novembre).

:calendar: _À ce propos, il pourrait être futile de noter que si le 30DayMapChallenge se déroulait en [février](https://fr.wikipedia.org/wiki/Ann%C3%A9e_bissextile#R%C3%A8gle_actuelle) ou en [décembre](https://www.senscritique.com/bd/32_decembre_La_Tetralogie_du_monstre_tome_2/193399), il porterait probablement un nom différent, toutes choses égales par ailleurs. Mais avec des si on mettrait Paris en bouteille , ce qui aurait cependant l'avantage de mettre certain.e.s au sec en ces temps bien arrosés ... enfin, au niveau de la météo du moins_ #DryJaruany

![28: 3D](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/retrospective_30dmc_2022/30dmc_2022_retro_05_d28.png){: loading=lazy}
:world_map: _J28: 3D - source: https://github.com/dsollberger/30DayMapChallenge_

:sunglasses: Les sujets sont annoncés quelques semaines à l'avance, et l'idée est de s'amuser, de se détendre, de prendre du plaisir. Le choix des [outils](https://30daymapchallenge.com/resources/#tools) utilisés est libre (mais opensource hein quand même svp : vous êtes assurément libres de choisir à condition que votre choix soit le bon ! (Et opensource !)). Idem pour les [données](https://30daymapchallenge.com/resources/#data), avec cependant une consigne à respecter certains jours. Tout ceci sans [se prendre la tête](https://www.youtube.com/watch?v=GPQEl2qf25w) :

![24: fantasy](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/retrospective_30dmc_2022/30dmc_2022_retro_06_d24.png){: loading=lazy}
:world_map: _J24: Fantasy - source: https://github.com/aliciaoberholzer/30DayMapChallenge_

:no_entry: pas de compétition
:underage: pas d'âge légal minimum (ni maximum d'ailleurs)
:cop: (presque) pas d'[obligations contractuelles](https://30daymapchallenge.com/#code-of-conduct)

:pushpin: _Au demeurant, n'est strictement prévue aucune autre obligation prérogativement et forfaitairement majorée au travers d'un droit de regard et de rétractation ultérieurement rétroactivable, amenant de facto à établir stricto sensu une période ad vitam æternam d'annuités flemmatoires prévues et préétablies au devant de pénalités unilatéralement puis rétro-antérieurement dépénalisantes eu égard, [à fortiori](https://www.youtube.com/watch?v=ZTeqM5gciH8), aux prérogatives duement susmentionnées en alinéa 7 du paragraphe 34 de la troisième annexe des [conditions générales](https://www.bonjour404.fr/post/705324721852563456/kffein) d'un engagement manifestement non-contractuel, au demeurant._

![16: minimal](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/retrospective_30dmc_2022/30dmc_2022_retro_07_d16.png){: loading=lazy}
:world_map: _J16: Minimal - source: https://github.com/nrennie/30DayMapChallenge/tree/main/2022_

:sound: Le _#30DayMapChallenge_, c'est aux géomaniacs ce que le _[#harlemshake](https://www.youtube.com/watch?v=iXCl0fY-HfQ)_ ou le _[#wayawayachallenge](https://www.tiktok.com/@mrgoodvibesonly/video/7141041133483871493)_ sont aux ambianceurs. Cette année, le [bruit](https://www.youtube.com/watch?v=l5ozpoOmvNc) et les [décibels](https://www.youtube.com/watch?v=3ag62f8Vr14) mesurés sur les [fréquences métriques](https://30daymapchallenge.com/statistics/) du mot dièse ont pu s'avérer assourdissants, et ce sans aucune fausse note ni bémol à la clef. Les géochefs d'orchestre ont investi la sphère en masse : ils étaient des dizaines de milliers selon les organisateurs, seulement [4326](https://spatialreference.org/ref/epsg/4326/) selon les [CRS](https://fr.wikipedia.org/wiki/Syst%C3%A8me_de_coordonn%C3%A9es_(cartographie)#Les_codes_EPSG) ... On connaît la :notes: !

<iframe width="100%" height="360" src="https://www.youtube-nocookie.com/embed/o-aDbQX2J3E" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

:star2: Les buts et aspirations du #30DayMapChallenge sont multiples :

_(liste contractuellement non-exhaustive et devant être considérée comme pénalement irresponsable devant tout géotribunal)_

![10: a bad map](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/retrospective_30dmc_2022/30dmc_2022_retro_08_d10.png){: loading=lazy}
:world_map: _J10: A bad map - source: https://github.com/dsollberger/30DayMapChallenge_

:large_blue_diamond: célébrer les cartes et tout ce qu'elles représentent
:large_blue_diamond: promouvoir la cartographie auprès du plus grand nombre
:large_blue_diamond: [applaudir](https://www.youtube.com/watch?v=qyHmeySM14k) la participation et l'entrain des participants, peu importe leur niveau d'expertise : novices, confirmés, [maestros](https://www.youtube.com/watch?v=vSzkfPCTV6w)... Tout le monde est chaleureusement bienvenu !
:large_blue_diamond: apprendre à manier et maîtriser des nouveaux outils cartographiques (le plus mieux étant [QGIS](https://www.qgis.org/fr/site/) bien sûr)
:large_blue_diamond: rassembler et explorer [la diversité grandissante](https://www.youtube.com/watch?v=X75ce-CAorU) de la communauté
:large_blue_diamond: s'émerveiller devant l'esthétique que peuvent exprimer les cartes
:large_blue_diamond: pouffer devant l'irrévérence qu'elles peuvent aussi scabreusement afficher
:large_blue_diamond: deviner notre avenir et [nos fortunes diverses](https://www.youtube.com/watch?v=lzGmpqN9zZc) grâce à l'intuition des nombreu.x.ses et talentuese.x.e.es cartomancien.ne.s qui composent la communauté :mage:
:large_blue_diamond: rencontrer les cartes  les plus :fire: de ta région
:large_blue_diamond: lâcher des pouces bleus en masse pour soutenir [les géopotos](https://www.youtube.com/watch?v=zKFqbyDR6M4)
:large_blue_diamond: s'époumoner au milieu du kop des géo-ultras à chaque geste technique réalisé lors de cette rencontre âpre et engagée, que beaucoup considèrent à juste titre comme le _cartografico_ :soccer: 
:large_blue_diamond: te vénérer, Ôh Grand QGIS, Sacré devant l'Éternel, toi le Messie Géospatial Providentiel, pour t'élever [sans sacrifice ni artifice](https://www.youtube.com/watch?v=wr8eVGWUftI) au rang de Dieu des S.I.G. : :dizzy: Séleste :dizzy: Immortel :dizzy: Giga-rédempteur
:large_blue_diamond: défendre la liberté d'expression cartographique, soit le droit fondamental, universel et inaliénable à vectoriser [haut et fort](https://www.youtube.com/watch?v=qUYZKXis0BU)
:large_blue_diamond: coordonner la convergence des géoluttes, semer [les graines](https://www.youtube.com/watch?v=x_HhWosCvYc) de la cartorévolte, vectoriser et géoréférencer les barricades puis y monter pour fomenter la QRévolution et instaurer la dictature de l'OpenSourçariat :fist: 
:large_blue_diamond: pitcher [ta map multichannel](https://www.youtube.com/watch?v=NEQ2C7ppWZg), data-driven et customer-minded avec un géo-powerpoint insightful qui impacte ta growth devant tes investors grâce à tes process drivés par ton KPI carto-oriented :bar_chart:
:large_blue_diamond: bouter hors de [ta bbox tricolore](https://www.youtube.com/watch?v=B5To8grqmyQ) les gros méchants cartobarbares et géoimmigrés qui viennent jusque dans tes bras s'en prendre à tes fils et tes compagnes :trollface:
:large_blue_diamond: croiser le fer aux côtés de sigistes tenaces et opiniâtres pour le Beau, le Bon, la Vertu, le Courage, la Vigueur, l'Honneur, la Grandeur, la Noblesse et la Dignité de nos cartes :crossed_swords: 
:large_blue_diamond: tartiner tout le pot de Qonfiture sur la tartine spatiale, pour les plus st4rfoull4h d'entre nous :heart_eyes_cat:
:large_blue_diamond: libérer la créativité, déchaîner l'audace et développer la sensibilité du cartomaniac qui sommeille en chacun de nous, afin de nous élever collectivement dans une transe céleste débouchant sur la lumière d'une totale liberté de pensée géocosmique vers un nouvel âge cartoréminiscent...

![9: space](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/retrospective_30dmc_2022/30dmc_2022_retro_09_d9.png){: loading=lazy}
:world_map: _J9: Space - source: https://github.com/Pecners/30DayMapChallenge_

![9: space](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/retrospective_30dmc_2022/30dmc_2022_retro_10_d9.jpg){: loading=lazy}
:world_map: _J9: Space -  source: https://workworkworkwork.work/2022-30-day-map-challenge_

Mais aussi partager avec les autres pour nous rassembler, apprendre les uns des autres, découvrir, en connaître un peu plus sur des territoires inconnus et lointains, ou au contraire porter un regard nouveau sur d'autres plus proches et mieux connus...

![10: a bad map](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/retrospective_30dmc_2022/30dmc_2022_retro_11_d10.jpg){: loading=lazy}
:world_map: _J10: A bad map - source: https://bbecquet.net/articles/2022/12/30-day-map-challenge/_

Ou encore rêvasser, s'évader dans des vapes reprojettées tout au long d'un mois de novembre qu'on aime aussi pour ses feuilles qui se colorent, puis qui tombent lentement, paisiblement, dans la subtile et douce mélodie d'une Qmétéo venteuse, à l'orée de cîmes convexes et brumeuses que le cartographe observe, plongé dans ses polygones volubiles et vaporeux, le curseur de la souris embué dans le vague, l'esprit embrumé dans des nuages de points suaves, peinant à distinguer avec précision les sommets adjacents des Monts du Cigue qui se dressent lentement, sans projection, à la volée, devant son regard perdu au milieu d'un brouillard humide et diffus dont il a du mal à saisir la bbox, préférant rester blotti dans le spleen saisonnier propice à un voyage cartographique intérieur qui l'envoûte, contre lequel il a du mal à résister... :sleeping: ... 

:zzz: ...

![dWüdN-cdf](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/retrospective_30dmc_2022/30dmc_2022_retro_12_cdf.jpg){: loading=lazy}
_Le Cartographe contemplant une mer de cartes postées lors du #30DayMapChallenge_ - _nov. 2022_ - ig :camera: _[@cspr_dvd_frdrch](https://fr.wikipedia.org/wiki/Caspar_David_Friedrich?wprov=sfla1)_

La nostalgie de ce 30DayMapChallenge passé est en train d'atteindre le rédacteur de cet article qui finit décidément en roue libre !

[Cheh](https://www.youtube.com/watch?v=uUDKfK3R42Q).

[Peuchère](https://www.youtube.com/watch?v=J4PG2Da1AK4).

![1: points](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/retrospective_30dmc_2022/30dmc_2022_retro_13_d1.png){: loading=lazy}
:world_map: _J1: Points - source: https://github.com/YoViajo/30-day-map-challenge/blob/main/2022/README.md_

Si vous êtes aussi sur le point de :sleeping:, ou si vous commencez à :rage:, c'est l'heure du :alarm_clock: !

![1: points](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/retrospective_30dmc_2022/30dmc_2022_retro_14_d1.jpg){: loading=lazy}
:world_map: _J1: Points - source: https://github.com/aliciaoberholzer/30DayMapChallenge_

:cook: Les _géocuistots_ s'activent en cuisine pour stimuler vos papilles, au travers d'un menu certifié ingrédients frais et de saison, qui tente vainement de donner un aperçu des saveurs qu'il a été possible de déguster tout au long de ce challenge succulent et succulé :yum:

_:plate_with_cutlery: En espérant que vous soyasses rassasiés et que ceux-là vous permette de tenir jusqu'à novembre prochain_

![17: A map without a computer](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/retrospective_30dmc_2022/30dmc_2022_retro_15_d17.png){: loading=lazy}
:world_map: _J17: A map without a computer - source: https://github.com/dsollberger/30DayMapChallenge_

:earth_americas: :bento: en entrée, le site du 30dmc apporte [une belle assiette composée](https://30daymapchallenge.com/2022/), avec son émincé finement retwitté et ses hors-d'œuvres cartographiques aux petits oignons

:earth_asia: :curry: en plat principal, [Marine Faucher](https://makina-corpus.com/societe/marine-faucher) et [Édith Maulandi](https://makina-corpus.com/societe/edith-maulandi) de [Makina Corpus](https://makina-corpus.com/) enfournent [le gratin des billets de blog](https://makina-corpus.com/sig-webmapping/retour-30daymapchallenge-2022), qui alterne fines couches de retours d'expérience, crème de la crème des Mapathoniens les plus vénères, le tout saupoudré de nombreux visuels poivrés pour relever encore davantage un plat qui ne manque décidément pas d'épices

:earth_africa: :shaved_ice: pour finir en beauté, le dessert du chef : le 30DMC étant beaucoup suivi en Afrique et particulièrement chez les amis du :senegal:, c'est pas du flan, une [onctueuse rétrospective](https://www.youtube.com/watch?v=IQpPJ8_ks6Y) est servie par [Abdou Sene](https://www.youtube.com/@Geotechdev), expert youtubeur georéférencé à Dakar. On a la chance d'avoir le son, l'image et même le sucre glace !

<iframe width="100%" height="360" src="https://www.youtube-nocookie.com/embed/IQpPJ8_ks6Y" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

:pill: N'hésitez pas à vous resservir : y'en a en rab ! Et les bienfaits thérapeutiques de la cartographie ne sont dorénavant plus à démontrer. En novembre, évitons de creuser le trou de la sécurité spatiale : pas besoin d'user ni d'abuser de cartomédicaments, pas besoin d'ingurgiter ni de se rouler beaucoup de géomédecines alternatives : **"~~an apple~~ a map a day keeps the doctor away"** :mute: :scientist:

![17: a map without a computer](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/retrospective_30dmc_2022/30dmc_2022_retro_16_d17.jpg){: loading=lazy}
:world_map: _J17: A map without a computer - source: https://histocarte.fr/30daymapchallenge-2022/_

:wine_glass: [Un digestif](https://les-artisans-cartographes.fr/30daymapchallenge_2022/) ? [Maxime](https://les-artisans-cartographes.fr/author/maxime/) et [Les Artisans Cartographes](https://les-artisans-cartographes.fr/) descendent à la cave vous chercher ça

:coffee: [Un café](https://darwinanddavis.github.io/DataPortfolio/30daymapchallenge/) ? [Matt Malishev](https://darwinanddavis.github.io/DataPortfolio/) vous le prépare

:rice: [Du sucre](https://neocarto.hypotheses.org/12028) ? [Nicolas Lambert](https://neocarto.hypotheses.org/author/neocarto) de [Néocarto](https://neocarto.hypotheses.org/pourquoi-ce-blog) vous montre où se trouve le sucrier

:page_with_curl: [L'addition](https://30daymapchallenge.com/statistics/) ? Vous réglez comment ? En espèce ? Sans contact ? Allez, c'est bon... c'est offert par [la maison](https://twitter.com/geojulien) :wink:

![2: lines](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/retrospective_30dmc_2022/30dmc_2022_retro_17_d2.png){: loading=lazy}
:world_map: _J2: Lines - source: https://github.com/IcaroBernardes/30DayMapChallenge_

:clap::clap::clap::clap::clap:

Un grand merci et un grand bravo à tous les participants !

En attendant la prochaine édition, n'oubliez pas : mangez des :apple: ! Ou encore mieux : faites des :world_map: !

Et rendez-vous en novembre !

:clap::clap::clap::clap::clap:

![30: remix](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/retrospective_30dmc_2022/30dmc_2022_retro_18_d30.png){: loading=lazy}
:world_map: _J30: Remix - source: https://github.com/Pecners/30DayMapChallenge_

### Auteur

![portrait guilhem allaman](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/retrospective_30dmc_2022/30dmc_2022_retro_author_ga.jpg "portrait guilhem allaman"){: .img-rdp-news-thumb loading=lazy}

:confused: Guilhem Allaman: je suis ingénieur développeur, spécialisé dans les SIG : python, PostGreSQL/PostGIS, QGIS... patati patata... mais parfois malheureusement siggeur profane et immature, à la volée, sans projection fixe, mélomane mégalomaniac et [mets l'ammoniac](https://youtube.com/playlist?list=PL2rP2TUXxhl3u8WY9oi1Jt88Ywc-LqPZ4), sophiste vindicatif et surtout de mauvaise foi, ambiancé mais pas rassasié par ce #30DayMapChallenge, en attendant celui de 2024 avec impatience !

{% include "licenses/beerware.md" %}

**Comment by gounux** [comment]
Voici la proposition d'article rétrospective sur le 30dmc

Il manque encore certains visuels, des cartes qui pourraient avoir la bonne idée d'illustrer les différents paragraphes

**Comment by Guts** [comment]
Top @gounux, tu te sens de faire un fork +  PR (cf https://contribuer.geotribu.fr/articles/workflow/#je-nai-pas-acces-en-ecriture) ou tu préfères qu'on le fasse pour toi ?

**Comment by gounux** [comment]
Merci @Guts, je peux m'en charger

Pour continuer la discussion, on passe au café dans le salon de la PR ? Ou au digestif sinon, chacun ses lubies

**Comment by Guts** [comment]
Oui voilà, rdv dans le grand salon de la PR.

Oh et désolé, mais oublie le pseudonyme c'est contraire à la charte 😉

**Comment by abdou-landroms** [comment]
Amazing. Un style d'écriture appétissant.

**Comment by gounux** [comment]
Suite dans la PR #816 

Cette issue peut être fermée à mes yeux
