### ISSUE TITLE
Consultez OpenStreetMap dans votre terminal avec Mercator

### ISSUE THREAD

**Issue by lbartoletti** [geotribu/website#822]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui
- [X] Non

### Votre nom

Loïc Bartoletti

### Votre adresse email

lbartoletti@tuxfamily.org

### Licence

- [X] J'accepte

### Section / catégorie

OpenStreetMap

### Mots-clés

openstreetmap, tui

### Titre de la news

Consultez OpenStreetMap dans votre terminal avec Mercator

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

Mercator est un nouveau logiciel pour consulter OpenStreetMap, mais… inhabituelle à l'époque moderne : dans un terminal ! 

Inutile, donc indispensable !

Vous pouvez vous le procurer sur la page https://github.com/mrusme/mercator/ et suivre les instructions pour l'installer chez vous.

Pour la navigation, on ne peut faire plus simple : on bouge avec les flèches du clavier (ou les touches de vim pour ceux qui savent), +/- pour gérer le zoom et l'on quitte avec 'q' et voilà.

Il accepte les coordonnées ou le nom des villes en entrée et plusieurs styles. On regrettera juste la taille des pixels...

**Comment by Guts** [comment]
Merci @lbartoletti pour la news

Mais il manque le nom du logiciel et un lien à minima non ?

**Comment by lbartoletti** [comment]
ah ah, en effet... Je modifie le contenu du sujet pour ajouter cela et la magie s'opère ?

En attendant, c'est Mercator : https://github.com/mrusme/mercator/

**Comment by Guts** [comment]
> ah ah, en effet... Je modifie le contenu du sujet pour ajouter cela et la magie s'opère ?

Modifier puis fermer et rouvrir le ticket.

**Comment by Guts** [comment]
News ajoutée et visible dans la preview : https://preview-pullrequest-809--geotribu-preprod.netlify.app/rdp/2023/rdp_2023-01-20/#openstreetmap

A noter que je me suis permis quelques ajouts et ajustements. Hésites pas revenir dessus ou à m'ordonner de remettre la version originale si jamais ça ne te conviendrait pas ;)
