### ISSUE TITLE
De l'éc(h)o pour de la carto et des technos à Nantes en mars prochain

### ISSUE THREAD

**Issue by gounux** [geotribu/website#824]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui
- [X] Non

### Votre nom

Guilhem Allaman

### Votre adresse email

contact@guilhemallaman.net

### Licence

- [X] J'accepte

### Section / catégorie

Geo-event

### Mots-clés

exposition géographie écologie technologies

### Titre de la news

De l'éc(h)o pour de la carto et des technos à Nantes en mars prochain

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

En mars prochain aura lieu à Nantes la Convention _[Atelier des prochains mondes](https://convention-apm.com/convention)_, organisée par l'APM (_Association Progrès du Management_), qui invite dirigeants et responsables à réfléchir et poser les bases d'un avenir à la croisée des mondes intimes, collectifs et sociétaux.

Lors de cette convention, les participants pourront découvrir une exposition concoctée par [Maxime Blondeau](https://maximeblondeau.com/), enseignant, conférencier et entrepreneur: "En croisant géographie et écologie, j'interroge nos imaginaires et nos conceptions du territoire sous l'influence de la technologie. Après avoir travaillé sur le futur du voyage en 2022, j'exposerai en mars prochain une composition de cartes, d'images et de textes dans le but de questionner notre perception de l'espace et du temps." _(plus d'infos [sur Linkedin](https://www.linkedin.com/posts/maxime-blondeau-%F0%9F%8C%B1-%E2%99%BE-a71b6521_nantes-midjourney-verne-activity-7015965007372812288-FnjF?utm_source=share&utm_medium=member_desktop) ou sur [son Twitter](https://twitter.com/blondeaumaxim))_"

**Comment by Guts** [comment]
Merci Guilhem.

News ajoutée et visible sur la preview : https://preview-pullrequest-809--geotribu-preprod.netlify.app/rdp/2023/rdp_2023-01-20/#geo-event
