### ISSUE TITLE
Carte des cyberattaques déclarées auprès d’organismes publics.

### ISSUE THREAD

**Issue by lbartoletti** [geotribu/website#825]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui
- [X] Non

### Votre nom

Loïc Bartoletti

### Votre adresse email

lbartoletti@tuxfamily.org

### Licence

- [ ] J'accepte

### Section / catégorie

Open Data

### Mots-clés

cyberattaque, umap

### Titre de la news

Carte des cyberattaques déclarées auprès d’organismes publics.

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

L'association DECLIC vous propose une revue de presse cartographique des cyberattaques subies par les collectivités territoriales, les intercommunalités, les départements, les régions, les établissements de santé et les SDIS depuis 2019.

http://umap.openstreetmap.fr/fr/map/attaques-cybersecurite-aupres-dorganismes-publics_821557#2/19.6/33.4

**Comment by Guts** [comment]
Il manque le lien vers la revue de presse non ?  ou bien c'est juste la carte ?

**Comment by lbartoletti** [comment]
Tu veux dire que cela a déjà été posté dans une RDP ?

**Comment by igeofr** [comment]
Je pense qu'il y a confusion sur le thème RDP, @Guts fait référence à une revue de presse que pourrait faire l'asso Déclic comme le fait GeoTribu alors qu'ici tu fais plutôt référence à l'analyse de la presse concernant les cyber-attaques.

**Comment by Guts** [comment]
News ajoutée et visible dans la preview : https://preview-pullrequest-809--geotribu-preprod.netlify.app/rdp/2023/rdp_2023-01-20/#open-data
