### ISSUE TITLE
Relevés terrain dans QGIS avec le plugin **ETL connector for ODK**

### ISSUE THREAD

**Issue by gounux** [geotribu/website#829]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui
- [X] Non

### Votre nom

Guilhem Allaman

### Votre adresse email

contact@guilhemallaman.net

### Licence

- [X] J'accepte

### Section / catégorie

Logiciel

### Mots-clés

ODK QGIS ETL

### Titre de la news

Relevés terrain dans QGIS avec le plugin **ETL connector for ODK**

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

À l'automne dernier a été publié un nouveau plugin QGIS: [ETL connector for ODK](https://plugins.qgis.org/plugins/odkconnector2/).

![logo plugin ETL connector for ODK](https://cdn.geotribu.fr/img/articles-blog-rdp/logo_etl_connector_for_odk.png)

Bon, cette news n'est décidément pas très fraîche ni de saison. Cependant, pour ce plugin, pas de date de péremption à l'horizon: il permet de charger dans QGIS des données en provenance d'un serveur [ODK](https://getodk.org/), et donc de pouvoir visualiser sur son poste de travail ses relevés terrain collectés avec l'application [ODK Collect](https://play.google.com/store/apps/details?id=org.odk.collect.android&hl=fr&gl=FR). Pour ensuite être en mesure de retraiter, réaliser des mappings, des exports et tout le post-traitement possible que permet nativement QGIS.

Maintenu par [Derrick Demeveng](https://github.com/DemevengDerrick/ETL-Connector-for-ODK), le plugin [ETL connector for ODK](https://demevengderrick.gitbook.io/etl-connector-for-odk/) est publié sous licence [GNU GPLv3](https://www.gnu.org/licenses/quick-guide-gplv3.fr.html).

P.S.: un [article avait été publié en 2021](/articles/2021/2021-06-08_odk_postgis_1/) à ce sujet sur les ondes de geotribu. Cet article, très complet et en trois volets, explique le projet ODK, et montre comment effectuer des relevés terrain en combinant le système ODK à une base PostGIS.

**Comment by Guts** [comment]
Merci. News ajoutée et visible dans la preview : https://preview-pullrequest-809--geotribu-preprod.netlify.app/rdp/2023/rdp_2023-01-20/#logiciel

Légère reformulation, à ta guise pour repasser derrière moi.
