### ISSUE TITLE
Afrocarto à la Villette

### ISSUE THREAD

**Issue by gounux** [geotribu/website#830]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui
- [X] Non

### Votre nom

Guilhem Allaman

### Votre adresse email

contact@guilhemallaman.net

### Licence

- [X] J'accepte

### Section / catégorie

Divers

### Mots-clés

afrofunk carto lagos FelaKuti 

### Titre de la news

Afrocarto à la Villette

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

Jusqu'au 11 juin prochain se tient à la Cité de la Musique de Paris une [exposition retrospective](https://philharmoniedeparis.fr/fr/activite/exposition/24616-fela-anikulapo-kuti) sur [Fela Kuti](https://fr.wikipedia.org/wiki/Fela_Kuti).

![Carte Lagos expo Fela Kuti Cité de la Musique](https://cdn.geotribu.fr/img/articles-blog-rdp/lagos_cite_de_la_musique_fela_kuti.jpg)

Au travers de chaudes archives musicales, photographiques et parfois aussi cartographiques, l'expo rend hommage, raconte l'héritage universel et l'influence du [Black President](https://www.youtube.com/watch?v=IQBC5URoF0s) et de sa [Kalakuta Republic](https://fr.wikipedia.org/wiki/R%C3%A9publique_de_Kalakuta), un lieu de vie et de réflexions libre et engagé, qui habite et questionne les manières de vivre son territoire: la tumultueuse et tentaculaire Lagos, que le visiteur a aussi l'occasion de découvrir.

**Comment by gounux** [comment]
Le contenu de la news a été modifié (dans la description de l'issue) pour y apporter (un peu) plus de sérieux

**Comment by gounux** [comment]
Cette news a peut-être plutôt sa place dans la catégorie "divers" je pense

**Comment by Guts** [comment]
> Le contenu de la news a été modifié (dans la description de l'issue) pour y apporter (un peu) plus de sérieux

En effet, c'était un peu trop fantasque pour que le lectorat ne se sente pas perdu.

**Comment by Guts** [comment]
News ajoutée et visible sur la preview : https://preview-pullrequest-809--geotribu-preprod.netlify.app/rdp/2023/rdp_2023-01-20/#divers

J'ai légèrement reformulé pour ajouter une respiration dans la phrase qui était unique. N'hésites pas à revenir sur ma modification.
