### ISSUE TITLE
GeoNetwork-UI et l'application Datahub

### ISSUE THREAD

**Issue by jahow** [geotribu/website#832]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui
- [ ] Non

### Votre nom

Olivia GUYOT

### Votre adresse email

olivia.guyot@camptocamp.com

### Licence

- [X] J'accepte

### Section / catégorie

Open Data

### Mots-clés

geonetwork, data, catalogage, open data

### Titre de la news

GeoNetwork-UI et l'application Datahub

### Icône de la news

Page d'accueil du Datahub de Géo2France

### Contenu de la news

La version 1.0 de l'application Datahub, partie intégrante de la suite [GeoNetwork-UI](https://github.com/geonetwork/geonetwork-ui), est enfin sortie ! Vous pouvez la retrouver en production ici : https://www.geo2france.fr/datahub/home/news

Le Datahub est une façade accessible et ergonomique pour [GeoNetwork 4+](https://geonetwork-opensource.org/). Facile à déployer, l'application dispose d'un design léché et d'une expérience utilisateur pensée pour être la plus fluide possible. Fil d'actualité, mise en favoris des fiches, options de filtres et de tri intuitives, et même la possibilité de mettre en avant les données de la zone de compétence d'un utilisateur connecté.

Une des forces du Datahub est également d'offrir un accès rapide à la donnée. Un exemple concret avec [la fiche des arrêts de bus de Dunkerque](https://www.geo2france.fr/datahub/dataset/arrets-de-bus) ! Le jeu de donnée décrit par la fiche y est visible sous forme de tableau et de carte si le format de fichier le permet (geojson dans ce cas).

Plus d'information sur les notes de version ici : https://github.com/geonetwork/geonetwork-ui/releases/tag/v1.0.0

Bonne exploration !

![image](https://user-images.githubusercontent.com/10629150/213666211-49a80480-5b99-4c1c-b75b-b28987ac082d.png)

### Message libre

Disclaimer : je travaille pour Camptocamp qui est le principal contributeur de cette solution. Malgré tout GeoNetwork-UI reste une solution communautaire sous le giron du projet GeoNetwork et ne constitue pas un produit de Camptocamp à proprement parler.

Merci pour le super travail sur la GéoRDP, on est tous.tes fans ici !! :slightly_smiling_face:

**Comment by Guts** [comment]
Bonjour et merci Olivia pour la proposition de news,

Ok pour l'intégrer. A noter que @igeofr a déjà évoqué la sortie de GN UI, comme visible dans la preview : https://preview-pullrequest-809--geotribu-preprod.netlify.app/rdp/2023/rdp_2023-01-20/#geonetwork-ui

Je vais pousser un (+/- savant) mélange des deux textes, celui-ci étant bein plus complet mais Florian, je te laisse juger et trancher.

**Comment by jahow** [comment]
Oups, effectivement j'ai été devancée ! Merci de la prendre quand même en compte, pas de souci pour mélanger les deux !

**Comment by Guts** [comment]
News mixée et ajoutée. Visible dans la preview dans quelques minutes : https://preview-pullrequest-809--geotribu-preprod.netlify.app/rdp/2023/rdp_2023-01-20/#sorties-de-la-semaine
