### ISSUE TITLE
Regardez un match de foot dans Google Maps

### ISSUE THREAD

**Issue by benoitblanc** [geotribu/website#833]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui
- [X] Non

### Votre nom

Benoît Blanc

### Votre adresse email

benoit.blanc@oslandia.com

### Licence

- [X] J'accepte

### Section / catégorie

Divers

### Mots-clés

football, Google Maps

### Titre de la news

Regardez un match de foot dans Google Maps

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

A l'occasion du hackathon [Google Maps Platform](https://googlemapsplatform.devpost.com) organisé par DevPost en Novembre 2022, [Orhun Özer](https://twitter.com/orabazu), [Kaan Kalkan](https://twitter.com/kaankalkan) et [Hüseyin Çapan](https://twitter.com/huseyin_capan) ont développé une application de visualisation de données de football en utilisant Google Maps. On peut voir à l'aide de l'application les différents événements qui ont eu lieu lors d'un match (passes, tirs, positions des joueurs, etc...) en 2,5D. Les données proviennent du fournisseur [StatsBomb](https://statsbomb.com/) qui met régulièrement des matchs de compétitions internationales en open-data (par exemple, dernièrement la [coupe du monde 2022 masculine](https://statsbomb.com/news/statsbomb-release-free-2022-world-cup-data/)).

Un des auteurs de l'application explique dans un fil Twitter la démarche pour arriver à ce résultat, notamment pour transformer les coordonnées x, y provenant du fournisseur de données StatsBomb à des coordonnées géographiques pour les afficher sur la carte. En plus de l'API Google Maps, les bibliothèques Deck.gl et Three.js sont utilisées pour l'affichage des événements et du score. Des fonctionnalités plus avancées sont aussi disponibles pour pousser l'analyse du match un peu plus loin : la construction d'un réseau de passes (*pass network*), la création de clusters de passes avec *K-means*, ou encore une grille de probabilité de passes d'une équipe.

<blockquote class="twitter-tweet" data-lang="fr" data-dnt="true" data-theme="light"><p lang="en" dir="ltr">Our recent project with <a href="https://twitter.com/kaankalkan?ref_src=twsrc%5Etfw">@kaankalkan</a> and <a href="https://twitter.com/huseyin_capan?ref_src=twsrc%5Etfw">@huseyin_capan</a> has won the top prize in <a href="https://twitter.com/googlemaps?ref_src=twsrc%5Etfw">@googlemaps</a> Platform Hackaton organized by <a href="https://twitter.com/devpost?ref_src=twsrc%5Etfw">@devpost</a> Here is some technical explanation of what we did including source code 👇🏻🧵</p>&mdash; Orhun Özer (@orabazu) <a href="https://twitter.com/orabazu/status/1600146250313371648?ref_src=twsrc%5Etfw">6 décembre 2022</a></blockquote>

Le code de l’application est disponible sur [Github](https://github.com/orabazu/kicky) et une démonstration est accessible [ici](https://kicky.club/) si vous voulez vous amuser à voir des matchs passés (presque) comme si vous étiez au stade !

![Aperçu des passes réalisées par une équipe dans le stade de Wembley](https://user-images.githubusercontent.com/8960009/213764222-127fcf34-7356-4b0d-b208-fbe6aeb55bb4.png)

### Message libre

Je parle de cette application car je suis fan de :soccer: et que j'ai vu cela dans ma timeline Twitter, mais en regardant les résultats du hackathon, il y a des dizaines d'applications qui vaudraient le coup d'oeil ! Il existe peut-être d'autres hackathons sur des librairies OS...

Désolé pour la contribution en dernière minute et merci pour le partage de tous ces contenus !

**Comment by benoitblanc** [comment]
Hmpg, j'ai oublié le lien du dépôt Github... https://github.com/orabazu/kicky , est-ce que l'édition du commentaire est prise en compte ?

**Comment by benoitblanc** [comment]
Merci, j'en ai profité pour ajouter un mot sur la provenance des données

**Comment by Guts** [comment]
Merci @benoitblanc !

News ajoutée et visible dans quelques minutes sur la preview : https://preview-pullrequest-809--geotribu-preprod.netlify.app/rdp/2023/rdp_2023-01-20/#divers
