### ISSUE TITLE
Un petit bol d'air frais avec l'appli AirParif

### ISSUE THREAD

**Issue by gounux** [geotribu/website#838]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui
- [X] Non

### Votre nom

Guilhem ALLAMAN

### Votre adresse email

contact@guilhemallaman.net

### Licence

- [X] J'accepte

### Section / catégorie

Sorties de la semaine

### Mots-clés

airparif API air observatoire WMS

### Titre de la news

Un petit bol d'air frais avec l'appli AirParif

### Icône de la news

https://cdn.geotribu.fr/img/logos-icones/airparif.png

### Contenu de la news

Il y a quelques jours a été publiée [la nouvelle application mobile](https://www.airparif.asso.fr/actualite/2023/nouvelle-application-mobile-airparif) de AirParif, [l'observatoire de la qualité de l'air en Ile-de-France](https://www.airparif.asso.fr/). Qui s'appuyant sur son réseau de 70 stations de mesure disposées dans toute la région, a pour but de surveiller, prévenir et informer la population sur cette problématique de santé publique.

Disponible sur les principaux stores, la nouvelle appli permet de visualiser les niveaux des différents polluants mesurés : ozone O3, dioxyde d'azote NO2, particules fines PM10 et PM2.5, un niveau global aussi. Ceci au travers de cartes et d'indicateurs qui vulgarisent et donnent au profane des indications simples et colorées de la qualité de l'air :

![capture d'écran appli AirParif carte qualité de l'air](https://cdn.geotribu.fr/img/articles-blog-rdp/airparif_carte_qualite.png)

L'appli permet également de consulter les prévisions à court-terme et les alertes à venir. Elle embarque aussi des ressources pédagogiques pour mieux comprendre les risques et moyens d'actions sur la qualité de l'air, de même que les fonctionnalités de l'ancienne appli _Initiner'AIR'_ : calculer son exposition aux polluants lors de ses trajets en vélo, lors de ses ballades (dominicales ou non), lors de ses joggings (quotidiens ou non) :

![capture d'écran appli AirParif calcul niveau itinéraire](https://cdn.geotribu.fr/img/articles-blog-rdp/airparif_initerair.png)

Partiellement refondue afin d'alimenter cette nouvelle appli, l'[API AirParif](https://airparif.fr/interface-de-programmation-applicative) fournit sous [licence ODbL](https://fr.wikipedia.org/wiki/Open_Database_License) les données visibles dans l'appli : niveaux des polluants, prévisions, alertes, mais aussi des [flux WMS/WCS "temps réel"](https://www.airparif.fr/sites/default/files/docs-api/API_WMS_Cartes_Temps_Reel.pdf). Pour consommer ces données, il est nécessaire de remplir le formulaire, ce après quoi AirParif transmet une clé d'accès à l'API de même que la documentation.

Comme on dit en région parisienne : tu me pompes l'air !

### Message libre

J'ai essayé de chercher le service de routing utilisé par l'appli AirParif pour calculer les itinéraires. Après n'avoir pas trouvé grand chose de concluant, je me demande si ce n'est pas le routing de MapBox qui est utilisé.
Il ne faut pas hésiter à compléter si vous en sachez plus à ce sujet

**Comment by Guts** [comment]
Merci pour la news @gounux. Je viens de l'ajouter à la prochaine RDP.

Je n'ai pas trouvé d'infos sur le service d'itinéraire mais s'ils utilisent le SDK MapBox il y a fort à parier que ce soit leur routing également.


Quelques remarques pour les images :

- quand ce sont des captures d'écran, plutôt ce sous-dossier : https://cdn.geotribu.fr/tinyfilemanager.php?p=articles-blog-rdp%2Fcapture-ecran
- quand il s'agit d'images "verticales", on applique une hauteur max entre 500 (idéalement si ça gâche pas la lisibilité) et 800
