### ISSUE TITLE
Cartoradio, une carte à ne pas réchauffer au micro-ondes

### ISSUE THREAD

**Issue by gounux** [geotribu/website#859]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui et je détaille dans quelle mesure dans la partie commentaire libre
- [ ] Non

### Votre nom

Guilhem ALLAMAN

### Votre adresse email

contact@guilhemallaman.net

### Licence

- [X] J'accepte

### Compte LinkedIn

https://www.linkedin.com/in/guilhemallaman/

### Compte Mastodon

https://mapstodon.space/@gounux

### Section / catégorie

Open Data

### Mots-clés

cartoradio ANFR radiofréquences antennes téléphoniemobile 4G 5G géoportail

### Titre de la news

Cartoradio, une carte à ne pas réchauffer au micro-ondes

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

[Cartoradio](https://www.cartoradio.fr/#/cartographie/lonlat/2.315393/48.872745) est un outil cartographique mis en place par l'[ANFR](https://www.anfr.fr/accueil), l'_Agence Nationale des Fréquences_. Dans l'optique de renforcer la transparence et l’indépendance du financement des mesures d’exposition aux ondes électromagnétiques, l'ANFR référence et publie sur _Cartoradio_ :

- l'emplacement et les caractéristiques de sites émetteurs de radiofréquences (soit les antennes qui émettent à plus de 5 watts, exceptées celles de l'Aviation Civile et celles de la Défense). Les opérateurs sont tenus de déclarer les nouveaux émetteurs installés, et ce sur différentes bandes de fréquences: téléphonie mobile (2G/3G/4G/5G...), faisceaux hertziens, radio FM, TNT, WiMAX, goniométrie, réseaux PMR, GSM-R, POCSAG...

- les mesures d'exposition aux ondes réalisées sur tout le territoire français (métropole et DROM), par des bureaux d'études accrédités et suivant [un protocole COFRAC](https://www.cofrac.fr/fileadmin/user_upload/Fiche_ondes_electromagnetiques.pdf) que l'ANFR [a récemment renouvelé et mis à jour](https://www.anfr.fr/liste-actualites/actualite/renouvellement-de-laccreditation-cofrac-du-laboratoire-de-lanfr-pour-la-mesure-de-lexposition-aux-ondes-electromagnetiques). La position précise, les résultats et un compte-rendu public en PDF sont disponibles pour chaque mesure réalisée

![cartoradio](https://cdn.geotribu.fr/img/articles-blog-rdp/cartoradio.png)

A noter que [Cartoradio](https://www.anfr.fr/fileadmin/mediatheque/documents/expace/Anfr_BrochureGenerale_pap_0411.pdf) utilise l'outil Géoportail de l'IGN. Il est également possible d'exporter les données en CSV, et ce directement depuis le site de Cartoradio. Sans oublier bien sûr les données publiées par l'ANFR sur [data.gouv.fr](https://www.data.gouv.fr/fr/organizations/agence-nationale-des-frequences/). Ni la [foire aux questions du site de l'ANFR](https://www.anfr.fr/maitriser/information-du-public/cartoradio/questions-/-reponses), qui peut permettre de mieux comprendre certains aspects des champs électromagnétiques, un domaine d'expertise auquel le grand public est de plus en plus exposé mais dont la recherche scientifique et [médicale](https://www.anses.fr/fr/content/les-ondes-%C3%A9lectromagn%C3%A9tiques) n'en est qu'à ses débuts...

Alors si vous cherchez un coin au vert où passer vos prochaines vacances, à l'abri des ondes, ou si au contraire vous voulez savoir où il y a le plus de 5G pour _regarder des pronos dans l'ascenseur en HD_ : n'hésitez pas à y zieuter un coup !

### Message libre

Je travaille pour un bureau d'études spécialisé dans les champs électromagnétiques, qui est mandaté par l'ANFR pour réaliser des mesures de champs. Je peux donc avoir un intérêt indirect à faire la promotion de l'ANFR et de ses sous-traitants, même si à mes yeux _Cartoradio_ est un site utile et intéressant, à porter à la connaissance du plus grand nombre d'où cette suggestion de news (une initiative personnelle et dont le bureau d'études n'est pas au courant)

**Comment by Guts** [comment]
Merci @gounux !

C'est intéressant car j'ai reçu le magazine n°4 de Next INpact cette semaine et il y a un dossier sur l'ANFR et son service permettant à tout un chacun et aux collectivités de déclencher une mesure gratuitement et qui enrichit à terme cartoradio : https://mesures.anfr.fr/#/

> e travaille pour un bureau d'études spécialisé dans les champs électromagnétiques, qui est mandaté par l'ANFR pour réaliser des mesures de champs.

Tu bosses avec Exem ?

**Comment by Guts** [comment]
@gounux quelques remarques :

- l'image est trop lourde (1,6 Mo pour une capture d'écran), loin des recommandations
- c'est une capture d'écran donc zou dans le dossier captures d'écran :wink:

**Comment by gounux** [comment]
Salut @Guts 

> service permettant à tout un chacun et aux collectivités de déclencher une mesure gratuitement et qui enrichit à terme cartoradio : https://mesures.anfr.fr/#/

Oui effectivement, il est possible de demander une mesure "gratuite" à l'ANFR, qui va ensuite missionner des bureaux d'études pour les réaliser. Ce marché est découpé en 7 lots, confiés potentiellement à des BE différents : découpage de la métropole en 6 zones + DROM. J'hésitais à mettre une mention à ça dans la news mais je trouve que c'est un peu trop du forçage..


> Tu bosses avec Exem ?

Non ce n'est pas Exem, c'est un autre qui s'appelle Simutech-UAE (pas de corrélation avec Abu Dhabi :D)


> J'ai fait le taf (l'image pèse désormais 75 Ko), mais si tu peux ajuster pour le prochain coup, je t'en paye un ! :pray: 

Arf, désolé, c'est pas la première fois en plus... Merci ! C'est plutôt moi qui t'en dois une ;)
