### ISSUE TITLE
Vera Baltz

### ISSUE THREAD

**Issue by KazeNoOni** [geotribu/website#860]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui et je détaille dans quelle mesure dans la partie commentaire libre
- [ ] Non

### Votre nom

Delphine MONTAGNE

### Votre adresse email

delphine.montagne@univ-pau.fr

### Licence

- [X] J'accepte

### Compte LinkedIn

https://fr.linkedin.com/in/delphinemontagne

### Compte Mastodon

@dmontagne@mapstodon.space

### Compte Twitter

@_DMONTAGNE

### Section / catégorie

Divers

### Mots-clés

Wikipédia;pédologie

### Titre de la news

Cartographier le sol : Vera Baltz sur Wikipédia

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

Imaginez : vous faites des études de géologie en URSS que vous réussissez brillamment. Ce qui vous conduit à construire l'exposition permanente d'un musée, à réaliser de nombreux terrains, à construire des routes, faire des recherches passionnantes touchant également à la botanique et à publier dans quatre langues (russe, anglais, allemand et français), puisque vous êtes polyglotte.
Et vous voilà en route pour le goulag pour conspiration contre l’État. Bilan : votre nom est soigneusement effacé de vos contributions. C'est l'histoire de [Vera Baltz](https://fr.wikipedia.org/wiki/Vera_Baltz), l'une des premières pédologues à arriver à ce poste en URSS. Sa biographie est à découvrir [en français sur Wikipédia](https://fr.wikipedia.org/wiki/Vera_Baltz) !

### Message libre

J'ai traduit et enrichit cette page.

**Comment by Guts** [comment]
En effet, Vera tient ses promesses :wink: !

News intégrée

Petite coquille sur la fiche Wikipedia il me semble :

> En septembre de 1941, a est évacuée avec sa famille vers la ville

**Comment by KazeNoOni** [comment]
Une parmi bien d'autres... Merci, c'est depuis corrigé à la relecture du matin. 
Et je te parie que dans un an, j'en trouverai d'abominables autres !
