### ISSUE TITLE
Ingrid Kretschmer

### ISSUE THREAD

**Issue by KazeNoOni** [geotribu/website#868]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui et je détaille dans quelle mesure dans la partie commentaire libre
- [ ] Non

### Votre nom

Delphine MONTAGNE

### Votre adresse email

delphine.montagne@univ-pau.fr

### Licence

- [X] J'accepte

### Compte LinkedIn

https://fr.linkedin.com/in/delphinemontagne

### Compte Mastodon

@dmontagne@mapstodon.space

### Compte Twitter

@_DMONTAGNE

### Section / catégorie

Divers

### Mots-clés

cartographie, Wikipédia

### Titre de la news

Ingrid Kretschmer : une grande dame de la cartographie autrichienne sur Wikipédia

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

[Ingrid Kretschmer](https://fr.wikipedia.org/wiki/Ingrid_Kretschmer) est une personnalité incontournable de la cartographie autrichienne. Autrice d'atlas et d'ouvrages de référence en cartographie, ses travaux portent aussi bien sur la projection de Mercator, la cartographie de l'Afrique par les explorateurs autrichiens ou la manière de représenter le relief sur les cartes. Passionnée par les cartes, elle a également passionné ses élèves, plusieurs générations d'élèves même, puisqu'elle est restée professeure plus de 40 ans à l'université de Vienne. Quand elle n'inventorie pas tous les atlas publiés en Autriche, elle réalise des expositions pour mieux faire connaître la cartographie auprès du grand public. Une vie riche et dense, à découvrir à présent [en français sur Wikipédia](https://fr.wikipedia.org/wiki/Ingrid_Kretschmer) !

### Message libre

Traduction et enrichissement par mes soins.

**Comment by Guts** [comment]
Merci pour la news ! Elle est intégrée et dans les tuyaux :)
