### ISSUE TITLE
Maria Glazovskaïa, géographe du sol

### ISSUE THREAD

**Issue by KazeNoOni** [geotribu/website#879]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui et je détaille dans quelle mesure dans la partie commentaire libre
- [ ] Non

### Votre nom

Delphine Montagne

### Votre adresse email

delphine.montagne@univ-pau.fr

### Licence

- [X] J'accepte

### Compte LinkedIn

https://fr.linkedin.com/in/delphinemontagne

### Compte Mastodon

@dmontagne@mapstodon.space

### Compte Twitter

@_DMONTAGNE

### Section / catégorie

Divers

### Mots-clés

Wikipédia, géologie, sol

### Titre de la news

Maria Glazovskaïa, une légende russe sur Wikipédia

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

Elle est une légende en ~URSS~ Russie et une anonyme en occident. On revient constamment en Russie sur ses idées alors que ses réalisations nous sont inconnues. [Maria Glazovskaïa](https://fr.wikipedia.org/wiki/Maria_Glazovskaïa) est une géographe qui a étudié les sols. Cette courte description est la meilleure pour décrire le foisonnement de ses travaux : étude de la chimie du sol, de la qualité du sol, des micro-organismes du sol, de la réaction des sols face aux pollutions... Et bien sûr, en bonne géographe, cartographie de ces sols : on lui doit avec son équipe une cartographie mondiale des sols à petite échelle. Elle sert aujourd'hui de base dans de nombreux domaines, quand elle n'est pas encore utilisée comme référence. Une vie riche, elle est morte centenaire, et passionnante à découvrir [en français sur Wikipédia](https://fr.wikipedia.org/wiki/Maria_Glazovskaïa).

### Message libre

J'ai traduit et enrichi cette biographie.

**Comment by Guts** [comment]
Merci @KazeNoOni !

News intégrée !
