### ISSUE TITLE
Le Kenya dans l'espace avec Taifa-1

### ISSUE THREAD

**Issue by gounux** [geotribu/website#900]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui et je détaille dans quelle mesure dans la partie commentaire libre
- [X] Non

### Votre nom

Guilhem Allaman

### Votre adresse email

contact@guilhemallaman.net

### Licence

- [X] J'accepte

### Compte LinkedIn

https://www.linkedin.com/in/guilhemallaman/

### Compte Mastodon

@gounux@mapstodon.space

### Section / catégorie

Divers

### Mots-clés

espace kenya satellite observation environnement panchromatique télédétection

### Titre de la news

Le Kenya dans l'espace avec Taifa-1

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

_Taifa-1_, c'est le nom du premier satellite opérationnel mis en orbite par la [Kenya Space Agency](https://ksa.go.ke/taifa-1-satellite/). Conçu par une équipe de chercheurs kényans, le satellite a pour mission de fournir des données d'observation environnementale précises et régulières.

<iframe width="100%" height="415" src="https://www.youtube.com/watch?v=teGxApMA_pI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

Une surveillance écologique et un système d'alerte utiles notamment pour l'agriculture, la sécurité alimentaire et la gestion des ressources, dans l'optique de mieux pouvoir gérer et prévoir les catastrophes naturelles. Car le Kenya, comme ses voisins d'Afrique de l'Est, connait une succession de saisons des pluies préoccupantes, et la sécheresse s'intensifie dans un contexte de hausse des températures moyennes.

Le satellite est équipé d’une caméra capable de prendre des images dans cinq bandes multispectrales, avec une résolution de 32 mètres, 16 mètres pour la bande panchromatique.

Le Kenya est donc le dernier arrivé dans la danse orbitale. En Afrique, c'était l'Egypte qui avait ouvert le bal en 1998, suivie par l’Algérie, l’Angola, le Ghana, le Nigeria, l’Afrique du Sud, le Soudan ou encore le Rwanda, rentrés sur la piste par la suite.

### Message libre

Le lancement était initialement prévu le 10 avril. Puis reporté 1 fois, 2 fois, pour un lancement prévu à l'heure où ces lignes sont écrites le 14 avril. Peut-être serait-il plus judicieux d'attendre que le lancement soit effectué avant de publier la news ?

**Comment by Guts** [comment]
Merci pour la news Guilhem, elle est dans les tuyaux.

> Le lancement était initialement prévu le 10 avril. Puis reporté 1 fois, 2 fois, pour un lancement prévu à l'heure où ces lignes sont écrites le 14 avril. Peut-être serait-il plus judicieux d'attendre que le lancement soit effectué avant de publier la news ?

Ayons foi mon bien cher frère ! Je me suis permis de faire de ton commentaire libre un ajout dans ta news. Dis-moi si ça te convient ou pas.

J'espère que tout se passe bien pour toi de l'autre côté de la Méditerranée :wink:.
