### ISSUE TITLE
carte du bullshitland, BD

### ISSUE THREAD

**Issue by ndavid** [geotribu/website#901]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui et je détaille dans quelle mesure dans la partie commentaire libre
- [X] Non

### Votre nom

Nicolas DAVID

### Votre adresse email

nicolas.david@ign.fr

### Licence

- [X] J'accepte

### Compte LinkedIn

https://www.linkedin.com/in/nicolas-david-28722129/

### Section / catégorie

Représentation Cartographique

### Mots-clés

BD, carte

### Titre de la news

Le bullshit a enfin sa carte

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

Après de multiples livres sur le sujet du *Bullshit* le dessinateur de BD _Fix_ nous livre, à l'occasion de la sortie de sa dernière bande dessinée (Chief Bullshit Officer 2.0), et via son [compte linkedIn](https://www.linkedin.com/feed/update/urn:li:activity:7051811180117417984/) une carte imaginaire de ce pays magnifique qu'est le bullshitland :

![bullshitland](https://user-images.githubusercontent.com/873438/232040623-4f228bd5-59c9-4ecb-abee-8478055f67dd.jpeg)

**Comment by Guts** [comment]
Merci @ndavid pour la proposition de news. Elle est dans les tuyaux et visible dans la preview : https://preview-pullrequest-895--geotribu-preprod.netlify.app/rdp/2023/rdp_2023-04-14/#representation-cartographique
