### ISSUE TITLE
Evoland : projet R&D européen pour l'évolution des couches copernicus

### ISSUE THREAD

**Issue by ndavid** [geotribu/website#902]
### Avez-vous un lien avec le contenu proposé ?

- [ ] Oui et je détaille dans quelle mesure dans la partie commentaire libre
- [X] Non

### Votre nom

Nicolas DAVID

### Votre adresse email

nicolas.david@ign.fr

### Licence

- [X] J'accepte

### Compte LinkedIn

https://www.linkedin.com/in/nicolas-david-28722129/

### Section / catégorie

Divers

### Mots-clés

Sentinel-2, occupation du sol, Europe

### Titre de la news

Evoland : projet R&D pour l'évolution des couches copernicus

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

Le projet européen EVOLAND a été lancé fin janvier et s'intéressera pour les prochaines années a développer et tester des méthodologies de production pour 11 nouveaux prototypes de produits d'occupation du sol s'inscrivant dans l'écosytème "Copernicus Land". Ces dernières données étant diffusées en open-data au niveau européens. 

Le [site de ce projet](https://www.evo-land.eu/) a été mis en ligne récemment. Bien sur il n'y a pas encore de données tests disponibles mais il y a déjà une [description](https://www.evo-land.eu/clms-prototypes/) des futurs produits envisagés ce qui est déjà intéressant à suivre en veille technologique.  

Pour information voici donc la liste des 11 prototypes prévus , regroupés en cinq domaines thématiques : 

##### agriculture
   - Cartographie des cultures de couverture (_Cover crop type mapping_)
   - Suivi de production primaire pour les cultures et prairies à une fréquence de 10 jours (_Cropland/grassland GPP monitoring_)
   - Cartographie des petits élements de paysages, comme les haies, bosquets, mares, murs etc.. (_Small landscape features mapping_)

On voit que ces trois produits agricoles sont orientés, entre autre, vers les besoins pour le suivi de la politique agricole commune. 

##### hydrologie
 - cartographie fine (résolution < 10m) des surfaces et réseau hydrographiques (_Improved water bodies mapping_)

##### forêt
- Cartographie/suivi des événments forestiers commes les coupes, feux de forêt, attaques insectes etc. (_Forest disturbance mapping_)
- Cartographie/estimation de la biomasse dont une couche de hauteur de canopée (_Forest biomass mapping_) 
- Cartographie/suivi de la forêt : augmentation de la fréquence de mise à jour d'un produit comme la couche actuelle [HRL Forest](https://land.copernicus.eu/pan-european/high-resolution-layers/forests). Passage de 3 ans à trois mois (_Continuous Forest monitoring_)

##### urbain
- Cartographie continue de l'imperméabilisation. Il s'agit de produire à haute fréquence une couche similaire à la couche existante [HRL Imperviousness](https://land.copernicus.eu/pan-european/high-resolution-layers/imperviousness) (_Continuous imperviousness monitoring_)
- Automatisation de la production de couche de type [Urban Atlas](https://land.copernicus.eu/local/urban-atlas) pour une mise à jour plus fréquente (_Automated land use mapping of urban dynamics_)

##### occupation du sol
- Cartographie en continue des caractéristiques sur la surface des terres, c'est à dire indicateur de présence/absence avec neige/no-neige; eau/no-eau; végétation/non-végétation (_Continuous mapping of land surface characteristics_)
- Test de cartographie d'occupation des sols à la demande (nomenclature utilisateur) (_On-demand land cover mapping_)

**Comment by Guts** [comment]
Merci @ndavid pour la proposition de news. Elle est dans les tuyaux et visible dans la preview : https://preview-pullrequest-895--geotribu-preprod.netlify.app/rdp/2023/rdp_2023-04-14/#divers

Je me suis permis de transformer les niveaux titres en liste à puces ordonnée car on évite les mises en pages trop élaborées dans les news. Dis-moi si ça te convient ou pas.

**Comment by ndavid** [comment]
pas de soucis pour les modifications titres vers liste à puces. J'ai hésité à le faire aussi mais j'avais un doute sur ce qui été mieux dans le cas des listes imbriquées.
