### ISSUE TITLE
Raquel Soeiro de Brito, cartographe pionnière au Portugal

### ISSUE THREAD

**Issue by KazeNoOni** [geotribu/website#903]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui et je détaille dans quelle mesure dans la partie commentaire libre
- [ ] Non

### Votre nom

Delphine Montagne

### Votre adresse email

delphine.montagne@univ-pau.fr

### Licence

- [X] J'accepte

### Compte LinkedIn

https://fr.linkedin.com/in/delphinemontagne

### Compte Mastodon

@dmontagne@mapstodon.space

### Compte Twitter

@_DMONTAGNE

### Section / catégorie

Divers

### Mots-clés

Wikipédia, carte

### Titre de la news

Raquel Soeiro de Brito, cartographe pionnière au Portugal

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

Elle est la première docteure en géographie au Portugal : [Raquel Soeiro de Brito](https://fr.wikipedia.org/wiki/Raquel_Soeiro_de_Brito) est une scientifique pionnière dans son pays. Elle cartographie, que ce soit dans son pays, on lui doit une importante participation à l'_Atlas du Portugal_, mais aussi au Timor oriental et dans plusieurs colonies portugaises. Et elle filme également, comme l'éruption du volcan Capelinhos. Une vie riche à découvrir en détails sur [sa page Wikipédia](https://fr.wikipedia.org/wiki/Raquel_Soeiro_de_Brito), à présent disponible en français.

### Message libre

J'ai traduit la page (et vais sûrement l'enrichir dans les jours à venir).

**Comment by Guts** [comment]
Merci pour la proposition de news @KazeNoOni. Elle est intégrée et visible dans la prévisualisation : https://preview-pullrequest-895--geotribu-preprod.netlify.app/rdp/2023/rdp_2023-04-14/#divers

**Comment by Guts** [comment]
Je suggère de mentionner son invitation à Clermont-Ferrand peut ajouter de l'intérêt au lectorat francophone de Geotribu. Peut-être sous forme de question pour allécher le chaland ? 

"Saviez-vous qu'elle a bien failli se retrouver à l'université de Clermont-Ferrand ?"

**Comment by KazeNoOni** [comment]
Vendu !
