### ISSUE TITLE
Hêtre, charme : Hanna Czeczott

### ISSUE THREAD

**Issue by KazeNoOni** [geotribu/website#940]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui et je détaille dans quelle mesure dans la partie commentaire libre
- [ ] Non

### Votre nom

Delphine MONTAGNE

### Votre adresse email

delphine.montagne@univ-pau.fr

### Licence

- [X] J'accepte

### Compte LinkedIn

https://fr.linkedin.com/in/delphinemontagne

### Compte Mastodon

@dmontagne@mapstodon.space

### Compte Twitter

@_DMONTAGNE

### Section / catégorie

Divers

### Mots-clés

biodiversité, Wikipédia

### Titre de la news

Hanna Czeczott : voyage dans la phytogéographie

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

Savoir où se répartissent les plantes, c'est la base d'un inventaire de la biodiversité. Savoir comment se répartissent les différentes essences d'arbres, selon un gradient, sur un immense territoire, en s'aidant de statistiques et de méthodes de biométrie, au début du XXe siècle, c'est d'un autre niveau. Mais la polonaise [Hanna Czeczott](https://fr.wikipedia.org/wiki/Hanna_Czeczott) n'est pas connue pour ces travaux de phytogéographie, pourtant innovants à l'époque. Elle s'est intéressée aux plantes qui ont aujourd'hui disparues, la flore fossile, que l'on peut par exemple trouver dans l'ambre. De quoi décrire un espace et un climat bien différents à travers un vrai voyage dans le temps... [A découvrir sur Wikipédia](https://fr.wikipedia.org/wiki/Hanna_Czeczott), où la biographie de cette figure de la paléobotanique est à présent disponible.

### Message libre

J'ai traduit et enrichi cette biographie.
Attention, c'est un peu la folie cette page et, non, je n'ai pas fumé d'herbe en la faisant.

**Comment by Guts** [comment]
Merci @KazeNoOni !

Ajoutée ! https://preview-pullrequest-933--geotribu-preprod.netlify.app/rdp/2023/rdp_2023-06-09/#divers
