### ISSUE TITLE
Allons dans la géo-paix du Christ

### ISSUE THREAD

**Issue by KazeNoOni** [geotribu/website#949]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui et je détaille dans quelle mesure dans la partie commentaire libre
- [ ] Non

### Votre nom

Delphine MONTAGNE

### Votre adresse email

delphine.montagne@univ-pau.fr

### Licence

- [X] J'accepte

### Compte LinkedIn

https://fr.linkedin.com/in/delphinemontagne

### Compte Mastodon

@dmontagne@mapstodon.space

### Compte Twitter

@_DMONTAGNE

### Section / catégorie

Divers

### Mots-clés

Wikipédia,cartographie,changement climatique

### Titre de la news

SIG, église et changement climatique : Molly Burhans

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/news.png

### Contenu de la news

L’Église catholique est le plus grand propriétaire terrien privé au monde. Du moins, c'est ce que disent les estimations car il n'en existe aucune cartographie exhaustive. Enfin, si, dans l'_Atlas Hierarchicus_, publié en 1901... Et il n'était d'ailleurs probablement pas à jour. Sans carte ni données disponibles, comment faire face aux bouleversements à venir dus aux changements globaux et s'y adapter ? C'est dans ce contexte que [Molly Burhans](https://fr.wikipedia.org/wiki/Molly_Burhans) s'est mis en tête de réaliser le premier SIG mondial des propriétés foncières de l'Église catholique. Compilation et numérisation de données existantes, retranscriptions de cartes anciennes, incorporation d'analyses faites maison, ajouts de données environnementales et de prospective... Cette catholique jésuite a petit à petit créé la plus grande base de géolocalisée au monde sur l'Église catholique et réalisé la première carte à cette échelle incorporant des frontières géo-religieuses. Un travail de fourmi qui lui a servi aussi bien pour proposer la prise en compte de l'écologie dans les activités économiques de l’Église que pour suivre les mutations de diocèse en diocèse de prêtres accusés d'abus sexuels. Un travail de géomaticienne, récompensé de nombreux prix, qui lui a ouvert les portes du Vatican et est à découvrir en détail sur [sa page Wikipédia](https://fr.wikipedia.org/wiki/Molly_Burhans), à présent disponible en français.

### Message libre

J'ai traduit et enrichi cette biographie.

**Comment by Guts** [comment]
Merci Delphine, c'est dans les tuyaux !

https://preview-pullrequest-943--geotribu-preprod.netlify.app/rdp/2023/rdp_2023-06-23/#sig-eglise-et-changement-climatique-molly-burhans
