### ISSUE TITLE
Une rubrique meme dans les RDP ?

### ISSUE THREAD

**Issue by gounux** [geotribu/website#951]
Salut l'équipe,

Comment ça va ?

Ces derniers temps j'ai gribouillé quelques :trollface:, en rapport avec les technologies géospatiales. Les webp sont déposés dans le dossier [`articles-blod-rdp/memes/`](https://cdn.geotribu.fr/tinyfilemanager.php?p=articles-blog-rdp%2Fmemes) sur le CDN, si vous voulez y zieuter un coup. Bon, c'est pas toujours du meilleur goût...

Je me dis que ça pourrait être marrant d'en mettre peut-être un à la fin des RDP ? Qu'en pensez-vous ?

**Comment by Guts** [comment]
Salut @gounux ,

Tu as fermé car tu as changé d'avis ?

**Comment by gounux** [comment]
Salut @Guts 

Ah oui l'issue a été fermée, les fenêtres ont du rester ouvertes, sûrement un courant d'air 😲

Oui bien sûr, comme c'est toujours sympa à lire et disons varié et équilibré les RDP, avec des news, des sorties, des évènements, de l'histoire, de la culture, je me permettais de soumettre cette idée, à discuter bien sûr. En tout cas s'il y a des idées à mettre sur "papier" je suis là 🤙🤟😉

**Comment by Guts** [comment]
Un courant d'air de doute et de "pas sûr d'assumer" :smirk: ?

Pour te donner mon avis rapidement :

- je suis pas fan de la mr propre (que mon avis hein)
- en termes d'humour et de mème, je pense qu'il faut essayer de s'en tenir à 1 mème/image = 1 vanne et éviter de multiplier les vannes et sous-vannes sur la même image (sinon ça prend plus de 2 sec à décryter et comprendre)
- proposer une structure type pour faciliter l'intégration dans la RDP (nom de section dédié, hashtag, etc.)

**Comment by gounux** [comment]
> Un courant d'air de doute et de "pas sûr d'assumer" :smirk: ?

:smirk: !!

> je suis pas fan de la mr propre (que mon avis hein)

Oui c'est vrai, celle-là est vraiment limite et maladroite, et compte-tenu des événements récents je comprends qu'elle puisse être interprétée au premier coup d'oeil comme assez abjecte ... Bon en tout cas c'est pas dans cette optique-là que je l'ai faite, plutôt l'inverse, j'imagine qu'on en discutera un jour autour d'une bière :wink: 

> en termes d'humour et de mème, je pense qu'il faut essayer de s'en tenir à 1 mème/image = 1 vanne et éviter de multiplier les vannes et sous-vannes sur la même image (sinon ça prend plus de 2 sec à décryter et comprendre)

J'en ai déposé quelques autres sur le CDN, "spécial été" on va dire. Je sais pas ce que vous en pensez, si c'est dans l'esprit ou pas ... Parfois je peux avoir l'impression d'être un peu méprisant et pas toujours inclusif, j'y travaille, en tout cas j'aimerais pas que ça puisse heurter, c'est pas l'idée. Et s'il y a besoin d'édulcorer ou changer des trucs j'ai toujours les `.qgz` (QGIS is the new paint !)

Ou si vous connaissez un psy qui propose des séances via tickets GitHub à des tarifs abordables ... :grin:

**Comment by gounux** [comment]
Je ferme l'issue, pas sûr que ce soit l'endroit ni le moment.
Merci pour les échanges et désolé pour la gêne occasionnée
